### ISSUE TITLE
Stripping of brackets leads to corrupt code

### ISSUE THREAD

**Issue by vielhuber** [prettier/plugin-php#1009]
**Prettier 1.16.4**

**PHP Plugin 0.10.2**

**Input:**

```php
echo '<select name="foo"><option value="bar"' . (@$_GET['foo'] === 'bar' ? ' 
 selected="selected"' : '') . '>bar</option></select>';
```

**Output:**

```php
echo '<select name="foo"><option value="bar"' . @$_GET['foo'] === 'bar' ? ' 
 selected="selected"' : '' . '>bar</option></select>';
```

**Expected behavior:**
```php
echo '<select name="foo"><option value="bar"' . (@$_GET['foo'] === 'bar' ? ' 
 selected="selected"' : '') . '>bar</option></select>';
```

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by aboyton** [comment]
Is there a way to run Prettier with a `--check-ast` flag so I can test Prettier doesn't break anything on a large codebase?

**Comment by czosel** [comment]
@aboyton Did you already try passing AST_COMPARE=1 to your command?

**Comment by evilebottnawi** [comment]
Problem in silent operator, investigate, without `@` all works fine

**Comment by czosel** [comment]
This is a parser issue related to the precedence of `silent` nodes, see https://github.com/glayzzle/php-parser/pull/455
