### ISSUE TITLE
coc.vim integration

### ISSUE THREAD

**Issue by jonleopard** [prettier/plugin-php#1012]
Hey guys,

No issue here, I was just wondering if anyone knew of a way to integrate this with [coc.vim](https://github.com/neoclide/coc.nvim)? I've been working on a php project, and the standard prettier is not formatting my php files very well at all.

Thanks for any help/input :)

**Comment by czosel** [comment]
Hi @jonleopard,

I'm currently using ALE to integrate this plugin with prettier in vim (as documented in the README). I haven't heard about coc.vim before, and after reading it's README i'm not sure how it should integrate. Would you expect it's `format` command to trigger `prettier`? Is that what it's doing for JS right now?

**Comment by jonleopard** [comment]
@czosel Yep, exactly!

Prettier currently works with coc.vim, there is some minimal set up mentioned in the [documentation](https://prettier.io/docs/en/vim.html#coc-prettier-https-githubcom-neoclide-coc-prettier). They have an [extension](https://github.com/neoclide/coc-prettier) set up for it as well (which I think interfaces with Prettier?). I have it disabled since Prettier doesn't know how to format php files very well at all (particularly blade files).

I'm still pretty new with coc.vim, so I'm not exactly sure what the proper way to go about integrating it would be (or if its even possible). I was mostly curious if anyone has already tried doing this.

Cheers :)

**Comment by czosel** [comment]
@jonleopard Alright, good to know! :slightly_smiling_face: In that case, it might be worth opening an issue over at https://github.com/neoclide/coc-prettier.
