### ISSUE TITLE
prettier-ignore kills function names

### ISSUE THREAD

**Issue by vielhuber** [prettier/plugin-php#1030]
**Prettier 1.16.4**

**PHP Plugin 0.10.2**

**Input:**

```php
<?php
// prettier-ignore-start
foo();
?>
    <span>OK</span>
<?php
bar();
// prettier-ignore-end
```

**Output:**
```php
<?php
// prettier-ignore-start
(); ?>
    <span>OK</span>
<?php ();
// prettier-ignore-end
```

**Expected behavior:**
```php
<?php
// prettier-ignore-start
foo();
?>
    <span>OK</span>
<?php
bar();
// prettier-ignore-end
```

**Comment by evilebottnawi** [comment]
I think it is bug in parser. Also we doesn't support `prettier-ignore-start`, i think we should do this

**Comment by czosel** [comment]
I wasn't able to reproduce this on the current master anymore. I'll close the issue given we don't support `prettier-ignore-start` / `-end`. Feel free to reopen it if similar issues occur related to `prettier-ignore`!
