### ISSUE TITLE
Automatic parentheses around multi-line print in expression have bad indentation

### ISSUE THREAD

**Issue by ahilke** [prettier/plugin-php#1045]
**@prettier/plugin-php v0.10.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbfCExZdLDiYDGUAMowAnmocwbAgAWgAmEBZoAEdBeGgABRNlOz05BRBiEQgYJLYU+2l0qABfFigKeBh0FDR4LElQNmwYNIMyzMwwQVa8EAAeAH4wajAAHUwJqRqACgASeABeAEYAbjn3AGpN-oWAHz2F7f6AThPNjcWiEjGQCdv1+ABSDYPrmFuNgAJbgEp7zCDAB8IBKQA)

**Input:**
```php
<?php

for($i=1;$c++<$i||$i++<99+$c=print"
";$i%$c||print"$c ")

?>
```

**Output:**
```php
<?php

for (
    $i = 1;
    $c++ < $i ||
    $i++ <
        99 +
            ($c = print "
");
    $i % $c || (print "$c ")
);

?>

```

**Expected:**
Line 9 - `");` - looks a lot like it is closing the `for` header. It should somehow be indented to avoid this confusion. Maybe like this:

```php
for (
    $i = 1;
    $c++ < $i ||
    $i++ <
        99 +
            (
                $c = print "
"
            );
    $i % $c || (print "$c ")
);
```

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by evilebottnawi** [comment]
Prettier do same https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgDpRZFYAkAllgLxYCMA3AcaWANQtYA8pFAPj48XJtOApkQCc4rC1FimOEmCpYADhjKwABgU0BKBoUEUApMyx9cajTHwhFWPCF26C+giAA0ICCphloAM7IoACGGBgQAO4ACmEIQSghAG4QZAAmniAARhghYADWcDAAyip5GgDmyDAYAK5wXgAWMAC2ADYA6o1k8AFlYHDF8T1kST0AnsjgAUFeGgFwGDDRuRUtIcioIW0LXgBWAQAeAEK5BUXFIS1wADIacJvbuyAHh8WVbXAAirUQ8I87BogMoYBYYKZZEJZcZtaCZKywDrpGCNZAADgADF41BAFh1ciopmo4GCkg8vABHX7wFY+BIgEIBAC0UDgcDS7MyGDgVLI3JWITWGyQW0BXgWLTI1TqQICH2+1IeIqeQJgUKRaRRyAATF4aiEyG1KgBhCAtdZTKDQckgWoLAAqUISooWAF9XUA

**Comment by evilebottnawi** [comment]
We should open issue in prettier before touch this here

**Comment by evilebottnawi** [comment]
We should open issue in prettier before touch this here
