### ISSUE TITLE
Invalid code when namespace is followed by HTML comment

### ISSUE THREAD

**Issue by joemaller** [prettier/plugin-php#1052]
**@prettier/plugin-php v0.10.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbfCExZdLDiYDGUAMowAnmocwbAgAWgAmEBZoAEdBeGgABRNlOz05BRBiEQgYJLYU+2l0qABfFigKeBh0FDR4LElQNmwYNIMyzMwwQVa8EAAeAH4wajAAAkw2ayhsMDZPMal0dABuMcGAPgAdTB3+gEIQkLGACVEAWQAZMfcbaZIxo+3MEBKgA)

**Input:**
```php
<?php namespace foo; ?>

<!-- HTML comment -->

```

**Output:**
```php
<?php namespace foo;



<!-- HTML comment -->

```

**Expected behavior:**

```php
<?php  namespace foo; ?>

<!-- HTML comment -->
```

Current output is invalid. 

**Notes:**
This seems to be specific to `namespace` declarations. I wasn't able to reproduce the problem with other declarations, assignments or function calls.

**Comment by evilebottnawi** [comment]
Bug, feel free to send a PR

**Comment by joemaller** [comment]
Found a few related examples. I suspect something about the way `namespace` is handled. 

---

This is the same as the original issue, the HTML comment is irrelevant, any HTML text will generate the same result.  The PHP closing tag `?>` collapses up then gets lost:
**@prettier/plugin-php v0.12.0**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxMNmsobDA2PwACKXR0AG5p6ZGAPh2SKAAPGGmQcqA)

**Input:**
```php
<?php
namespace foo;

?>

text

```

**Output:**
```php
<?php
namespace foo;



text

```

---

This next one might be two issues overlapping. `namespace` is left open as above, then the comment is wrapped as PHP.  Might be related to this other one. https://github.com/prettier/plugin-php/issues/1228

**@prettier/plugin-php v0.12.0**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxMNmsobDA2PwACKXR0AG5p6YB6XZWfG3mSHcwRgD4znQAPGGmQcqA)

**Input:**
```php
<?php
namespace foo;

// comment

?>

text

```

**Output:**
```php
<?php
namespace foo;

<?php
// comment
?>

text

```
