### ISSUE TITLE
array setting

### ISSUE THREAD

**Issue by mathieutu** [prettier/plugin-php#110]
Before/after
```diff
-    protected $fillable = ['title', 'description', 'requester_id', 'type', 'summary', 'proof', 'budget_id'];
+    protected $fillable
+        = ['title', 'description', 'requester_id', 'type', 'summary', 'proof', 'budget_id'];
```

(actually I don't know if this kind of message really helps you, I'm just reporting all the bugs I'm seeing, but tell me if it's not relevant.)

**Comment by czosel** [comment]
Hi @mathieutu, we definitely appreciate your feedback! Since we're bound to the 80 character limit, i guess your example should be formatted like this:
```php
protected $fillable = [
  'title', 
  'description', 
  (...)
];
```
/cc @evilebottnawi  @mgrip

**Comment by evilebottnawi** [comment]
@mathieutu yes, each item on new line better, no new option
