### ISSUE TITLE
Remove const public accessor 

### ISSUE THREAD

**Issue by mathieutu** [prettier/plugin-php#111]
```diff
-    public const PRICE_ATTRIBUTE = 'price_ht';
+    const PRICE_ATTRIBUTE = 'price_ht';
```

**Comment by mgrip** [comment]
@evilebottnawi just noticed now we _always_ print the visibility - is that intentional? If so we at least need to add that to the ast-clean function to fix `--debug-check` testing

**Comment by mgrip** [comment]
for reference: https://github.com/prettier/plugin-php/blob/master/tests/constants/__snapshots__/jsfmt.spec.js.snap#L31

**Comment by mathieutu** [comment]
How do you handle php version?
Because const visibility came with php7.1 so you can't add it if version is under. It will throw an exception. 😐

**Comment by nicoder** [comment]
@czosel proposed to target supported versions of PHP in this comment: https://github.com/prettier/plugin-php/issues/16#issuecomment-359151799

**Comment by mathieutu** [comment]
Ok. So my comment about not adding public when under 7.1 is relevant. 😕
