### ISSUE TITLE
Invalid output, "<?php" turned into "<?="

### ISSUE THREAD

**Issue by warpr** [prettier/plugin-php#1112]
**@prettier/plugin-php v0.11.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUwAegAqOem5gAIrMCCIeGVqGGXohgBGAE5lgDF0dCWZ6ZGAPmmh6gBmW9GAXmWAEgQYNWWRkbLADk-hsUGW0DA9RgQP+rxmz1uIHKQA)

**Input:**
```php
<?php
/**
* Copyright 2019 Foo
*/
?>
<h3><?= $title ?? 'Some report' ?></h3>
```

**Output:**
```php
<?=
/**
* Copyright 2019 Foo
*/
?>
<h3><?= $title ?? 'Some report' ?></h3>
```

EDIT: <?= is not the same as <?php, so this change breaks this code.

**Comment by evilebottnawi** [comment]
I think it is bug in parser :di

**Comment by zarv1k** [comment]
I just noticed that It reproduces only in a case when the next php tag in the php-view file is the short-tag (`<?= ?>`), so [there is no issue](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwAegAqXa2AAl3DgAEANzYIQ-GIFUOAEjYj3e2tlYA+LaXsMDZMD6rdaHKAxajoR5sQ6fJbbX7-L6YH5-AGrAC8kOhgLhKI+IHaQA) when the next php tag is full php tag (`<?php ?>`)

**Comment by evilebottnawi** [comment]
@zarv1k you can try to fix it, logic is not hard
