### ISSUE TITLE
$a[$b]{$c};  -> Parse Error : syntax error, unexpected '{', expecting ';' on line 3

### ISSUE THREAD

**Issue by HenkPoley** [prettier/plugin-php#1152]
**Prettier 1.18.2**

**PHP Plugin 0.11.2**

```sh
# Options (if any):
```

**Input:**
Code is accepted by at least PHP 5.6-7.1, and is found in https://github.com/tcpdf-clone/tcpdf/blob/master/tcpdf_barcodes_1d.php#L467

```php
<?php

$a[$b]{$c};    
```

**Output:**
```php
Parse Error : syntax error, unexpected '{', expecting ';' on line 3

  1 | <?php
  2 | 
> 3 | $a[$b]{$c};
    |      ^
```

**Expected behavior:**
Possibly:
```php
<?php

$a[$b][$c];       
```
I'm not very sure, seems to be string access that *was to be* deprecated in PHP 6.0, in that case, *maybe* keeping the `{$c}` notation is more clear, to show the difference to array access ? Though it seems `prettier-php` has already decided on `[$c]` elsewhere.

**Comment by evilebottnawi** [comment]
It will be fixed in next release, we already work on this https://github.com/prettier/plugin-php/pull/1153

**Comment by evilebottnawi** [comment]
Output was
```
$a[$b][$c];
```
