### ISSUE TITLE
Reformating chaining

### ISSUE THREAD

**Issue by mathieutu** [prettier/plugin-php#116]
Same here, I can understand why it made that, but I think this is not a good idea:

```diff
-        Route::prefix('api')
-             ->middleware('api')
-             ->namespace($this->namespace)
-             ->group(base_path('routes/api.php'));
+        Route::prefix('api')->middleware('api')->namespace($this->namespace)->group(
+            base_path('routes/api.php')
+        );
```

**Comment by evilebottnawi** [comment]
@mathieutu yep, for future https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoWATrrAOq4AmMAFsgBwAMGMAhgEbV2NIAmDAQoBzADZwAigFcI8ZADMO4gnHakOucWIDCEALYGOyEFGhx0ILprABrODADKWDmDHIYpGepAArAgAPACFbB2cOAzgAGQpLJGVVX1dSNVJTLm4AT3FoKzUDXE9vXxk1ABVuIgSVNQwKNJgABU1RYyVa31I4AEcZXG6WjjaTGqSMMgg1Sk0sUzI4NIA3SwwOUlIIAHcm9YRqkA4liForGggwDvHDghgruswZGCwngXu4AF8PoA please check how it is output in js if output pretty when we have feel free to open issue (if js have same syntax)

**Comment by mathieutu** [comment]
Ok, thanks! 

I've tried in js and indeed, it's a bug!

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAlCBXeA6ADgJzgDMBLADwAoByAQ1xKoEoAdKZmbAWxIBMeAbOAHcahanQYs2HKDU5wAzrhpg41IhAhNW7bAHN8mXBQBGNBXAD6ymAAtqhrIoD0EvLdxNGAbhAAaEAhcGBJoBWRQUUMhAAVRBHCUGgA3CF5-EHMYZCIafgsAk3wVAGs4GABlZTASKD1kGHwMOACeCDAcvIKQWot8GBjivU4aTvyWkAArBTIAIWKwMsq5OAAZWrgx7swYXCwAJi2J5Xw+5BAzEwBPfmgMglqYAHVeO2QADgAGAIIICyfirhzgRFHB8MlNgFCABHDAkQiDGjDUZIXLjAIWbgNJoTBS1PSCACKGAg8COARgNBMLx4byQ+wpxRI-HxAGEIJwRucoNBISAMBYACpUxJoiwAX3FQA

**Comment by czosel** [comment]
JS reference: https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L3886
Looks quite complex 😅
