### ISSUE TITLE
Bug unintentional type cast from float to int 

### ISSUE THREAD

**Issue by Selion05** [prettier/plugin-php#1163]
**@prettier/plugin-php v0.11.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxpgBIfaigfAGsAAgBeVYBGADoN9c3dhgBuaen4KVWACnnFlYBKVeBp1dfVpep0VYByY0Eob6nTDld4GJ4vN4fL7ffQiQHTcrTKGrJz2AD6AFFkAAZY4gcpAA)

**Input:**
```php
<?php

$check = 1. === 1.0;

if ($check) {
    echo 'true';
} else {
    echo 'false';
}
echo PHP_EOL;
```

**Output:**
```php
<?php

$check = 1 === 1.0;

if ($check) {
    echo 'true';
} else {
    echo 'false';
}
echo PHP_EOL;

```
A number `1.` should be formatted as `1.0` not `1`

Btw nice issue reporter :D

**Comment by evilebottnawi** [comment]
hm, why you need `.` here? Prettier do same https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASMALOYDWACAXjwEYA6QgosgBgG4AdKRgSwDM8AKdLXASj2CM8wvKgBuAQwBOhPAHIYUgK5w5DKAF88cADYBnOAKEjx02XNYT9q9RsYgANCAgAHGM2h7koaVIgB3AAVpBC8UCTEIZgATRxAAIykJXDgYAGUXZOYoAHNkRRUnDBgAWx0AdQxmeD1MsDg00OrmMWqAT2RwPS8nbIMpGECknJKJZEtrJwArPQAPACEklPSJErgAGWy4casDabm07JydOABFJQh4HcmQTKl+zviJeLadaDiXKWyYcpiYDGQAA5qE5PhADOUki5Op84P0xNsnABHC7wIauMIgCR6AC0UDgcGihLiUjgKOYpKGEhGYyQEz2IAMJWY+WUcCceiOJ3Ol22dN27JAMGev2i-2QACYnIoJMwdEcAMIQEqjTpQaCIkBKAwAFWeYXpcA0GiAA

**Comment by Selion05** [comment]
Well the point is your javascript example does not change the behavior (both versions are `true`) while in the php example the pre formatting outputs `true` and and post formatting outputs `false`

**Comment by evilebottnawi** [comment]
Yes, bug :+1: Will be fixed in next release

**Comment by evilebottnawi** [comment]
Fixed https://github.com/prettier/plugin-php/pull/1167
