### ISSUE TITLE
[PSR-12] Trait use formatting

### ISSUE THREAD

**Issue by loilo** [prettier/plugin-php#1178]
> **Disclaimer:** I am aware that it's not make-or-break for Prettier to adhere to PSR-12.
>
> However, now that it is officially accepted as a standard, we should discuss (and, if necessary, reject) each current violation of PSR-12 — if only to have point to refer to in future discussions or issues.

### PSR-12 Violations

1. > The `use` keyword used inside the classes to implement traits MUST be declared on the next line after the opening brace.
   > – [Section 4.2](https://www.php-fig.org/psr/psr-12/#42-using-traits)
2. > Each individual trait that is imported into a class MUST be included one-per-line and each inclusion MUST have its own `use` import statement.
   > – [Section 4.2](https://www.php-fig.org/psr/psr-12/#42-using-traits)
3. > Otherwise, it MUST have a blank line after the `use` import statement.
   > – [Section 4.2](https://www.php-fig.org/psr/psr-12/#42-using-traits)

[Playground Link (contains all listed violations)](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxpn1k27AACAFkgi3nsbGngacW9xYB6A8XRaigRRexqdEFZCkWOKEuwcxhF4kWYAHd0RYADYRQP6Xdg6axQEhbTD7Q7HACC8l+NCQTyuNzuDyebAe80wAGtFuZMFipDoIJ8zoS2m8ASJge02GCITBdvtAScTLU4UwOaYYAAhADcrL2fQ45h8iykgkwPgw0PBNHQFAAFABKRbAcqskWwk7UeBLazCN7KX6MilPR7KYiYFSLdBSS2LOYLXXs0ScmAWYWYcogcpAA)

**Comment by evilebottnawi** [comment]
I think will be great put here example(s) what we expected

**Comment by loilo** [comment]
Expected is basically what I put into the playground link.

So this input:

```php
<?php

class MyClass
{
    use TraitA, TraitB;
    public function method() {}
  
    use TraitC;
}
```

Should more or less produce this output:
```php
<?php

class MyClass
{
    use TraitA;
    use TraitB;
    use TraitC;

    public function method() {}
}
```

**Comment by evilebottnawi** [comment]
Oh, rewrite one `use` to multiple and/or moving `use` to above are out of scope prettier, also adding new lines is bad idea and can annoy many developers. 

I think here we need linter.

**Comment by loilo** [comment]
Very much possible.

**Comment by glen-84** [comment]
I guess this issue can be closed as out-of-scope (wontfix)?

**Comment by loilo** [comment]
We can. Thanks for the reminder.
