### ISSUE TITLE
Bug: comment in prettier-ignore node doesn't print

### ISSUE THREAD

**Issue by samsch** [prettier/plugin-php#1193]
**@prettier/plugin-php v0.11.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxpgHpZgAJIWAQkSPhld2hpgBI2BYBeBYBtaYXzhfnznXbpgF0AbhByoA)

**Input:**
```php
<?php

// prettier-ignore
$a = [
    //  test
];
```

**Output:**
```php
Comment "//  test" was not printed. Please report this error!
```

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by czosel** [comment]
I'll go ahead and close this as a duplicate of #1402.
