### ISSUE TITLE
Ampersands (&) being removed from reference binding assignments

### ISSUE THREAD

**Issue by em4nl** [prettier/plugin-php#1211]
**@prettier/plugin-php v0.11.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxpn1k27AACACV0fqRF4GnFxe2dxYB6A8WAOjO9vZ32tgQfRalBTB8MTEWAMmNEAH08pBgACjeABJPoZFkCwDdqF8RBkoCRsExwcQKFAAB4ASk2l32O3gUkW-wAhPBsCIARCoTCoHCEQBtIEo9EAXQxWK2r1xXJ20BggggrxBEEQAG4cbjyuL9kDYdZ4TBFgBecGQmjU2kwbAMplo5limac7n4wntCBqTD-GU0uUkLEAPkWDHeb3BsvldIYzKViuVAHIAFS+9lS7lA9yopXvESyKR4PCgn44P5fADuZgoPjYEAoX3DUEtoKRVo1GP13J25UWUAMxv+pvNlrdtsWDqdbxdxZtMA9Xp9frwQexhvLOzD6Ajyre0dj8eFUET+RgX0hJmsufH+aFiCLTZgpZDi0r1ZEQ5HuLHE6j1ZnCd+BRh7Fu69RBbnO+t8v3w4lB95-Ne05xreSYFJaeZFqq0K7oiyKYKiaKLAA1IsACMX4-pg5QgOUQA)

**Input:**
```php
<?php

class Router {
  
    // ...
  
    static function &trie_insert(&$trie, $path_segments, $index) {
        if (!isset($path_segments[$index])) {
            return $trie;
        }
        $segment = $path_segments[$index];

        if (strlen($segment) > 0 && $segment[0] === '*') {
            $node = &self::trie_insert_wildcard_node($trie, $segment);
        } elseif (strlen($segment) > 0 && $segment[0] === ':') {
            $node = &self::trie_insert_param_node($trie, $segment);
        } else {
            $node = &self::trie_insert_static_node($trie, $segment);
        }
        return self::trie_insert($node, $path_segments, $index + 1);
    }
}
```

**Output:**
```php
<?php

class Router
{
    // ...

    static function &trie_insert(&$trie, $path_segments, $index)
    {
        if (!isset($path_segments[$index])) {
            return $trie;
        }
        $segment = $path_segments[$index];

        if (strlen($segment) > 0 && $segment[0] === '*') {
            $node = self::trie_insert_wildcard_node($trie, $segment);
        } elseif (strlen($segment) > 0 && $segment[0] === ':') {
            $node = self::trie_insert_param_node($trie, $segment);
        } else {
            $node = self::trie_insert_static_node($trie, $segment);
        }
        return self::trie_insert($node, $path_segments, $index + 1);
    }
}

```

The ampersands are being removed from assignments like `$x = &f();` where we want to bind a reference returned from a function to a variable, turning it into a normal, copying assignment, which breaks the code.

https://www.php.net/manual/en/language.references.return.php

**Comment by evilebottnawi** [comment]
Thanks for issue, should be fixed in master

**Comment by czosel** [comment]
This is indeed fixed and has just been released as part of `v0.12.0`.

**Comment by em4nl** [comment]
Thank you! I can confirm it's fixed.

**Comment by adamaveray** [comment]
It looks like assigning by reference within an array to another array value might've broken during that change.

Works:

```php
<?php
$test = ['key' => &$value];
```

Used to work but now doesn't (ampersand is removed):

```php
<?php
$test = ['key' => &$value['something']];
```

A workaround for now is:

```php
<?php
$test = [];
$test['key'] = &$value['something'];
```

**Comment by czosel** [comment]
On the current master even the first example is not printed correctly - thanks for reporting!
