### ISSUE TITLE
Not working on vscode

### ISSUE THREAD

**Issue by jmperro** [prettier/plugin-php#1213]
Hello to all!
I've the latest version of the extension in vscode.
I've installed the prettier/plugin-php on the project folder.
I've restarted vscode several times.

The extension still not working, when I try to format a php file vscode ask me to install a formatter.

**Comment by evilebottnawi** [comment]
Please provide steps what you do

**Comment by jmperro** [comment]
1. Install globally prettier and pretier-php (npm install --global prettier @prettier/plugin-php)
2. Install extension Prettier on VSCode
3. Install prettier and prettier-php on project folder (npm install prettier @prettier/plugin-php)
4. Restart VSCode
5. Open project, open a php file and run Format Document

**Comment by evilebottnawi** [comment]
What prettier do you use? Global or local?

**Comment by jmperro** [comment]
I've installed both, how do I check what I'm using?

**Comment by robo-wg** [comment]
I have the [same problem](https://github.com/prettier/prettier-vscode/issues/1055).

**Comment by evilebottnawi** [comment]
Can you report issue in `VSCode` plugin repo?

**Comment by jmperro** [comment]
I've created a new issue on prettier-vscode repo

https://github.com/prettier/prettier-vscode/issues/1059

**Comment by glen-84** [comment]
@jmperro Did you get it working? (it works fine for me on Windows 10)

**Comment by jmperro** [comment]
Yeah, using yarn I get it working fine!

Ing. José María Romero Cuny
Vector-IT

**Comment by glen-84** [comment]
I guess this can be closed then?

**Comment by jmperro** [comment]
Yeah!

Ing. José María Romero Cuny
0351 155 194412
Vector-IT
