### ISSUE TITLE
Long computed array keys are broken into multiple lines

### ISSUE THREAD

**Issue by liangchunn** [prettier/plugin-php#1226]
**Prettier 1.16.4**

**PHP Plugin 0.11.2**

**Input:**

```php
<?php

$a = [
    self::REALLY_LONG_STATIC_VARIABLE_1 . '_' . self::REALLY_LONG_STATIC_VARIABLE_2 => 'ABC'
];
```

**Output:**

```php
<?php

$a = [
    self::REALLY_LONG_STATIC_VARIABLE_1 .
    '_' .
    self::REALLY_LONG_STATIC_VARIABLE_2 => 'ABC'
];
```

**Expected behavior:**
Not breaking computed keys into new lines

**Comment by czosel** [comment]
Prettier for JS seems to do [the same](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mwAOlJpgNokgCG9DjTz9NmA1JjQEa9-8DBgtpxphxEyVMk0AukkwBGAEwBmMgF8QAGhAQADjACW6ZKFoAnCxADuABUsI0yOgDcIRgCY6Q3C7TAAazgYAGV9AKMoAHNkGAsAVzhdAAsYAFsAGwB1FKN4NAiwOFCnfKNXfIBPFzA0Z10otDgLGDt-aPTaZGxaTObdACs0AA8AIX8gkNDadLgAGSi4Hr6BkGGR0KjozLgARQSIeBX+5JAIi2aLF25abjhMn30LKJhsrxgU5AAOAAZdZ4QZrZfz6FzPOBXVzLXQAR0O8HaBmcKFoaAAtFA4HBPDifBY4PCjAT2rROt0kL1TrpmukjHFEmc0NtdgcjstKaszjA7u9PJ9kMpdPFaEZMtsAMIQdJdFxQaAwkAJZoAFTuKKpa1cSQAklBcbBQmAXoYAIL60IwKq7E7NDQaIA), and I couldn't find anything about this in PSR2 or PSR12. Is there any reference saying that computed array keys should not be broken up?
