### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Cvar1984** [prettier/plugin-php#1239]
[error] Invalid configuration file `as/b374k.php`: EACCES: permission denied, scandir '/data/data'

u0_a115@localhost:~$ prettier ~/as/b374k.php --write
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main                                            # science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable                   # game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable                        # unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:                                                               Linux localhost 3.18.71-perf-g5c5b6e3 #1 SMP PREEMPT Tue Nov 5 23:37:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 5A

**Comment by evilebottnawi** [comment]
Something wrong with your environment, we can't help here, sorry
