### ISSUE TITLE
Converting Single line multidimensional array into new line. 

### ISSUE THREAD

**Issue by lianglee** [prettier/plugin-php#1240]
Question: is this possible?

Input 
`$array = array('abc' => 'def' , 'aei' => 'val');
`
Expected:
```
$array = array(
           'abc' => 'def' , 
           'aei' => 'val'
);
```
Output:
`$array = array('abc' => 'def' , 'aei' => 'val');`

**Comment by czosel** [comment]
Hi @lianglee,

We're implementing the same behavior as prettier for JS does for objects: If the input is on one line, and fits on it, it stays on one line. If the input contains a linebreak or doesn't fit on one line, it's formatted as you expect. See [this example](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxpgBI2CBMggAIAXmWFpYAKaeXlgHJOH321gD4DiigpE6YDtih4E9Xz-YA3OX2ASgBuaZByoA).

**Comment by lianglee** [comment]
Is there any way / configuration that always do a line break?

**Comment by czosel** [comment]
The only way I see involves a code change in the plugin...

**Comment by lianglee** [comment]
Thanks

**Comment by czosel** [comment]
Sure!
