### ISSUE TITLE
glayzzle/php-parser github package

### ISSUE THREAD

**Issue by umdstu** [prettier/plugin-php#1252]
For some reason the php-parser is pointing to the github path for this package, rather than the npm tracked version. Is there a reason for this, or could this be updated to use npm?

I see that the branch you're using, #prettier, is 15 commits behind master. Having this point to github instead of npm makes it hard to use this package behind a proxy.

Thanks

**Comment by evilebottnawi** [comment]
because "Work in Progress" and we try to get all latest fixed in parser

**Comment by umdstu** [comment]
Ok thanks!
