### ISSUE TITLE
Nowdoc: invalid trailing comma

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#1292]
```php
call(
    $var
        ? "foo"
        : <<<'EOD'
        string
        string
        string
        EOD
);
```
is formatted as
```php
call(
    $var
        ? "foo"
        : <<<'EOD'
        string
        string
        string
        EOD,
);
```
which is invalid.

**Comment by loilo** [comment]
The same error happens in arrays.

So, what would be the intended behavior here? Omit the comma if the heredoc is (part of) the last item of a array/function call, otherwise put the comma on an extra line?

**Comment by czosel** [comment]
I think we should omit the training comma if the last element is a heredoc/nowdoc - it’s not exactly pretty 😉

**Comment by loilo** [comment]
Sure, but invalid code is not only generated with trailing commas but also if it's a "regular" comma:

```php
<?php

[
  $var
  ? "foo"
  : <<<'EOD'
        string
        string
        string
EOD
  , "bar"
];
```

In that case, we probably want to put it on an extra line.
