### ISSUE TITLE
Short arrow functions is not working

### ISSUE THREAD

**Issue by SuddenlyRust** [prettier/plugin-php#1319]
**@prettier/plugin-php v0.12.0**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxptggTIIB9OzAACmmAAg2pTFWAEjnlAEYmDYOIZWiASg2AXgA+M8OjjYA6J4vopk2NgG0fraTcDQOCICBAu6PIEQdA+ADW2CB30wWwAusirgBuaYgcpAA)

**Input:**
```php
<?php

array_map(
  fn($arg1, $arg2) => $arg1 . $arg2,
  [
    "prettier" => "rocks",
  ],
);

```

**Output:**
```php
Parse Error : syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' on line 4

  2 | 
  3 | array_map(
> 4 |   fn($arg1, $arg2) => $arg1 . $arg2,
    |                   ^
  5 |   [
  6 |     "prettier" => "rocks",
  7 |   ],
```

**Comment by evilebottnawi** [comment]
Latest version with supporting arrow functions is not released right now

**Comment by SuddenlyRust** [comment]
Is there already an approximate date when the release will come?

Thank you for your quick response @evilebottnawi and all the work you put into this plugin 🤗

**Comment by czosel** [comment]
Unfortunately, we can’t give any estimates on release dates; I’m not sure when I’ll find the time to work on the plugin and I think the situation is similar for the other contributors. 
You could try the current master branch though, where partial support for PHP 7.3 and 7.4 has already landed (including arrow functions).

**Comment by SuddenlyRust** [comment]
Gonna try it out later (hope it works 🙏) and thank you so much for for the quick response @czosel. Wish you all the best with this project.

I really enjoy the philosophy of prettier and hope someone finds the time to keep this project running.
