### ISSUE TITLE
[Bug] Object property types are being deleted

### ISSUE THREAD

**Issue by phjl** [prettier/plugin-php#1336]
Looks like class property types are just being removed since updating to the latest version of prettier-php.

**Input**
```
protected Organization $organization;
protected string $event;
protected string $jobId;
protected string $candidateId;
```

**Output**
```
protected $organization;
protected $event;
protected $jobId;
protected $candidateId;
```

**Versions:**
prettier: 1.19.1
@prettier/plugin-php: 0.13.0

**Comment by czosel** [comment]
@evilebottnawi no, I think this is still missing (assuming https://github.com/prettier/plugin-php/issues/854 is up to date).

**Comment by skyrpex** [comment]
thanks! happy quarantine.
