### ISSUE TITLE
Nullable property types are incorrectly stripped from output

### ISSUE THREAD

**Issue by duclet** [prettier/plugin-php#1348]
**Prettier 1.16.4**

**PHP Plugin master**

```sh
# Options (if any):
```

**Input:**

```php
class MyClass {
    private ?string $name;
}
```

**Output:**

```php
class MyClass {
    private string $name;
}
```

**Expected behavior:**
```php
class MyClass {
    private ?string $name;
}
```

**Comment by czosel** [comment]
Thanks for the bug report! This should be relatively easy to fix - I might get to it on the weekend, if someone else wants to take a shot please go ahead :slightly_smiling_face:
