### ISSUE TITLE
trailingCommaPHP not accepting string value

### ISSUE THREAD

**Issue by derekparsons718** [prettier/plugin-php#1373]
### Introduction

There seems to be an incongruity between the documentation and functionality of version 0.14.0.

### Producing the Error

Running prettier with `"trailingCommaPHP": "none"` yields the following error:

```
Invalid trailingCommaPHP value. Expected true or false, but received "none".
```

Changing the value from `"none"` to `false` fixed the issue.

### System
prettier-php: v0.14.0
prettier: v2.0.2
Installed locally and run using npm.
Configuration:

```javascript
"prettier": {
      "printWidth": 80,
      "tabWidth": 3,
      "useTabs": false,
      "semi": true,
      "singleQuote": false,
      "quoteProps": "as-needed",
      "trailingComma": "none",
      "bracketSpacing": true,
      "arrowParens": "always",
      "proseWrap": "preserve",
      "htmlWhitespaceSensitivity": "css",
      "endOfLine": "lf",
      "overrides": [
         {
            "files": "*.php",
            "options": {
               "phpVersion": "7.2",
               "singleQuote": true,
               "trailingCommaPHP": "none", // <-- This is the problem
               "braceStyle": "psr-2",
               "tabWidth": 4
            }
         }
      ]
   }
```

### Conclusion

The documentation says that "none" is a valid option for trailingCommaPHP, as does the release notes for v0.14.0. I must conclude that this is either a bug or incorrect documentation.

**Comment by czosel** [comment]
Thanks for the bug report! It seems that the option has actually been refactored into a Boolean, even though it's documented differently. Can you try setting the option to `false` instead?

@evilebottnawi @loilo If you agree with `true`/`false` instead of `all`/`none`, I'll update the documentation to reflect this.

**Comment by loilo** [comment]
I do. I had also written it that way in the 0.14 branch of the playground some months ago. 😁

**Comment by czosel** [comment]
:+1: I totally forgot about this :see_no_evil: Since it's just a documentation issue, no need for a new release :+1:

**Comment by derekparsons718** [comment]
I thought that might be the case. Thanks for clarifying, and for all of your hard work! :)
