### ISSUE TITLE
Pretty output double quotes strings

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#138]
We have two syntax:
- Easy
```php
$string = "Foo ${bar}";
```
- Complex (curly) syntax 
```php
$string = "Foo {$bar}";
```

Ref: http://php.net/manual/en/language.types.string.php

Should we:
1. Output encapsed string as is.
2. Output always into complex (curly) syntax.

**Comment by czosel** [comment]
I'd leave them the way we find them for now, because for complex expressions the two styles have different meaning. That requires https://github.com/glayzzle/php-parser/issues/101 to be implemented though.

**Comment by czosel** [comment]
I'll close this for now since there is a PR for the parser feature now :smile:
