### ISSUE TITLE
Impossible to use variable substitution in key of generators.

### ISSUE THREAD

**Issue by 0x450x6c** [prettier/plugin-php#1390]
**@prettier/plugin-php v0.14.0**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCADsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtqUFMGIxMAAIpdHQACgBKI+Ato6OAEh1xo4BeI4BGbIBmAG47o5JRCyChHDZRNgQG5PKDjdrgt4APk+P3+mHaIHaQA)

**Input:**
```php
<?php

function foo() {
  $test = 123;
  yield "bar {$test}" => 123;
}
```

**Output:**
```php
Parse Error : syntax error, unexpected '"', expecting ';' on line 5

  3 | function foo() {
  4 |   $test = 123;
> 5 |   yield "bar {$test}" => 123;
    |        ^
  6 | }
```

**Comment by czosel** [comment]
Thanks for the bug report @0x450x6c! This is most likely a parser issue, I created an issue there: https://github.com/glayzzle/php-parser/issues/532.
