### ISSUE TITLE
missing variadic support in printer

### ISSUE THREAD

**Issue by oadam** [prettier/plugin-php#143]
my_func($a, ...$b);

becomes

    my_func($a, Have not implemented kind variadic yet.);

**Comment by evilebottnawi** [comment]
@oadam Thanks for issues

**Comment by oadam** [comment]
@evilebottnawi happy to contribute. I've been searching for a php equivalent of gofmt for a very long time, I'm super excited :smiley: !

**Comment by evilebottnawi** [comment]
@oadam :+1: More issues === quick stable release
