### ISSUE TITLE
Publish a new 0.14.1 patch version of this plugin to fix NPM warning about peer dep on prettier package

### ISSUE THREAD

**Issue by tonix-tuft** [prettier/plugin-php#1431]
Hi guys,

the version of this plugin you have published to NPM is not up-to-date with the code of this repo.

Check out the `package.json` file published on the NPM registry: https://unpkg.com/@prettier/plugin-php@0.14.0/package.json

You will see that it lacks the correct `peerDependencies` definition for prettier `^2.0.0`:

```js
{
  ...
  "peerDependencies": {
    "prettier": "^1.15.0"
  },
  ...
}
```

Whereas in this GitHub repo, if you look at the `package.json` of the `0.14.0` version on the master branch -> https://github.com/prettier/plugin-php/blob/master/package.json, the `peerDependencies` key is correct:

```js
{
  ...
  "peerDependencies": {
    "prettier": "^1.15.0 || ^2.0.0"
  },
  ...
}
```

This leads to the misleading warning when installing this package and already having `prettier@^2.0.0` installed:

```bash
$ npm i --save-dev @prettier/plugin-php
npm WARN @prettier/plugin-php@0.14.0 requires a peer of prettier@^1.15.0 but none is installed. You must install peer dependencies yourself.

```

### Proposed fix
Just release a new `0.14.1` patch version and publish it to NPM so that `0.14.1` will have the correct `peerDependencies` key in its `package.json` on the NPM registry.

**Comment by czosel** [comment]
[Done!](https://github.com/prettier/plugin-php/releases)
Sorry about the delay.
