### ISSUE TITLE
--require-pragma ignores pragma in many situations

### ISSUE THREAD

**Issue by warpr** [prettier/plugin-php#1462]
**@prettier/plugin-php v0.14.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-MIgIlmIRCBgytgq2PTkRAF8WKAp4GHQUNHgsSVA2bBg2gy6QYjBBSbwQAB4AfmMwAAIKKBjZNmgACgmIeBiYAH1ksChsAF4ARgBKAG4AHUwAegAqb82AAUgsAQSE230+Hw+ABJqFBZLJ0Js7ps3iBYfD0EwUSAPnZsQB3AayCgAQlRuOxb0hIBeIA6QA)

**Input:**
```php
<?php declare(strict_types=1);
/** @prettier */

$hello = "hello, "
. "world!"
. "\n";
```

**Output:**
```php
<?php declare(strict_types=1);
/** @prettier */

$hello = "hello, "
. "world!"
. "\n";
```

Hello!

Our typical boilerplate for PHP files looks like this:

```php
<?php declare(strict_types=1);
/**
 * Application name / description (1 line)
 *
 * @copyright     Copyright (c) 2020, Company name LLC.
 * @license       MIT
 * @prettier
 */
```

But running prettier with `--write --require-pragma` doesn't reformat these files.  The equivalent boiler plate does work for javascript files, so this seems to be a bug.

**Comment by czosel** [comment]
Hi @warpr,

PSR-12 seem to suggest [placing the file-level docblock before the declare statement](https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements). Would that be an option for you? Like that, the pragma works ([see playground](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-MIgIlmIRCBgytgq2PTkRAF8WKAp4GHQUNHgsSVA2bBg2gy6QYjBBSbwQAB4AfmMwAAIAHUwAegAqA82AAUhYBCRNg73diigY2TZoAAoJiHgYmAB9ZLAobAAXgAjABKADcu12ABJqFBZLJ0JtATsQHCEegmKjdnZUQB3AayCgAQm2IBx2KhIHBIA6QA)).

**Comment by warpr** [comment]
@czosel yes, I didn't know that was recommended by PSR-12, that will probably work for us, yes.  Thanks for the response!

**Comment by czosel** [comment]
Great! You're welcome :upside_down_face:
