### ISSUE TITLE
(S)CSS Inline curly braces for one liners

### ISSUE THREAD

**Issue by Sensanaty** [prettier/plugin-php#1469]
I couldn't find anything about this anywhere.

Is there a way to disable/alter warnings for the following syntax?

![image](https://user-images.githubusercontent.com/24919018/85933026-78f22700-b8d2-11ea-8266-67fb93cab80e.png)

Prettier will put these onto separate lines like this:

```css
.letter-l {
    grid-area: letterL;
}
```

Which for me personally just isn't as good as it takes up an unnecessary amount of space (6 LOC for this! I have this pattern at least 4 or 5 more times in this file alone, that's 30 extra lines of code for no real reason!). Note that I'm not chaining 2 or more declarations together, for example: ` .letter-l { grid-area: letterL; color: white; font-size: 3rem; }`, I only use this oneliner when I have a singular declaration to make

**Comment by orionrush** [comment]
@Sensanaty, even a one line explanation is sufficient. Summary closures for expediency are toxic for community participation.
