### ISSUE TITLE
PHP CS Fixer integration clarity

### ISSUE THREAD

**Issue by Bluefitdev** [prettier/plugin-php#1478]
Hey guys,

sorry for opening an issue.. just a quick question. I tried to followed your recipe but I don't think i got it properly

Here's my .php_cs

```
<?php

require_once('./PrettierPHPFixer.php');

return PhpCsFixer\Config::create()
    ->registerCustomFixers([
        (new PrettierPHPFixer()),
    ])
    ->setRules([
        'Prettier/php' => true,
    ]);
```

Copied and paste the `PrettierPHPFixer.php` straightaway. When you said integration, you meant that we are using php_cs_fixer right? I'm using php cs fixer as an auto formatter in my vscode pointing to the `.php_cs` above. However it doesn't format it according to the prettier at all. Just follows the cs fixer rules. However if i changed my default formatter to prettier it works, but I want to integrate both of them.

How do I achieve this?

Thanks!

**Comment by czosel** [comment]
cc @Billz95

**Comment by Billz95** [comment]
@czosel  thanks for the cc
@Bluefitdev Just tested it out, seems to be an issue with vscode's php-cs-fixer plugin.

It has `--rules=` enabled when executing the php-cs-fixer. When using `--rules` in php-cs-fixer, it seems it will ignore things you have in `.php_cs`. Thus it will ignore the configuration for the prettier. Not sure if there's a workaround, will look into that

**Comment by Billz95** [comment]
@Bluefitdev alright, so after playing around with the plugin a bit, it turns out you just have to set
```json
"php-cs-fixer.config" : "/path/to/.php_cs"
```
in your vscode php-cs-fixer setting. Then the plugin will regard the config properly. Let me know if there's  still any issue. cheers

**Comment by robertwt7** [comment]
Love the quick reply guys, thanks!
