### ISSUE TITLE
Wrong Parentheses

### ISSUE THREAD

**Issue by aleppos** [prettier/plugin-php#1501]
**Prettier 2.0.5**

**PHP Plugin 0.14.3**

```sh
# Options (if any):
--single-quote
```

**Input:**

```php
<?php

			$test = true AND true;
```

**Output:**

```php
<?php

($test = true) and true;

```

**Expected behavior:**
```php
<?php

$test = (true && true);

```

**Comment by czosel** [comment]
Hi @aleppos 

I think the current formatting is correct, the parentheses acutally highlight a potential bug: `AND` and `&&` are not equivalent in PHP - `AND` has lower precedence, even lower than the assignment operator (`=`). See https://stackoverflow.com/questions/2803321/and-vs-as-operator for details.

**Comment by evilebottnawi** [comment]
Yes, we don't change your AST, so adding parens in this case is invalid, it is expected behavior to catch same bugs
