### ISSUE TITLE
Indent complex conditions

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#153]
Input:
```php
                        if (
                            $showNoticeValue === '1' &&
                            !is_null($currentService) &&
                            $currentService->getServiceId() === $activation->getServiceId()
                        ) {
```
Output:
```php
                        if (
                            $showNoticeValue === '1' &&
                            !is_null($currentService) &&
                            $currentService->getServiceId() ===
                            $activation->getServiceId()
                        ) {
```
I'd suggest
```php
                        if (
                            $showNoticeValue === '1' &&
                            !is_null($currentService) &&
                            $currentService->getServiceId() ===
                                $activation->getServiceId()
                        ) {
```

**Comment by mgrip** [comment]
sounds good 👍 i can try to take a look later today. might see if i can rope in https://github.com/prettier/plugin-php/issues/375 as well

**Comment by mgrip** [comment]
interestingly enough, prettierjs actually prints w/o the [indentation](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQB0qaYAkAzgBYQDuAchDKmHAGoCGANgK5yYC8fmAcgCMAzADIx+QgEJUJAPpQObNtiJgOAJ00IYAZTiaAbgzgBKcZILEN23QeOmAdAHM4+wycYBJACbYLPh4pYhYweiMWemhXdwcvOD8A-AtgEMgoEhhMeCzeTCEAbnwAXxAAGhAIAAdozORQFm0qAAUmhBJkEBYjCFRfCu6s5HR2EjhKgCNNMIBrOOqw1CgXZBhNLkrfCDARsYm0TMMYFpmXAFsWPbZxyoArEgAPACEZsHn9FnO4ABlluGutyqHBg1RBACZAQdFppxpoupMWJMAJ5saCDaqaZYwADq-RgZGQAA4AAyVTEQcY4mbVLqYuBwowAyo6ACOHFQOlOLAuVyQoxuB3G51Qaw2QuWLjYcAAihw6AD+ftKjAkXjfATkOCVTNUGxJQBhCDnS5dKDQZkgDjjAAqSM6SsFJRKQA) 

There were a whole bunch of other cases that get addressed in #400 though

**Comment by czosel** [comment]
It actually does indent once you reach the line limit ([see here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQB0qaYAkAzgBYQDuAchDKmHAGoCGANgK5yYC8fmAcgCMAzADIx+QgEJUJAPpQObNtiJgOAJ00IYAZTiaAbgzgBKcZILEN23QeOmAdAHM4+lp6-efXwycYASQATbAs+HiliFjB6IxZ6aFd3BwC4ELD8C2AoyCgSGEx4At5MIQBufABfEAAaEAgAB0T85FBGzVRYAHVUYJgyZAAOAAZ6mBYAI17+waQAJnqSLpc2OABFDjo4ZHR2EjhxzRZUNhWAYQgAWyuWZBAoaB36yeOwAGsUxpiV5BhNLj1ABWJAAHgAhN6fDxXOAAGS6OyQezYB3q300B0090mUwAnmxoHUQAcrqg-gDDiAOAcACpTEi7fZUrpYmAABWOLluTNRVJ0AEcOKgdJyWNy7sjmejNBADt1jo17h04FijM8QCxtFR2VqEIyUCwjBA+sTghAwLy0ZqClaqRAODBGo75naqlUgA)).

My example above is indented deeply because i copied it out of some existing file including indentation.

**Comment by mgrip** [comment]
Ah got it, that makes sense - let me add a test to that PR to make sure the same happens in ours

**Comment by mgrip** [comment]
yup, all set 👍
