### ISSUE TITLE
Usage in non-js projects

### ISSUE THREAD

**Issue by emil-nasso** [prettier/plugin-php#1530]
We use prettier for some of our javascript projects and like the formatter and how opiniated it is.

We would like to start using it for our PHP projects too but most of our php-projects are plain PHP, no javascript. While building the projects, we can always solve this but when developing, we are looking for another solution.

Is there a way to use this project for pure php-projects while developing? We are mainly using vscode.

**Comment by evilebottnawi** [comment]
Install prettier globally with the plugin

**Comment by emil-nasso** [comment]
Ah, thanks for pointing me in the right direction. :) I installed it globally, added a document selector for `*.php` and enabled global modules in the extension settings. Thanks for pointing me in the right direction. :)
