### ISSUE TITLE
How to Install this plugin for PHP to vscode _WITHOUT_ Javascript-based npm or yarn?

### ISSUE THREAD

**Issue by starfishpatkhoo** [prettier/plugin-php#1537]
I am trying to move to VSCode.

I like Prettier, becuase it can also help me with SCSS, HTML, JS, YAML and even JSON config files. It works great and I have "editor.defaultFormatter": "esbenp.prettier-vscode", for all files. Format on save as well as ctrl-shift-p > format document is really nice. I'm still debating between tab space 4 or 8... Hmmm....

BUT: I am primarily a small-time nobody PHP developer. I don't use Node.JS or npm or yarn or .. other "hip" and "modern" tools, so yes, I'm really old fashioned and still use a horse and carriage to get to town. Please don't flame me for not being "hip" and "modern".

So it seems like I must install a whole bunch of Javascript tools (NodeJS, a 20+MB package which I don't use) to install a 20kb JS plugin into the folders of each and every non-Javascript project I have?

I've spent the last 3+ hours trying to find an answer, looking at the documentation for prettier in GitHub, VSCode Marketplace and here, like issues #1213 and #1530 ... As stated there also, probably just install prettier globally and not on a per project basis.

I've tried downloading the unpkg version - https://unpkg.com/@prettier/plugin-php/standalone.js - and putting it in the node_modules folder of the prettier plugin.. Even edited the package.json to try to get it to be recognised...

._.

Is there a Wiki or some instruction somewhere how to:
1. Download this plugin (the release of this plugin on GitHub is the entire uncompiled source code...)
2. Install this plugin to an already working global prettier installed in vscode from the VSCode marketplace

_**WITHOUT**_ using npm or yarn (as an old-school php developer needing a php-related plugin) ?

Yes, I know how to use GitHub - this is not a bug/issue report, but a plea for help - I'm tired, I'm frustrated, and I don't know where else to turn to. Thank you guys in advance.

**Comment by hackel** [comment]
Honestly, you should probably just not use this tool.  Node and npm are over 10 years old now—not exactly "hip and modern".  No one's going to "flame" you—you should use whatever is the right tool for the job—but refusing to install Node.js (which comes with npm) in order to run a *Node* project makes no sense.  Would you file a bug report on the Wordpress project asking how to use it without installing PHP?  But you claim you're already running prettier, which means you already have Node installed, so I don't understand what the issue is here.

Just bite the bullet and use npm or yarn or give up. `npm install --global @prettier/plugin-php`  There is no other way.

**Comment by starfishpatkhoo** [comment]
**Objective: I want to use Prettier and the Prettier-PHP Plugin in VSCode.**

(Disclaimer: I'm trying to switch to VSCode and I didn't even know of Prettier until I saw a blog post talking about the best extensions in 2020 for VSCode).

**Steps to Reproduce**

OK, well, I did not install Node.JS or NPM. I installed the portable .zip version of VScode (https://code.visualstudio.com/download). Then, in the marketplace, (on the VSCode Left Sidebar) I looked for Prettier and hit install. Easy Peasy.

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

Prettier is even tagged "PHP" on the page.

https://stackoverflow.com/questions/51000556/npm-command-not-found-in-visual-studio-code

So then I installed NPM from Microsoft - https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script thinking I can just Command Palette `>npm install --global @prettier/plugin-php` but no.. that's not a valid command. I tried https://marketplace.visualstudio.com/items?itemName=fknop.vscode-npm as well, no joy. I'm guessing these allow you run npm commands (like update dependency) on a NodeJS project etc that you are working on - *IF* you have NodeJS already installed?

This problem must be a common one because there is even an unofficial fork of Prettier that includes the PHP plugin with more than 10,000 installs.

https://marketplace.visualstudio.com/items?itemName=Karye.prettier-php

But it is unofficial, older and less frequently updated.

**Problem Description**

I'm not asking to stop using npm or yarn. I am on your side when people say "Must use Composer what??" ..

And yes, VSCode is itself a Javascript application. And Prettier is a Javascript plugin. But I am not looking to develop VSCode or Prettier, I am just a user (although I am technically trained). I don't need to install NodeJS to use/run VSCode or Prettier or Atom (or Electron-based WhatsApp Desktop for that matter) while I do need PHP to run WordPress (and they say so up front).

* WordPress User: Needs PHP
* WordPress Developer: Needs PHP
* Prettier User: Needs VSCode (which needs Windows, MacOS or Linux)
* Prettier Developer: Needs Node.JS

So it is different.

**Pull Request**

Maybe documentation somewhere needs to be stated on the VSCode marketplace that you must install NodeJS to install any of the plugins, or remove the PHP tag or (what I really want) some instruction how to add these plugins. Even if I did install Node.JS, do I have to go to the Prettier plugin folder in the user-data folder and run the npm command? Or else how does npm know where `--global` is? And can I uninistall NodeJS after? Sorry for out-of-scope NodeJS questions because.. I don't use NodeJS! \^_^/ Sigh...

BTW, click on "Q&A" on Prettier in the VSCode marketplace and they send you to GitHub Issues. So I had debated - post this question in the prettier-prettier project or prettier-plugin-php project - and I opted for the latter since I thought it was more specific. But maybe this is a broader Prettier issue and I posted in the wrong place - if so, apologies for the spam.

**Please Help _|-|o ?**

Anyway, all I'm asking is how to download and install this without npm or yarn? Yes, I am willing to edit config files by hand. I am willing to assume responsibility of manually updating it, etc etc. I didn't need npm or yarn to get to this point with either VSCode or Prettier. I just want to use a plugin that Prettier has. Can I grab the unpkg version and modify something somewhere?

But I am resigned to the fact that this issue will probably be closed "Will Not Fix" because it is technically not possible.

And you know, this is a really good piece of software. The developers did a great job. It's a useful tool that I can use every day. Can I not use it? Of course. I've not used it for many, many, many years. (PHP is more than a decade older than NodeJS, and I still remember when Zend was first released, LOL). But Prettier and Prettier-PHP is a useful and good software, and I want to use it. I really have tried to figure it out on my own.

``` ._. ```

**Comment by czosel** [comment]
Hi @starfishpatkhoo, I think it would be best if you post this question over at https://github.com/prettier/prettier-vscode, since this repository is not dealing with editor integrations.

**Comment by starfishpatkhoo** [comment]
Well noted. Thank you. I've done so. Much appreciated.
