### ISSUE TITLE
Chained method arguments split up unnecessarily

### ISSUE THREAD

**Issue by hackel** [prettier/plugin-php#1545]
**@prettier/plugin-php v0.14.3**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AjAEwAMANCDAIYBG5VteAFjYBXbFAAq3XHgBmHADZi22YgHN5UAIrD0MKPhgRhUNmGpgAakhVZ8IAOwA6ASDaGO8eWoDC6ALZ+HAAKABJBBkYmIFwQHADGUADKMACeGnZg2BAAtAyuINAAjsLw0EGxqoH4copRxGIQMOUclRzVCmIAvmxQFPAw6Cho8FjSoBzYMO213SDEYMJTeCAAPAD8ZmAAOpg7ACTFSCk7AARnJ9kAfGIacTAAShwA7gAUAORx6MIkLwBUAJQnCYnAAGn2+MBBLBOFA4egA+jJBoEYC8wdA4b14XCoSctiAAKQATWyBL82SYdHxgOBINhehBb3+p3OVxkEH872Kuig8LEHAgcWoUGwTJZZyuT2F0He8XBJHhlDe0L2cq+JAAkhRmZhzhdLlKkFB3nEMXoKNiYMqTm9LgBea3eAVcLB4PCYdCvf5XSYCmDIGQAWSwNBe3uuwi4wZI1GwLz2fhDsf+Or1V1UHOEYAAQil3vSoEyANw7ECdIA)

**Input:**
```php
<?php

$query
    ->selectRaw('count(*) as `count`, date_format(`created_at`, "%Y-%m-01") as `date`')
    ->from('quote_searches')
    ->where('account_id', $accountId)
    ->where('created_at', '>=', Carbon::now()->startOfMonth()->subMonths($months))
    ->groupBy('date');

```

**Output:**
```php
<?php

$query
    ->selectRaw('count(*) as `count`, date_format(`created_at`, "%Y-%m-01") as `date`')
    ->from('quote_searches')
    ->where('account_id', $accountId)
    ->where(
        'created_at',
        '>=',
        Carbon::now()
            ->startOfMonth()
            ->subMonths($months),
    )
    ->groupBy('date');

```

I'm specifically referring to the second `where` call.  Prettier leaves this alone, so I assume it must be caused by the php plugin.  It's behaving as if the print-width is much less.  (I use 120, but this even fits in 80.)

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAjgVzgJwJ4A6UABKcQHQDOcANnGDAEoCGA7gBQDkkms7AVAEpizSsQAGPWOIA0xACbN4AfQBmEHAFsl7STjhK485UtnECIAKQBNALSXNtgAwBGC8NETF8cZ0FEyClUcCE0uLAgVamYcMAALOEo-ALJyVgT9LmYwKRhlAEt5TjlUbNyASXl-ElT03DguMH1DYyVi4k4APgBedoBhGIAjaHIoCA5BKhgYmAB5VQBZaBg49knKTEGl2DjKdlRNZd3BasDyAHMQzAAHACE8Lm84PwBuIhAZEAhrmHzoSmQoBiIVYAAUYggAShmAA3CCFD4gQY4bIAazgMAAytdsvkoOdkDAcNhPnBNIMjPIjAAZZj4zDMc5wABiGm0MF++OQIGYmBgEERcRgmhoAHU4vl4JQcWA4JjIZL8jDJXhuWBKADPnjqDgYKCUedtMhVMwaNRPgArSgAD1uKLA6KxzE0cGpeLgxtN5pAVutmLx5zoAEVMJEPUgTWa4J8cTgddzBswKTREdccHiYKLCitkC4AExOGMhaiilHXblpxK4GEez4ReD675QnmUWxQOBGIyI-RYfL6fWMo0Rr3RkDUTT5QnE0eUAPB0PwKckkDTQZZ+Q5pAAFk+ROY+RoAb6oSHPJoKc+mGoABUk1DI96YdhylAqbBMU18j8AIKvzEwPA6E9KMAF8QKAA)
```sh
--arrow-parens avoid
--parser babel
--print-width 120
--single-quote
--tab-width 4
--trailing-comma all
```

**Input:**
```jsx
$query
    .selectRaw('count(*) as `count`, date_format(`created_at`, "%Y-%m-01") as `date`')
    .from('quote_searches')
    .where('account_id', $accountId)
    .where('created_at', '>=', Carbon.now().startOfMonth().subMonths($months))
    .groupBy('date');

```

**Output:**
```jsx
$query
    .selectRaw('count(*) as `count`, date_format(`created_at`, "%Y-%m-01") as `date`')
    .from('quote_searches')
    .where('account_id', $accountId)
    .where('created_at', '>=', Carbon.now().startOfMonth().subMonths($months))
    .groupBy('date');

```

**Comment by Eldair** [comment]
Same in latest version. Looks bad, especially in IF statements.

**Comment by czosel** [comment]
I totally agree. Potentially, we could check how Prettier for JS handles this and port some of the logic to the plugin.

**Comment by evilebottnawi** [comment]
Good idea

**Comment by arnoson** [comment]
Any news on this? Would be really great to only split chained methods if we're running out of space

**Comment by czosel** [comment]
Hi @arnoson, I agree it would be nice to get this fixed. I currently don’t have time to work on this it myself, but I’d do my best to help anyone who’d be interested in taking this on.

**Comment by slowspin59** [comment]
Also hoping for an update on this issue. We recently began using Prettier for our codebase, both our PHP and JS code. Successive chained method calls on the JS side get wrapped to one method call per line only if the full line exceeds the line length limit, but the same thing occurs on the PHP side with >2 chained method calls, regardless of how long the line is. It's had an adverse affect on our codebase. It would be great if the PHP behavior could be consistent with the JS behavior. Thanks for your consideration!
