### ISSUE TITLE
Where to put config?

### ISSUE THREAD

**Issue by strider72** [prettier/plugin-php#1563]
I have the following configuration, but can't figure out where to put it:

```
{
	"phpVersion": "7.4",
	"braceStyle": "1tbs",
	"singleQuote": true,
	"useTabs": true
}
```

Does this go somewhere in the NPM `package.json`?  The `.prettierrc.json` file?

(If it matters, I installed Prettier and this plugin via NPM command line, and I'm using them within PhpStorm. I did get it to format a PHP file, so the plugin is working.  I just don't know how to customize the settings.)

**Second (related) question**: How do I tell Prettier to use this plugin to format files with a *custom* extension?  I have some PHP template files that use a `.phtml` extension

**Comment by hackel** [comment]
Github issues are not the place for support requests.

You can configure it either way, it's up to you.  See https://prettier.io/docs/en/configuration.html
It already works just fine with .phtml files, which you could have found by simply searching this repo or just trying it first.

**Comment by strider72** [comment]
@hackel I did search the Prettier docs. The link you posted doesn't answer my question.

Funny about .phtml -- I was unaware it used to be a semi-standard.  I just made it up.  However, it would still be useful to know how to specify a custom file extension for PHP parsing. it doesn't work in the standard Prettier settings because the base script doesn't recognize PHP

**Comment by strider72** [comment]
It appears the answer is you set plugin options via `overrides`. No way I can find to set "php" as a custom parser.

Example:
```  
"prettier": {
  "useTabs": true,
  "overrides": [
    {
      "files": [
        "*.php",
        "*.phtml"
      ],
      "options": {
        "phpVersion": "7.4",
        "braceStyle": "1tbs",
        "embeddedLanguageFormatting": "off",
        "singleQuote": true
      }
    }
  ]
}
```

**Comment by strider72** [comment]
I've closed this, but it would still be **really** nice to give a full example in the documents!

**Comment by czosel** [comment]
Hi @strider72,

did you try the "parser" option? https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option

**Comment by strider72** [comment]
@czosel I did.

```
Value should be one of: "flow", "babel", "babel-flow", "typescript", "css", "less", "scss", "json", "json5", "json-stringify", "graphql", "markdown", "mdx", "vue", "yaml", "html", "angular", "lwc"
```

**Comment by czosel** [comment]
I just tried to reproduce the issue, and it works for me! I created a little repo that should show it: https://github.com/czosel/prettier-php-config-example/
