### ISSUE TITLE
How do I configure plugin-php inside package.json?

### ISSUE THREAD

**Issue by brunocassol** [prettier/plugin-php#1618]
Hi! I was able to specify prettier settings inside `package.json`. Is there a way to configure `prettier/plugin-php` in it too?

Thanks in advance!

![image](https://user-images.githubusercontent.com/203541/103445661-98855600-4c4d-11eb-821e-c404adbcf4c0.png)

**Comment by czosel** [comment]
Hi @brunocassol 

You should be able to specify options for the PHP plugin in the same `prettier` block. My test went as follows:
package.json
```
{
  "name": "prettier-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@prettier/plugin-php": "^0.16.1",
    "prettier": "^2.2.1"
  },
  "prettier": {
    "phpVersion": "5.3",
    "singleQuote": true
  }
}
```
test.php
```
<?php
$arr = ["foo", "bar"];
```
```
$ yarn prettier test.php 
yarn run v1.22.5
$ /tmp/prettier-test/node_modules/.bin/prettier test.php
<?php
$arr = array('foo', 'bar');
Done in 0.30s.
```

**Comment by brunocassol** [comment]
Awesome it works! Thanks @czosel
