### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by jscheid** [prettier/plugin-php#1631]
I must be missing something... why does this not work?
https://github.com/jscheid/prettier-php-test

```
➜  prettier-php-test git:(main) yarn test
yarn run v1.22.10
$ prettier sample.php
array_map(function($arg1,$arg2) use ( $var1, $var2 ) {
    return $arg1+$arg2/($var+$var2);
}, array("complex"=>"code","with"=>
    function() {return "inconsistent";}
,"formatting"=>"is", "hard" => "to", "maintain"=>true));
✨  Done in 0.45s.
```

Shouldn't this be printing the sample output in https://github.com/prettier/plugin-php#output ?

**Comment by alexander-akait** [comment]
You need to install plugin-php

**Comment by jscheid** [comment]
The sample repository that I've linked to does have `@prettier/plugin-php`, is that what you mean?

**Comment by jscheid** [comment]
Do I need to have php installed perhaps?

**Comment by jscheid** [comment]
I've added a Dockerfile.

```
➜  prettier-php-test git:(main) ✗ docker build .
Sending build context to Docker daemon  21.22MB
Step 1/4 : FROM node:12
 ---> f65e5434ee1c
Step 2/4 : ADD package.json yarn.lock sample.php ./
 ---> Using cache
 ---> dfdbf33607fa
Step 3/4 : RUN yarn
 ---> Using cache
 ---> 7871b2b3482b
Step 4/4 : RUN yarn test
 ---> Running in b4dde9798a8c
yarn run v1.22.5
$ prettier sample.php
array_map(function($arg1,$arg2) use ( $var1, $var2 ) {
    return $arg1+$arg2/($var+$var2);
}, array("complex"=>"code","with"=>
    function() {return "inconsistent";}
,"formatting"=>"is", "hard" => "to", "maintain"=>true));
Done in 0.43s.
Removing intermediate container b4dde9798a8c
 ---> 5756e96fdcbf
Successfully built 5756e96fdcbf
```

**Comment by czosel** [comment]
Just a guess: the command “prettier sample.php” is using your globally installed prettier, which doesn’t have the php plugin.
Try “npm install -g @prettier/plugin-php” or “yarn prettier sample.php” to use the local version.

**Comment by jscheid** [comment]
Thanks @czosel -- did you see the Dockerfile I added to the demo repository? There is only one version of Prettier in that docker container.

**Comment by jscheid** [comment]
By the way, I don't need to use this plugin, I'm just trying to write a test case to make sure that [my plugin](https://github.com/jscheid/prettier.el) works well with yours.

Can you see what changes would need to be made to the [Dockerfile](https://github.com/jscheid/prettier-php-test/blob/main/Dockerfile) to make things work?

Is it possible that it's a problem with your [sample input](https://github.com/prettier/plugin-php#input)?

**Comment by jscheid** [comment]
I've added a more explicit [test](https://github.com/jscheid/prettier-php-test/blob/main/test.js). Output is [here](https://gist.github.com/jscheid/37cb4d177a52bf246aba08b274ff1772) -- clearly this is loading your plugin correctly?

**Comment by jscheid** [comment]
File needs to start with `<?php\n`....

Perhaps your example input/output could be updated to show that.

**Comment by czosel** [comment]
Ah right, we've seen this issue a couple of times before. #1632 makes the README more explicit, thanks for the suggestion!
