### ISSUE TITLE
Uglify arguments output with closure

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#164]
Input:
```php
$foo->bar(
    $arg1,
    function ($arg2) use ($var1) {
        // body
    },
    $arg3
);
```
Output:
```php
$foo->bar($arg1, function ($arg2) use ($var1) {
    // body
}, $arg3);
```

I think we should always break lines if we have closure between

**Comment by mgrip** [comment]
Some [JS examples](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEB0AjAhgJwAoAdKAAgrIIHMBGAGlMrNQFcowYBLaMwgEhoAmAJRlgTZpQD00stggATAJ6SKAX0blKNAMykRAblKl0WPETUt2nHuQHCxE7VLKz5S1S7Kareg8ZQphg4BCTebBzcvA741KLiVszuCipWvt7CWsz+UEYmUGahlplxDFaRtjGCcQnOrhQpnukBBUUW4Tll2Tq1PRSV0fY18U5JMnKpXszqASD0IBAADkMAzsigBPgQAO4ACgQI6yi4AG4QXIrzILirMMiouAA2q3AL2Pi4YADWcDAAyksvlwoNRkDB8Kw3iBFBAwA9nq8FiDXvgYHtPtQALa4BEvaEAK1WAA8AEKfH5-f64LFwAAyILgeKRi1YMCWbKEzOhQPwqOQIDw2GUT2g1yW+BBMAA6pcYAALZAADgADAsJRBXtLPksBRK4KjTkyFvg4ABHVhcU0Y3DY3FIR74havLFccGQ6GrEHUJ5wACKrAg8G5CxguGwssUCuQQlDny4T29AGEIFicQKoNBjSBWK8ACrh46O17qdRAA) - I don't think we'd always want to break everything, but agree if there are other arguments on either side we should
