### ISSUE TITLE
Format On Save not working on VSCODE (Windows 10)

### ISSUE THREAD

**Issue by jbersamin-vitech** [prettier/plugin-php#1640]
I tried to search on close/open issues but no avail.

What is wrong with my settings? Please help. Thanks

**Prettier 2.2.1**

**PHP Plugin 0.16.1**

*package.json*
```sh
    "devDependencies": {
        "@prettier/plugin-php": "^0.16.1",
        "axios": "^0.21",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "prettier": "^2.2.1"
    }
```

**.prettierrc.json:**
```php
{
    "useTabs": true,
    "overrides": [
        {
            "files": ["*.p"],
            "options": {
                "parser": "php",
                "phpVersion": "7.4",
                "braceStyle": "1tbs",
                "embeddedLanguageFormatting": "off",
                "singleQuote": true
            }
        }
    ]
}

```

**My VS Code Settings:**

```php
    "editor.formatOnSave": false,
    "[php]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true
    },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
```

**Expected behavior:**

**Comment by nicoder** [comment]
hi @jbersamin-vitech ,

(I don't know much about this but) this line of your `.prettierrc.json` stood out to me:

`"files": ["*.p"],`

should it be `*.php` ?

(or maybe your php files have a `.p` extension)

**Comment by jbersamin-vitech** [comment]
@nicoder I tried to change it to .php and still not working. If I could just see any errors in the output inside the VSCODE. I could have fix this.
