### ISSUE TITLE
Broken: inline closure method access

### ISSUE THREAD

**Issue by Vovan-VE** [prettier/plugin-php#1675]
**@prettier/plugin-php v0.16.1**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtmNkx7AACACEDqAAPHUwKQ4BBLeAtg6eDuY4PGIOpQUwYjExP9DoAAUAEpHs8Hv9ntCgV8fn8DqCDpDoajngASGjwbCZAB8RAAbmwdAcALwHPjZADc4LR7RBeI4xAoomBmOo2KYBxueDwu32INBNKhT3aWzFmBA7SAA)

**Input:**
```php
<?php

class B extends A
{
    public function foo()
    {
        (function () {
            $this->private = 42;
        })->bindTo($this, A::class)();
    }
}

```

**Output:**
```php
<?php

class B extends A
{
    public function foo()
    {
        function () {
            $this->private = 42;
        }->bindTo($this, A::class)();
    }
}

```

https://3v4l.org/0M45m
```
Parse error: syntax error, unexpected token "->" in /in/0M45m on line 9
```

**Comment by czosel** [comment]
Released as v0.16.2 :tada:
