### ISSUE TITLE
Doesn't work in VSCode

### ISSUE THREAD

**Issue by uncleramsay** [prettier/plugin-php#1683]
Not really sure what I'm doing wrong. Here are the steps I'm taking:

- Install `Prettier - Code formatter` VSCode extension
- At root of project, run `yarn add -W --dev prettier @prettier/php` (this is in a monorepo project. I also tried installing in the underlying packages directly)
- Restart VSCode
- Navigate to php file
- Ctrl+Shift+P -> Format Document
- Get error message `There is no formatter for 'php' files installed`

Can anyone advise? Thank you!

**Comment by czosel** [comment]
The steps look reasonable to me - did you already open an issue at https://github.com/prettier/prettier-vscode?

**Comment by uncleramsay** [comment]
@czosel thanks for getting back to me. I hadn't posted there - was about to but then I realised my mistake.

I was installing `@prettier/php` instead of `@prettier/plugin-php` - it works with the latter!

Thanks for taking a look for me.

**Comment by czosel** [comment]
Ah sorry, I should have noticed that as well :see_no_evil: I'm glad you could resolve the issue :wink:
