### ISSUE TITLE
configuration to phpVersion 5.3, JavaScript file format not working on VSCODE

### ISSUE THREAD

**Issue by 53JIlLenWe11** [prettier/plugin-php#1694]
If it is configured to phpVersion5.3
Cannot format JavaScript file format.

Windows 10 ver1809
VSCode: 1.55.0
nodejs: v14.16.0
npm: 6.14.11
prettier@2.2.1
@prettier/plugin-php@0.16.2
eslint@7.23.0

.prettierrc
``` json
{
	"useTabs": true,
	"endOfLine": "auto",
	"singleQuote": true,
	"semi": true,
	"printWidth": 120,
	"trailingComma": "es5",
	"phpVersion":"5.3"
}
```

**Comment by czosel** [comment]
Hi @53JIlLenWe11 - i'm not sure if I understand the issue: Are saying that `phpVersion: 5.3` causes the formatting of JavaScript files to break? Can you post some more details on how to reproduce this?

**Comment by 53JIlLenWe11** [comment]
It did not reproduce on another PC.
There may be another cause.
Sorry, closing this one.
