### ISSUE TITLE
Long function declaration ugly

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#171]
Input:
```php
public function longLongAnotherFunction(string $foo, string $bar, int $baz): string 
{
    return 'foo';
}
```

Output:
```php
public function longLongAnotherFunction(
    string $foo,
    string $bar,
    int $baz
): string
{
    return 'foo';
}
```

Should be:
```php
public function longLongAnotherFunction(
    string $foo,
    string $bar,
    int $baz
): string {
    return 'foo';
}
```

**Comment by mgrip** [comment]
fwiw I started looking into this a while ago and I didn't have any luck - the real trick is adding a line before the opening brace if the function declaration doesn't break, and not adding one if it does
```php
public function shortFunction()
{

}

public function longFunction(
  $arg1,
  $arg2
) {

}
```

**Comment by evilebottnawi** [comment]
@vjeux can you help with this. We need logic as `line` only vice versa (i.e. `ifBreak(" ", hardline)`). How it is possible?

**Comment by vjeux** [comment]
You can put “\n” instead of hardline but I can’t guarantee that it’s not going to mess up the printer in some other ways...

**Comment by evilebottnawi** [comment]
@vjeux putting `\n` break indent :disappointed:

**Comment by evilebottnawi** [comment]
@vjeux how about we implement `invertLine` in `prettier` with versa vice line logic?

**Comment by vjeux** [comment]
I don’t know what that will mean for the algorithm as it violates one of the core invariant: if it doesn’t break, then make it break. I don’t understand the algorithm enough to know if it will actually work.

You should try it for sure but there’s a chance that you won’t be able to do it.

**Comment by evilebottnawi** [comment]
@vjeux i will try to implement and send PR in `prettier`
