### ISSUE TITLE
Editor integration for Intellij based platforms

### ISSUE THREAD

**Issue by Stevemoretz** [prettier/plugin-php#1717]
I noticed in Readme,there were a lot of editors integration tutorials but Intellij is missing, any particular reason?

**Comment by czosel** [comment]
I think this just because no one contributed docs for this yet - if you have the plugin running in IntelliJ / phpStorm, please open a PR 😊
See also https://github.com/prettier/plugin-php/issues/452

**Comment by Stevemoretz** [comment]
Thanks no still haven't got it working
