### ISSUE TITLE
How to Setup in PHPStrom

### ISSUE THREAD

**Issue by Surya16Go** [prettier/plugin-php#1727]
I have followed the instructions from [https://www.jetbrains.com/help/phpstorm/prettier.html](url). 
But it says if 
> Prettier: File index.php has unsupported type

**Comment by cseufert** [comment]
Make sure you have both prettier and the prettier php plugin installed:
```json
{ "dependancies": {
    "@prettier/plugin-php": "^0.16.1",
    "prettier": "^2.1",
}}
```
You will need to update the Run for files glob to something like this:
![Screenshot from 2021-06-02 15-00-10](https://user-images.githubusercontent.com/1734519/120426378-535b8080-c3b3-11eb-9db0-73204b8b7cf9.png)

**Comment by czosel** [comment]
@Surya16Go did this work for you?

@cseufert thanks for sharing this! I think it would be a valuable addition to the README as well, do you agree?
