### ISSUE TITLE
impossible detect two php tags

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#175]
```php
<div></div>
<?php echo 'test'; ?>
<?php echo 'test'; ?>
<div></div>
```

**Comment by mgrip** [comment]
@evilebottnawi this is fixed right?

**Comment by evilebottnawi** [comment]
@mgrip no

**Comment by mgrip** [comment]
ok so just checked, and this works, but you loose the 2nd php tag

```php
<div></div>
<?php
echo 'test';
echo 'test';
<div></div>
```
Maybe this is just personal preference but I think the way we currently output is fine?

**Comment by evilebottnawi** [comment]
@mgrip it is other discussion, by default we don't change ast

**Comment by virgofx** [comment]
Just a heads up -- 
```php
<div></div>
<?php echo 'test'; ?>
<?php echo 'test'; ?>
<div></div>
```
does not equal 


```php
<div></div>
<?php
echo 'test';
echo 'test';
?>
<div></div>
```

There's a new line character that's now missing. That's important for `.phtml` that frequently interweaves PHP blocks. Not sure by last comment if the second block is the resulting code; however, it should not. It should keep all php tags and corresponding spacing outside the php blocks.

**Comment by mgrip** [comment]
Unfortunately the parser treats the 2 cases exactly the same - ideally it would pick up the case with 2 sets of tags as having an extra `inline` node in between the two echo nodes. _But_ the parent program node does have the source prop - we could theoretically check this to see if there to find the extra tags. So definitely possible, i can try to take a look today or monday.

**Comment by evilebottnawi** [comment]
@mgrip what about looks in source code?

**Comment by mgrip** [comment]
Yup! That's probably how we'll have to do it - but we'll have to look in the parent `program` node - the tags don't exist in the source prop for either of the echo nodes

![image](https://user-images.githubusercontent.com/13454680/41783416-c98d9eea-760a-11e8-9d63-38f0919111b2.png)

**Comment by mgrip** [comment]
Or I guess we could maybe use originalText, similar to https://github.com/prettier/plugin-php/blob/c6eae45624149e52dddf7fb31ecb66e9e74ffb0d/src/printer.js#L100 ?

**Comment by evilebottnawi** [comment]
@mgrip maybe need investigate

**Comment by evilebottnawi** [comment]
Fixed
