### ISSUE TITLE
PHP8: Trailing comma in method signature

### ISSUE THREAD

**Issue by markkirchner** [prettier/plugin-php#1759]
**Prettier 2.3.1**

**PHP Plugin 0.17.1**

**Input:**

```php
class T
{
    public function __construct(
        string $t1,
        string $t2,
        string $t3,
        string $t4,
        string $t5,
    ) {
    }
}
```

**Expected:**
Valid PHP 8 code; file should be formatted.

**Result:**

```
Parse Error : syntax error, unexpected ')', expecting T_VARIABLE on line 10
   8 |         string $t4,
   9 |         string $t5,
> 10 |     ) {
     |    ^
  11 |     }
  12 | }
  13 |
```

**Comment by Richard87** [comment]
I have the exact same error, watching this :)

**Comment by cseufert** [comment]
@czosel Can you look at merging the parser changes?

Also should prettier always leave a trailing comma on multi-line function definitions when set to PHP >= 8.0?

**Comment by markkirchner** [comment]
> Also should prettier always leave a trailing comma on multi-line function definitions when set to PHP >= 8.0?

Maybe that behaviour should depend on the (already existing) `--trailing-comma-php` switch as well?

**Comment by cseufert** [comment]
That makes sense, I'll put together a pr for it

**Comment by czosel** [comment]
This has just been release with v0.17.2 :tada:
