### ISSUE TITLE
PHP8: catch block without variable declaration

### ISSUE THREAD

**Issue by markkirchner** [prettier/plugin-php#1760]
**Prettier 2.3.1**

**PHP Plugin 0.17.1**

**Input:**

```php
try {
    // Something
} catch (\Exception) {
    // Nothing
}
```

**Expected:**
Valid PHP 8 code; file should be formatted.

**Result:**

```
Parse Error : syntax error, unexpected ')' on line 13
  11 | try {
  12 |     // Something
> 13 | } catch (\Exception) {
     |                   ^
  14 |     // Nothing
  15 | }
```

**Comment by czosel** [comment]
Hi @markkirchner, thanks for the bug report! As soon as #1763 has been reviewed, we'll make  a new release with the bugfix.

**Comment by czosel** [comment]
This has just been release with v0.17.2 :tada:
