### ISSUE TITLE
Configuration for Single-Quoted Strings

### ISSUE THREAD

**Issue by bytreakz** [prettier/plugin-php#1782]
Hey, I'm new into programming and I dont know where I can find the configurations for the php plugin.

If I set singleQuote in prettier to true nothing happens and everything is still with doubleQuotes.

Thanks!
TREAKZ

**Comment by cseufert** [comment]
YOu can simple add a prettier section to your package.json that looks something like this:

```json
{
  ...
  "prettier": {
    "phpVersion": "8.0",
    "singleQuote": true,
    "tabWidth": 2,
    "trailingComma": "all"
  }
}
```

You also need to configure your IDE to run prettier to reformat your code, or call it on the command line.

**Comment by cseufert** [comment]
@bytreakz I am going to close this, if you are still having issues, feel free to open a new issue.
