### ISSUE TITLE
PHP8: Trailing comma in closure use-block

### ISSUE THREAD

**Issue by justim** [prettier/plugin-php#1795]
This change from #1769 also adds a comma after "parameters" in a use block for a closure — which it should, but the resulting code can not be parsed again.

Environment:

**Prettier 2.3.2** _(latest as of writing)_
**PHP Plugin 0.17.2** _(latest as of writing)_

Input:

```php
<?php

$test = function (SomeClass $one, SomeOtherClass $two, AndAnotherOne $three)
  use ($one, $two, $three, $four, $five, $six, $seven, $eight, $nine, $ten, $eleven)
{
}
```

Output:

```php
<?php

$test = function (
    SomeClass $one,
    SomeOtherClass $two,
    AndAnotherOne $three,
) use (
    $one,
    $two,
    $three,
    $four,
    $five,
    $six,
    $seven,
    $eight,
    $nine,
    $ten,
    $eleven,
) {};
```

And using the output as input again give the following message:

```
Parse Error : syntax error, unexpected ')', expecting T_VARIABLE on line 19

  17 |     $ten,
  18 |     $eleven,
> 19 | ) {};
  20 |
```

See Prettier playgrounds: [before](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCDoA6BiBYwIbeLJUBhdAFtvbAAoAEv74zoKGIBwuAMZQAMowAJ5q1mDYEAC0AEyOINAAjoLw0P4uyn56cgogxCIQMKVs5WyVBgC+LFAU8DDoKGjwWJKgbNgwrSIdNZhgguN4IAA8APzGYAA6mJsAJDpjAAQAvPtSgpjRGJj7ABRxPlAesqPY+9tYhvt33lDINEiPz1eMAA7ugmPsAIKYChQ7TUJDITBQIHUaBQACUm32+2EyOubyR4N2oKJNDRRKk6EEEAp8AAbh9tkoAB5EkQMzBEqDwZTUGBEzDERk6TmvKBqDmYzDATZtEBtIA) and [after](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCDoA6BiBYwIbeLJUBhdAFtvbAAoAEv74zoKGIBwuAMZQAMowAJ5q1mDYEAC0AEyOINAAjoLw0P4uyn56cgogxCIQMKVs5WyVBgC+LFAU8DDoKGjwWJKgbNgwrSIdNZhgguN4IAA8APzGYAA6mJsAJDpjAAQAvPtSgpjRGJj7ABSb+-f7cT5QHrKj2PvbWIZ3D0-eUGQNCQr3enxgAHd0ExfvcAIKYCgI7TUJDITBQcHUaA-TAASn2wkxtyuDy+GJhpPuuyhlIeWJxdLJUnQgggTOpUngADdcfTtkoAB4cz4iXmYEXbKDwZTUGCSzDEPlknQS2GfKBqcWUgnANoAbk2IDaQA).

Is this a quick fix? Or do you want me to look into it?

**Comment by alexander-akait** [comment]
We need to fix it here https://github.com/glayzzle/php-parser

**Comment by justim** [comment]
I created a PR for support in the parser: https://github.com/glayzzle/php-parser/pull/776
