### ISSUE TITLE
@prettier/plugin-php not found in the registry

### ISSUE THREAD

**Issue by lgraziani2712** [prettier/plugin-php#18]
Right now, the name of the npm lib is `@prettier/php`.

Thank you for your work!

**Comment by azz** [comment]
Yeah I haven't published it yet since it's under active development. I'll publish the latest version to the new name soon.

**Comment by czosel** [comment]
@azz Maybe it would be a good time to publish a first version? Then we could close #24 and the README would not be misleading anymore. I think the big `WORK IN PROGRESS` note in the README is clear enough that users don't expect production quality yet 😄

**Comment by andreiglingeanu** [comment]
That is a great idea @czosel, would love to try the prettifier in my day-to-day work. I believe this will actually just speed things up, more people would instantly be able to provide feedback

**Comment by azz** [comment]
Just published master as `@prettier/plugin-php` and renamed the repo to `prettier/plugin-php` for consistency.
