### ISSUE TITLE
Alpha release?

### ISSUE THREAD

**Issue by mgrip** [prettier/plugin-php#181]
https://github.com/prettier/plugin-php/issues/174#issuecomment-371190371

Wanted to start a discussion on where people think the quality of this plugin is currently, and plans for rolling out more widely.

For myself I've been running `--debug-check` on a codebase of ~1000 php files, and as of this morning am not getting any breaking errors 🎉 

Do people think its time to start publishing this as an alpha/beta release to encourage more people to start using and finding edge cases? I'm guessing that would mostly just entail bumping our package version to `0.1.0` and updating our README.md + documentation

**Comment by czosel** [comment]
I just tried the same with my codebase from work, and for me #112 seems to be an issue at several places (can't quite tell yet if that is the only problem). I'd suggest not doing a formal release before we've verified that we don't have breaking AST changes for a couple of larger codebases (might be interesting to try some larger open source projects). 

Of course I'm always in favor of encouraging people to try prettier for php on their projects and report back issues 😄 We just have to careful not to give the impression that the plugin is ready to be used, because then people might loose trust when we break their code (https://github.com/prettier/prettier/pull/3521#issuecomment-352594165).

**Comment by evilebottnawi** [comment]
In end of month i think we can release alpha :+1:

**Comment by evilebottnawi** [comment]
I think we will be the first of the official plugins :1st_place_medal:

**Comment by mgrip** [comment]
I think several of the largest remaining issues are solved with https://github.com/prettier/plugin-php/pull/217 (#190, #191, #173). Seems to me like getting that PR over the line will be the majority of what we need to get this to `v0.1.0`

**Comment by aboyton** [comment]
I'm guessing that if I run `--debug-check` and there's a bug with the AST generation itself then this won't detect it? I'm guessing this isn't particularly likely but could happen.

I'm very happy to help with testing on the reasonably large PHP codebase that I have at work. Sadly I got stuck on my first file (see #29, #252, #253, #254) but I'm really exited by this.

**Comment by mgrip** [comment]
I _believe_ all of the high priority issues mentioned above have now been fixed

**Comment by evilebottnawi** [comment]
We have big problem with mixed contents, we should fix it and we can alpha release. Try to run plugin on any WordPress theme repo

**Comment by mgrip** [comment]
@evilebottnawi do we already have an open issue for that? Currently the only open issue we have labeled as high priority is https://github.com/prettier/plugin-php/issues/267

**Comment by czosel** [comment]
@evilebottnawi You mean PHP embedded in HTML? To me, something that only works on `.php` files without mixed content would also be a very valuable starting point. I haven't looked at the HTML printer yet, but I could imagine that proper support for PHP in HTML would require a pretty solid foundation on the HTML side.

**Comment by aboyton** [comment]
As I mentioned before, I’m happy to give this a go on more code before an alpha if you’d like over the next 3 days (completely up to you obviously, I don’t want to delay you unnecessarily). So far I’ve only tested Prettier on a single PHP file and all the issues I’ve reported  were from that (which I’m unsure what that says about my PHP code).

**Comment by aboyton** [comment]
The other thing you could consider if finding a couple of big open source PHP code bases and running Prettier over them. That worked well for the JavaScript version IIRC.

**Comment by czosel** [comment]
@aboyton Testing and reporting issues is always appreciated and will speed us up instead of slowing us down! :wink: 
I think it's really important that we're confident about not breaking any code before we do our first release.

**Comment by mgrip** [comment]
@vjeux @azz I think we're getting close to fixing the last of any breaking issues. When we get to the point that we think this is good to move out the development release (hopefully within a week?), what work do you guys think would be involved in releasing this as an alpha/beta? Just bumping the npm version? I think @azz is the owner of the module and might have to do that

**Comment by vjeux** [comment]
Let me know what your npm names are and I can add you to @prettier/prettier-php. I'm not really sure why prettier-php has been deprecated (and I don't have access).

I think that publishing a new version is what is needed technically. I would recommend making a blog post / release notes about it so that we can tweet about it from the prettier account to get visibility.

**Comment by ichiriac** [comment]
Hi guys, congrats for the amazing job done !

As the final 3.0 is not ready yet, I could also make a pre-release of php-parser (3.0.0-pre1) that includes major bug fixes - do you see any blocking issue that I could prioritize ?

**Comment by evilebottnawi** [comment]
@ichiriac Thanks for work on `php` parser, only one strange error https://github.com/prettier/plugin-php/issues/313, maybe parser problem

**Comment by czosel** [comment]
@vjeux shouldn't it be `@prettier/plugin-php` for consistency? I'm also not sure about the naming conventions, @azz might now more. Also:
* my npm handle is `czosel`
* I could draft a blog post on the weekend!

**Comment by evilebottnawi** [comment]
I agree we should be `@prettier/plugin-php` for official consistently naming

**Comment by vjeux** [comment]
Okay, I have no idea how I can add you in the scoped module :x

Trying to add you from here https://www.npmjs.com/package/@prettier/plugin-php/access gives me this error message:

![image](https://user-images.githubusercontent.com/197597/38261409-f51088be-371e-11e8-80cf-0a81b5e2ebfb.png)

Trying from the command line gives me a similar error:

```js
npm team ls @prettier/plugin-php
npm ERR! code E404
npm ERR! 404 Not Found : -/org/%40prettier%2Fplugin-php/team
```

@azz do you know what's going on?

**Comment by azz** [comment]
Looks like the npm backend is having a bad time.

![image](https://user-images.githubusercontent.com/1297597/38291316-7a25fe86-3822-11e8-9565-9c94b9e312df.png)

![image](https://user-images.githubusercontent.com/1297597/38291324-837c9cce-3822-11e8-8e1d-019b7f8e416b.png)

**Comment by azz** [comment]
Ok got it sorted:

* Created a team called `php` in the `prettier` org.
* Added the `@prettier/plugin-php` package to the `php` team.
* Added @czosel and @mgrip as members of the `prettier` org and the `php` team.

You both should have publish access for this package now.

**Comment by czosel** [comment]
Looks like it's working - thanks @azz!

**Comment by czosel** [comment]
For the blog post I'd really like to include some instructions on how to get this to run in an editor. I've looked both at prettier-vscode (https://github.com/prettier/prettier-vscode/issues/395) and at vim prettier (https://github.com/prettier/vim-prettier/issues/119), but both don't seem to work with plugins yet. Has anyone of you had success with an editor already? @mgrip @evilebottnawi

**Comment by evilebottnawi** [comment]
@czosel i use `intellij idea`, he is support prettier, also have external tool to support any tools

**Comment by evilebottnawi** [comment]
@czosel @mgrip before alpha release we should solve https://github.com/prettier/plugin-php/pull/156, feel free to finish this PR and release alpha

**Comment by czosel** [comment]
@evilebottnawi does the PHP plugin work in IntelliJ already?

**Comment by evilebottnawi** [comment]
@czosel yes, just install prettier and plugin-php and all works fine

**Comment by tuananh** [comment]
Thank you for all the hard works <3

**Comment by czosel** [comment]
@evilebottnawi Wow, pretty cool!

About the peer dependency: Is it really important that this lands before releasing? I don't really see why. 
We should, however, update the install command in the README to just `yarn add --dev prettier/plugin-php` if we decide to release it without making prettier a peer dependency, right?

**Comment by evilebottnawi** [comment]
@czosel have two version prettier is very bad, also if you don't use > npm@4 your can got error because peer deps can be on top in node_modules, also it is increase node_modules size, because prettier have pinned deps and out version prettier have other pinned deps.

**Comment by czosel** [comment]
@evilebottnawi Alright - please see my comment in #156.

**Comment by mgrip** [comment]
Deployed!
