### ISSUE TITLE
Massage comments

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#190]
Running comments through `--debug-check` currently fails. Example Input:
```php
/*
 * This file is part of Composer.
 *
 * (c) Nils Adermann <naderman@naderman.de>
 *     Jordi Boggiano <j.boggiano@seld.be>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Composer\Autoload;
```

```diff
[error] ../ClassLoader.php: prettier(input) !== prettier(prettier(input))
[error] Index: 
[error] ===================================================================
[error] --- 
[error] +++ 
[error] @@ -1,10 +1,12 @@
[error]  <?php
[error] -/** This file is part of Composer.
[error] +/**
[error] + * This file is part of Composer.
[error]   *
[error]   * (c) Nils Adermann <naderman@naderman.de>
[error] - *     Jordi Boggiano <j.boggiano@seld.be>
[error] + * Jordi Boggiano <j.boggiano@seld.be>
[error]   *
[error]   * For the full copyright and license information, please view the LICENSE
[error] - * file that was distributed with this source code. */
[error] + * file that was distributed with this source code.
[error] + */
[error]  
[error]  namespace Composer\Autoload;
[error]
```

In this particular example there seem to be two issues:

* the added extra lines at the begging and end should be massaged away
* the removed indent in `Jordi Boggiano <j.boggiano@seld.be>` is unwanted (right?)

PS: I think this is the last kind of breaking AST change in my codebase! :tada:

**Comment by mgrip** [comment]
will be fixed with https://github.com/prettier/plugin-php/pull/217

**Comment by andreiglingeanu** [comment]
Just stumbled on the fact that the parser removes indentation from my comments, which I very carefully wrote, for some detailed illustration of a difficult concept. I think it would be saner to not touch the comments & perform such destructive changes to them.

**Comment by evilebottnawi** [comment]
@andreiglingeanu it is bug, already fixed in master branch in `parser`

**Comment by andreiglingeanu** [comment]
Actually it is not fixed in `master`, but #217 does fix it. But, #217 introduces another comment-related breaking change.

**Comment by evilebottnawi** [comment]
@andreiglingeanu in master in `parser` (here https://github.com/glayzzle/php-parser) :smile: Yep PR will fix this, near future I'll finish it

**Comment by andreiglingeanu** [comment]
Oh, got it :) Thanks for the awesome work!

**Comment by mgrip** [comment]
Believe this should be fixed now - if there are more issues related to ast cleaning when running `--debug-check` feel free to reopen this, otherwise for anything new please open a new issue! 🙏
