### ISSUE TITLE
Promoted arguments with interrogation mark throw error

### ISSUE THREAD

**Issue by sollidsnake** [prettier/plugin-php#1924]
**@prettier/plugin-php v0.18.0**

**Input:**
```php
<?php

class A
{
    public function __construct(protected ?string $a = null)
    {
    }
}

```

**Output:**
```
prettier errors:
[warn] Ignored unknown option --stdin.
[error] test.php: SyntaxError: Parse Error : syntax error, unexpected '?', expecting T_VARIABLE on line 5
[error]   3 | class A
[error]   4 | {
[error] > 5 |     public function __construct(protected ?string $a = null)
[error]     |                                          ^
[error]   6 |     {
[error]   7 |     }
[error]   8 | }

```

**Expected behaviour:**
No error thrown. That's valid PHP code.

**Comment by czosel** [comment]
I'm not exactly sure what seems to have fixed this, but I can't reproduce this in the current release (see [playground example](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCDoA6AIwgWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDCICM7azDBBCbwQAB4AfmMwAB1MbZjZMewAAgBBbeBtw8vD+Y4PGMOpQUwYjExDgH13mOHwl4AKSDaKAvbqHVbjCAqQ4AEjYhwAvIdMIJZLIAJQXK7nN5XdrbdogdpAA)).

**Comment by sollidsnake** [comment]
You're right, I also can't reproduce it anymore with the latest version. I'm closing this issue. Thanks.
