### ISSUE TITLE
0.18.3 - Defining attribute classes with bitmask definition fails with Bad terminal sequence "|" at line 8

### ISSUE THREAD

**Issue by AndreasA** [prettier/plugin-php#1943]
**Prettier 2.5.1**

**PHP Plugin 0.18.3**

**Input:**

```php
<?php declare(strict_types=1);

namespace App;

#[\Attribute(Attribute::TARGET_PROPERTY | Attribute::TARGET_METHOD | Attribute::IS_REPEATABLE)]
class Test
{
}
```

**Output:**

```shell
src/Test.php: Error: Bad terminal sequence "|" at line 3 (offset 73)
```

**Expected behavior:**
No error.

Though I think the issue is actually related to the php parser: 
https://github.com/glayzzle/php-parser 
https://github.com/glayzzle/php-parser/issues/486
https://github.com/glayzzle/php-parser/issues/654

**Comment by czosel** [comment]
Fixed in `v0.18.5` :tada:
