### ISSUE TITLE
PHP 8.1 - Support for nested attributes

### ISSUE THREAD

**Issue by Alvaro948** [prettier/plugin-php#1970]
**@prettier/plugin-php v0.18.4**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtmNkx7AACUShxg+Atg8uDgGIAbWQAQQ2NgHFYAAoLq++wNho8A4AcgA9GwwPBgcILICmF9vpdoNgwMMTgDbnD4d9MFAAO4HR7PABKJ2ROCg70RpJEAOyDGYBwoJxiEHggywAMBD2QAGlAQBKWGYTGY7F4gkbYlIlEUkkogF8BgARiYDKZLLZmA5ADltAc5LJ0DjuvzBcKDgBdDF8y1Cq5zDgeGIHKSCTAxDBCqEQbDvPlnA7AgBUBzsoYOgeBB3aW3aIHaQA)

**Input:**
```php
<?php

class Test {
    #[OA\Get(
        path: '/api/users',
        responses: [
            new OA\Response(response: 200, description: 'AOK'),
            new OA\Response(response: 401, description: 'Not allowed'),
        ]
    )]
    public function users() { /* ... */ }
}
```

**Output:**
```php
Parse Error : syntax error, unexpected 'OA\Resp...' (T_STRING), expecting ']' on line 7

   5 |         path: '/api/users',
   6 |         responses: [
>  7 |             new OA\Response(response: 200, description: 'AOK'),
     |                ^
   8 |             new OA\Response(response: 401, description: 'Not allowed'),
   9 |         ]
  10 |     )]
```

**Comment by czosel** [comment]
Fixed in `v0.18.5` :tada:
