### ISSUE TITLE
Configuration setting for exclamation mark in IF statement

### ISSUE THREAD

**Issue by JustinByrne** [prettier/plugin-php#2004]
**@prettier/plugin-php v0.18.7**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtgBIpdHQAAgBeQ-CoAG4trfgpQ4AKAEJDvYOASkPgLcPDqBjqI4bED7I7wbCHfQiIFXTDtEDtIA)

**Input:**
```php
<?php

$foo = true;

if (! $foo) {
  echo "foo is false";
}
```

**Output:**
```php
<?php

$foo = true;

if (!$foo) {
    echo "foo is false";
}

```

Is there a configuration setting I can add so that the exclamation mark can have a space between it and the next thing in the if statement?

**Comment by czosel** [comment]
Hi @JustinByrne
There is no such config option. Prettier is an opinionated code formatter which tries to stick to a minimal number of options, so I don't think we'll add an option for this. See https://prettier.io/docs/en/option-philosophy.html for more on this.

**Comment by JustinByrne** [comment]
Thank you for your reply @czosel I am developing a package at the moment, and as part of my GitHub actions I run php-cs-fixer and it and this plugin love changing the position of the ! I will look at my cs config to see if I can change anything there. Again thank you, happy for this issue to be closed.

**Comment by czosel** [comment]
Good idea - several people using this plugin also use php-cs-fixer to apply custom formatting changes :+1:
