### ISSUE TITLE
Syntax error when adding a type to a property using global namespace backslash

### ISSUE THREAD

**Issue by lmichelin** [prettier/plugin-php#2018]
**@prettier/plugin-php v0.18.8**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCDoA6AIwgWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtlzcYAAIAWSTRV16t4C396-2iADc2HX2NjYARR7F4Hyh9gBIY6AfCgAQRgAG4tu0tiB2kA)

**Input:**
```php
<?php

trait MyTrait
{
    private \DateTime $createdAt;
}

```

**Output:**
```php
Parse Error : syntax error, unexpected '\DateTime' (T_NAME_FULLY_QUALIFIED) on line 5

  3 | trait MyTrait
  4 | {
> 5 |     private \DateTime $createdAt;
    |            ^
  6 | }
  7 |
```

**Comment by ccchapman** [comment]
Can no longer reproduce in v0.18.9.
