### ISSUE TITLE
Breaking change: removes braces inside double quotes

### ISSUE THREAD

**Issue by cmancone** [prettier/plugin-php#210]
Input:
```php
<?php
class test {
    public function test_method() {
        $customer = (object) [ 'name' => 'Bob' ];
        $job = (object) [ 'customer' => $customer ];

        return "The customer for that job, {$job->customer->name}.";
    }
}
```
Output
```php
<?php
class test
{
    public function test_method()
    {
        $customer = (object) ['name' => 'Bob'];
        $job = (object) ['customer' => $customer];

        return "The customer for that job, $job->customer->name.";
    }
}
```
Expected output:
```php
<?php
class test
{
    public function test_method()
    {
        $customer = (object) ['name' => 'Bob'];
        $job = (object) ['customer' => $customer];

        return "The customer for that job, {$job->customer->name}.";
    }
}
```

**Comment by cmancone** [comment]
Just checked this against the latest code base (I didn't realize I was behind) and it is still an issue.

**Comment by vjeux** [comment]
Semi related but on the pretty we add the `high-pri` label for anything that would either cause a syntax error or worse, a different behavior. I would recommend doing something similar, this way it's easy to look at the issues (open and closed) and find out all the things that are/were breaking.

**Comment by czosel** [comment]
Good idea - i created and added the `high-pri` label!

**Comment by mgrip** [comment]
@cmancone can you check this again against the most recent version of master? I believe it should have been fixed with #251

**Comment by cmancone** [comment]
@mgrip I should be able to later today or tomorrow

**Comment by cmancone** [comment]
@mgrip I can confirm that with the latest updates this is now working
