### ISSUE TITLE
Strings ending in backslash

### ISSUE THREAD

**Issue by cmancone** [prettier/plugin-php#213]
I sometimes build class names from strings and variables, which ends up looking something like this:

Input:

```php
<?php
$class = 'models\tasks\repeaters\\' . $base_class;
```
Output:
```php
<?php
epeaters\' . $base_class;sks
```
Expected Output:
```php
<?php
$class = 'models\tasks\repeaters\\' . $base_class;
```

**Comment by mgrip** [comment]
@cmancone can you make sure you've pulled latest? I think this should have been fixed in https://github.com/prettier/plugin-php/pull/180

**Comment by cmancone** [comment]
You're right, it is fixed.  I didn't realize I was behind.  I'll recheck the other issues I just submitted.  Thanks!
