### ISSUE TITLE
Over zealous line splitting?

### ISSUE THREAD

**Issue by cmancone** [prettier/plugin-php#214]
Feel free to close if this is not considered a bug (and yes, this code doesn't actually work as is, I just grabbed out the line that caused trouble without surrounding context):

Input:
```php
<?php
namespace models\core;

class field extends \models\base
{
    protected function pre_save( $input, $fields ) {
        $input['configs'] = json_encode( array_merge( $configs, $field_type->process_field_config_from_user( $input['definition'] ) ) );
        unset( $input['definition'] );
    }
}
```
Output:
```php
<?php
namespace models\core;

class field extends \models\base
{
    protected function pre_save($input, $fields)
    {
        $input[
            'configs'
        ] = json_encode(
            array_merge(
                $configs,
                $field_type->process_field_config_from_user(
                    $input['definition']
                )
            )
        );
        unset($input['definition']);
    }
}
```
Expected output:
```php
<?php
namespace models\core;

class field extends \models\base
{
    protected function pre_save($input, $fields)
    {
        $input['configs'] = json_encode(
            array_merge(
                $configs,
                $field_type->process_field_config_from_user(
                    $input['definition']
                )
            )
        );
        unset($input['definition']);
    }
}
```
There are obviously a lot of ways a long line like this could be split up, and I'm definitely okay with this being opinionated and accepting however it decides to split it.  However, the part that stuck out to me was this part:

```php
$input[
            'configs'
        ] = json_encode(
```
Namely, `$input['configs']` seems like a strange thing to split up.

**Comment by evilebottnawi** [comment]
Not a bug, just more pretty output :+1:

**Comment by czosel** [comment]
I agree this doesn't look great. Hard to tell how difficult it is to fix this concrete example, we have to analyze it.

**Comment by evilebottnawi** [comment]
@cmancone btw we will fix it before release, priority on bugs which break code or remove something :+1:

**Comment by cmancone** [comment]
@evilebottnawi No problem: this isn't even on my list of concerns.  I just mentioned it because I noticed it.  I'm very okay with the concept of "Our coding standards are whatever the prettier outputs".  This one might be a little weird, but it wouldn't stop me from using this at all.

**Comment by mgrip** [comment]
added tests with #401 to confirm this is fixed
