### ISSUE TITLE
ES6 refactoring

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#218]
We won't do a stable release of this plugin before the EOL of node 4.x (2018-04-30), and our CI already ignores node 4 today. It would be nice to bring some more ES6 goodness into our codebase, right?

We could start by adding some more ESlint rules that throw warning, and gradually refactor the codebase. Let me know what you think! :smile:

**Comment by evilebottnawi** [comment]
:+1:

**Comment by mgrip** [comment]
@czosel definitely agree - if you have an idea of what rules you think would be good to add, definitely  list them here!

**Comment by czosel** [comment]
After quickly reading https://eslint.org/docs/rules/#ecmascript-6, i could imagine starting with

https://eslint.org/docs/rules/object-shorthand
https://eslint.org/docs/rules/prefer-destructuring
https://eslint.org/docs/rules/prefer-template
https://eslint.org/docs/rules/sort-imports (maybe?)

Several optimizations are probably not covered by some ESlint rule yet. I guess it would make sense to just start somewhere and encourage the usage of ES6 in general.

**Comment by evilebottnawi** [comment]
`sort` takes time, than gives new opportunities and advantages
