### ISSUE TITLE
Plugin detection issue with prettier v3

### ISSUE THREAD

**Issue by mermshaus** [prettier/plugin-php#2215]
Hi,

thanks for the prettier v3 update from yesterday!

I tried to update today but couldn’t figure out how to do it.

**Works: prettier 2.8.8, plugin-php 0.19.0**

```
$ nvm use 20 && npm install --global prettier@2.8.8 @prettier/plugin-php@0.19.0 && npm list --global && echo '<?php $foo="bar";' | prettier --stdin-filepath=foo.php
Now using node v20.5.1 (npm v9.8.0)

changed 8 packages in 1s

2 packages are looking for funding
  run `npm fund` for details
/home/marc/.nvm/versions/node/v20.5.1/lib
├── @prettier/plugin-php@0.19.0
├── corepack@0.19.0
├── npm@9.8.0
└── prettier@2.8.8

<?php $foo = "bar";
```

**Doesn't work: prettier 3.0.2, plugin-php 0.20.0**

```
$ nvm use 20 && npm install --global prettier@3.0.2 @prettier/plugin-php@0.20.0 && npm list --global && echo '<?php $foo="bar";' | prettier --stdin-filepath=foo.php
Now using node v20.5.1 (npm v9.8.0)

changed 8 packages in 863ms

2 packages are looking for funding
  run `npm fund` for details
/home/marc/.nvm/versions/node/v20.5.1/lib
├── @prettier/plugin-php@0.20.0
├── corepack@0.19.0
├── npm@9.8.0
└── prettier@3.0.2

[error] No parser could be inferred for file "foo.php".
```

```
$ prettier --support-info | grep -i php
(1) $
```

Maybe I’m making an obvious mistake, but I thought it couldn’t hurt to add this as an issue.

Thanks!

Marc

**Comment by czosel** [comment]
Hi @mermshaus, thanks for the bug report! It seems that plugins now have to be registered explicitly, e.g. by passing `--plugin=@prettier/plugin-php`. See [here](https://prettier.io/docs/en/plugins.html#using-plugins) for details and alternatives. We'll have to update our docs to reflect this.

@fisker has the implicit plugin registration been dropped?

**Comment by fisker** [comment]
[The plugin search feature has been removed.](https://prettier.io/blog/2023/07/05/3.0.0#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker)

**Comment by mermshaus** [comment]
Hi everyone,

thanks for the quick help! Adding the plugin configuration/CLI arguments solves this issue.

There is one thing of note: If you have a global installation of prettier, [plugin detection won’t work](https://github.com/prettier/prettier/issues/15141), at least not by simply specifying the package name. It’s possible to use an absolute path to a plugin’s entry point to work around this. E.g. `prettier --plugin /usr/lib/node_modules/@prettier/plugin-php/src/index.js`.

**Comment by coffebar** [comment]
@mermshaus I have tried your workaround with `plugin-php` and I see the error message is gone, but it's not gonna work: no formatting.
Is it still work for you?

**test.php**

```php
<?php
if(1 ){ echo 2;  }
?>
```

```bash
prettier --log-level debug test.php \
  --plugin /home/abc/.node_modules/lib/node_modules/@prettier/plugin-php/src/index.js \
  --parser php
```

Output:

```
[debug] normalized argv: {"":["test.php"],"cache":false,"color":true,"editorconfig":true,"logLevel":"debug","plugins":["/home/abc/.node_modules/lib/node_modules/@prettier/plugin-php/src/index.js"],"parser":"php","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"_":["test.php"],"__raw":{"_":["test.php"],"cache":false,"color":true,"editorconfig":true,"log-level":"debug","plugin":"/home/abc/.node_modules/lib/node_modules/@prettier/plugin-php/src/index.js","parser":"php","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"]}}
[debug] resolve config from '/home/abc/test.php'
[debug] loaded options `{"parser":"php","plugins":["/home/abc/.node_modules/lib/node_modules/@prettier/plugin-php/src/index.js"],"useTabs":false,"tabWidth":2}`
[debug] applied config-precedence (cli-override): {"parser":"php","plugins":["/home/abc/.node_modules/lib/node_modules/@prettier/plugin-php/src/index.js"],"tabWidth":2,"useTabs":false}
<?php
if(1 ){ echo 2;  }
?>
```

**Comment by mjsteinbaugh** [comment]
@coffebar Specifying the full plugin path works for me, but I find this to be an annoying regression as this wasn't required previously with prettier v2

**Comment by mermshaus** [comment]
@coffebar Yes, it still works for me. To avoid derailing this issue, I put more info [here](https://gist.github.com/mermshaus/db827721edcf22e80083f0b5f4c179f2). I hope it may be of help to you.

**Comment by felixmosh** [comment]
Downgraded to v2 since phpStorm uses global prettier & php plugin instances 👎🏼

**Comment by webdev23** [comment]
It's a node thing, it adds numerous JavaScript garbage everywhere and of course nothing work. 

After successfully obtained a PHD in node.js via internet, i found that to work.

Sharp eyes viewers may notice the `.mjs`.

```
node -v
v20.10.0
```

```
{
  "plugins": ["/usr/lib/node_modules/@prettier/plugin-php/src/index.mjs"]
}

```
