### ISSUE TITLE
`npx prettier . --check` doesn't check php files

### ISSUE THREAD

**Issue by martijngastkemper** [prettier/plugin-php#2253]
**Prettier 3.0.3**

**PHP Plugin 0.20.1**

**Input:**

```shell
npx prettier . --check
```

**Output:**

```shell
All matched files use Prettier code style!
```

**Expected behavior:**

An error about a PHP file. I've added a PHP file that doesn't match the code style:

```php
<?php $bar = function(string $foo) { return $foo; }; echo $bar('bla'); 
```

When I run `npx prettier **/* --check` it does give a warning about this test file. `. --check` does work for javascript, CSS, and other files. I can't find anything in the Prettier 3 release notes and the plugin-php documentation about this changed behavior since Prettier 2.

Does anyone know what I'm doing wrong?

**Comment by skyeewers** [comment]
Seeing the same issue with a fresh install of prettier and prettier-php here!
If I point `npx prettier --check ./sites/templates` (templates being a directory that only contains PHP files) I'm getting a warning that the directory contains no files the could be checked with prettier.

Halp? 🥺

**Comment by czosel** [comment]
The reason for this is most likely that you're either missing the PHP plugin, or you're not specifying that it should be used explicitly (the "plugin search" feature has been removed in Prettier v3, see https://github.com/prettier/plugin-php/issues/2215 for details).
