### ISSUE TITLE
Class and method braces with no body split onto multiple lines

### ISSUE THREAD

**Issue by hackel** [prettier/plugin-php#2275]
**@prettier/plugin-php v0.21.0**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCDoA6AIwgWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswJABaGNwWaABHQXhoANdlfz05BRBiEQgYErYytgqDAF8WKAp4GHQUNHgsSVA2bBgWkXbqzDBBMbwQAB4AfmMwAB1MDZjZEewAAk9hHp8AUQAPOP6sPagznUwKfbW1gCVBEngfKHPLjEw94CtDZbHbYfYAQUw2moSE8oP2wA2e2RexmHA8MT2UneMT+ewA+viYoNwriABRojF7YgwPYAEjOTFRgnR8ExNPpSQAlACgZg+SBWkA)

**Input:**
```php
<?php

class CustomException extends \RuntimeException {}

class AnotherClass {
    public function __construct(public int $x, public int $y) {}
}

```

**Output:**
```php
<?php

class CustomException extends \RuntimeException
{
}

class AnotherClass
{
    public function __construct(public int $x, public int $y)
    {
    }
}

```

**Expected behavior:**
The closed braces `{}` should remain inline, as per [PER CS 2.0](https://github.com/php-fig/per-coding-style/blob/2.0.0/spec.md#44-methods-and-functions).

**Comment by czosel** [comment]
Hi @hackel, sorry for the late feedback! I personally prefer the concise style as you suggest, and it's great to see that PER CS 2.0 also recommends it. @cseufert would you agree that we should move this forward?

**Comment by cseufert** [comment]
Yes, looks good to be, with it being PER it should be the way we do it.
