### ISSUE TITLE
Docs: specify if prettier follow psr-12 or something else

### ISSUE THREAD

**Issue by jehon** [prettier/plugin-php#2288]
I would suggest that the Readme.md would specify if this module follow any standard...

Because I did follow up this plugin blindly and the question arise afterward :-)

Thanks in advance and have a nice day,
Jean

**Comment by Kenneth-Sills** [comment]
[Per the maintainers:](https://github.com/prettier/plugin-php/issues/2060#issuecomment-1259314310)

> We have always used PSR / PER as guidance when making formatting decisions, but we never aimed to be fully PSR / PER compliant. Probably there are many more examples for this. To me, the idea behind this plugin is to stay reasonably close to how Prettier for JS works.

If there are conflicts with the standards and tooling you use, you'll need to resolve it through configuration - likely in those other tools, since Prettier is fairly opinionated.

**Comment by jehon** [comment]
Great idea! Perhaps to say that on the homepage would be a plus?
