### ISSUE TITLE
does not respect prettier printWidth in overrides since v0.22.0

### ISSUE THREAD

**Issue by apasov** [prettier/plugin-php#2341]
I have the following prettier config:

```
    "prettier": {
        "printWidth": 280,
        "semi": false,
        "singleQuote": true,
        "phpVersion": "8.2",
        "plugins": [
            "@prettier/plugin-php"
        ],
        "overrides": [
            {
                "files": [
                    "*.php"
                ],
                "options": {
                    "printWidth": 150,
                    "singleQuote": false
                }
            }
        ]
    },
```

Since v0.22.0 this plugin stopped respecting `printWidth` settings in overrides options and uses 280 instead. While `singleQuote` is respected correctly as it is set in overrides.

**Comment by cseufert** [comment]
Can you provide some example code, before and after formatting?

**Comment by apasov** [comment]
It was my mistake. The plugin just started treating `printWidth` differently since v0.22.0
It _does_ respect options set in overrides.
