### ISSUE TITLE
Use 4 spaces for indendation

### ISSUE THREAD

**Issue by mgrip** [prettier/plugin-php#25]
To align with the PSR2 standard, we need to use 4 spaces for indentation, rather than 2 (which is happening now). I _believe_ we achieve this by changing the default value for the `tabWidth` option from 2 to 4. I'm unsure exactly how to override the default value for a global option, from a plugin - @czosel pointed me to https://github.com/prettier/prettier/pull/3924, but I haven't been able to implement successfully yet.

**Comment by mgrip** [comment]
PSR2 spec: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#1-overview

**Comment by czosel** [comment]
Fixed by #124
