### ISSUE TITLE
Bug with `\` in strings

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#267]
Input:
```php
'/(<a\b[^><]*)>/i',
```
Output:
```php
'/(<a\\b[^><]*)>/i',
```

Looks like a bug in parser

**Comment by mgrip** [comment]
_Might_ get fixed with https://github.com/prettier/plugin-php/pull/263 assuming we use `node.raw` - but not 100% sure

**Comment by evilebottnawi** [comment]
@mgrip i will investigate this in near future. Right now we should add more valid tests :+1:
