### ISSUE TITLE
Quote escaping removed

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#298]
Input:
```php
$test = "\"$commandName\"";
```
Output:
```php
$test = ""$commandName"";
```

**Comment by czosel** [comment]
Puh, after debugging this a bit I think I'd appreciate your help with this one @mgrip

**Comment by ichiriac** [comment]
Hi  @czosel,

You could try to use the `raw` property when you find an `encapsed` node ? 
![image](https://user-images.githubusercontent.com/173203/38188384-1ac05f08-365c-11e8-8b79-cd3a40c3c448.png)

Seems that I missing the first `"`, I will open an issue on the parser for that

**Comment by evilebottnawi** [comment]
@ichiriac looks like problem still exists, i will try to upgrade php-parser to latest commit, but still got 2 `\\"` nodes :confused:

**Comment by czosel** [comment]
Hi @ichiriac, thanks for looking into this and the fix! In #350, I went with using the `raw` property of the `string` node instead of `encapsed.raw`, because otherwise we'd loose the ability to format complex expressions inside of encapsed nodes. Also, some tests were failing - the results looked like some more edge cases / issues in the parser.
