### ISSUE TITLE
Non-standard docblock causes formatting confusion

### ISSUE THREAD

**Issue by cmancone** [prettier/plugin-php#303]
This causes debug-check to complain, but doesn't actually break anything.  Notice the extra asterisk on the opening comment for the docblock - without that one asterisk everything works fine.

Input
```php
<?php
class test {
    /***
    * Configures the tasks tabs (sub_menu)
    */
    protected function get_sub_menu( $page = '' )
    {
    }
}
```
Output
```php
<?php
class test
{
    /***
        * Configures the tasks tabs (sub_menu)
        */
    protected function get_sub_menu($page = '')
    {

    }
}
```

Expected output:
```php
<?php
class test {
    /***
     * Configures the tasks tabs (sub_menu)
     */
    protected function get_sub_menu($page = '')
    {

    }
}
```

**Comment by mgrip** [comment]
so it appears prettier js doesn't handle indentation very well either - im gonna dumb our comment printing function down to just print the original comment as is
