### ISSUE TITLE
Newlines after closing PHP tag

### ISSUE THREAD

**Issue by cmancone** [prettier/plugin-php#304]
I noticed some issues related to new lines after a closing PHP tag.  The primary effect is the stripping of some of these newlines.  For a file that contains just a class definition this would actually be a good thing (although it causes debug-check to crash), but for something more like a template file it might be considered a change (although HTML obviously ignores whitespace).

**Input:**
```php
<?php
$code = true;
?>


```
**Output:**
```php
<?php
$code = true;
?>
```
running with `--debug-check` on results in:
```
[error] test.php: prettier(input) !== prettier(prettier(input))
[error] Index: 
[error] ===================================================================
[error] --- 
[error] +++ 
[error] @@ -1,3 +1,2 @@
[error]  <?php
[error]  $code = true;
[error] -?>
[error] 
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c prettier --plugin=. --parser=php test.php --debug-check
Directory: /var/www/prettier/plugin-php
Output:
".
```

**Comment by evilebottnawi** [comment]
@cmancone known issue, we will fix it in near future

**Comment by mgrip** [comment]
So the output is now

```php
<?php
$code = true;

```

Do we think thats correct? Do we care about the closing tag?

**Comment by evilebottnawi** [comment]
@mgrip yep, we should output all php tags as is

**Comment by czosel** [comment]
The closing tag should follow naturally once we have proper inline support, right? Until then, I wouldn't implement any special case for this.

**Comment by mgrip** [comment]
@czosel what do you mean by "proper inline support" exactly?

**Comment by mgrip** [comment]
fixed in https://github.com/prettier/plugin-php/pull/430
