### ISSUE TITLE
Inline hanging comments at end of file with extra newlines dropped or moved outside of php

### ISSUE THREAD

**Issue by cmancone** [prettier/plugin-php#305]
Obviously related to #304, but since there is a bit extra here (and it is potentially a breaking issue) so I'm creating another issue: feel free to close if appropriate.  On a file with extra newlines at the end **and** a comment at the end of the file, that comment can either be lost or moved outside of the PHP all together.  Two examples:

**Input:**
```php
<?php
class test{
} // some comment
?>


```
**Output:**
```php
<?php
class test
{

}
?>
```

Escaping PHP example
**Input:**
```php
<?php
class test{
}
// some comment
?>


```
**Output:**
```php
<?php
class test
{

}
?>// some comment

```

**Comment by mgrip** [comment]
Similar to #304, output is now

```php
<?php
class test
{

} // some comment


```

Do we think that's correct, or do we care about the closing tag?

**Comment by evilebottnawi** [comment]
@mgrip yep, as i said before, we should output all php tags as is, we prettier not codemod

**Comment by cmancone** [comment]
Obviously do whatever you guys want, but removing a closing PHP tag at the end of a file is not a breaking change (I've actually started removing them from our codebase).  That being said there is plenty of room for trouble doing so if the file has hanging newlines after the closing PHP tag.  If you remove a PHP tag in that case you would modify the meaning of the file (i.e. were it a template file, removing an ending PHP close tag when there are empty new lines after it would effectively remove the empty new lines from the end of the generated HTML).

**Comment by evilebottnawi** [comment]
@cmancone because you have `HTML` and `PHP`, for other formats (not PHP) it can be danger and can break output

**Comment by mgrip** [comment]
Maybe we could check the source and see if there's anything existing outside the program node? (ie whitespace), and if so, keep the closing tag?

**Comment by evilebottnawi** [comment]
@mgrip yep source code is good place to detect when we should output `<php` or `?>`
