### ISSUE TITLE
Create a playground for prettier

### ISSUE THREAD

**Issue by aboyton** [prettier/plugin-php#314]
This is potentially a question instead for the main Prettier repository, but any idea how hard it would be to get a playground for this plugin (or make the main playground support this parser)?

I know the focus right now is for an alpha release (and it's looking great, I found very few issues on the few hundred files I tried) and so I don't want to distract from that.

Having a playground is really nice both for debugging and also for reporting (the main prettier playground has a really nice issue creator button).

**Comment by mgrip** [comment]
Would be pretty cool if we could add a toggle to the existing prettier [playground](https://prettier.io/playground) to use different plugins/languages

**Comment by vjeux** [comment]
Agreed, would be nice to have it on the main prettier website since the PHP plugin is now in a good shape. If someone wants to set it up that would be great.

**Comment by sirbrillig** [comment]
Is this complete? https://loilo.github.io/prettier-php-playground/

**Comment by czosel** [comment]
@sirbrillig It's functionally complete, but it’s a reimplemention specifically for the PHP plugin (I think based on Vue.js). The original goal of integrating it with the “main“ playground is not achieved yet.

**Comment by czosel** [comment]
I'll go ahead and close this for now :upside_down_face:
