### ISSUE TITLE
Debug check complains about prettier cleaning extraneous newlines between comments

### ISSUE THREAD

**Issue by cmancone** [prettier/plugin-php#321]
Just to say out loud: I think the fact that my title's are getting longer and longer is an awesome sign.  It seems to me that we're long passed fixing serious issues and now I'm just finding increasingly more obscure edge cases.  Thanks guys, it's fun to see this all coming together!

Onto the issue: when there is more than one newline between comments (with no code between the comments) prettier removes an extraneous newline (and I think it should!) but debug check then complains that the code has changed.  From a code management standpoint, I don't see a need to have comments separated like this in the first place.  I'd be perfectly fine if prettier removed all newlines between comments.  Also, since this isn't an error anyway, and is simply a false-positive from debug-check, I'm okay if the answer is "just ignore this".

Input:
```php
<?php
class test {
    public function more_test() {
        // this is a comment


        // this is another comment
        if (true) {
            return 'some code';
        }
    }
}
```
Output:
```php
<?php
class test
{
    public function more_test()
    {
        // this is a comment

        // this is another comment
        if (true) {
            return 'some code';
        }
    }
}
```

On debug-check run:
```
[error] clean.php: prettier(input) !== prettier(prettier(input))
[error] Index: 
[error] ===================================================================
[error] --- 
[error] +++ 
[error] @@ -5,5 +5,4 @@
[error]      {
[error]          //input = array of data for creating the upload
[error] -
[error]          //right now, only one file upload allowed
[error]          if (true) {
[error] 
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c prettier --plugin=. --parser=php clean.php --debug-check
Directory: /var/www/prettier/plugin-php
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/prettier/plugin-php/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by evilebottnawi** [comment]
@cmancone It is difference comment, first - just comment, second - leading comment. Many people have newline between comment and leading comment. I think we don't remove newline between, but should be not error. Need investigate.

**Comment by mgrip** [comment]
Believe this is the same as https://github.com/prettier/plugin-php/issues/368
