### ISSUE TITLE
Escaped double-quotes become unescaped

### ISSUE THREAD

**Issue by hawkrives** [prettier/plugin-php#322]
PHP: 7.0
Node: 9
prettier-php: 26c6262
prettier: <code>[d676188](https://github.com/prettier/prettier/commit/d676188dbb0c99de57bdffda96ab0cccb1abfa1d)</code>

Input:
```php
class Extensible_Walker_Nav_Menu extends \Walker_Nav_Menu
{
	public function start_lvl(&$output, $depth = 0, $args = []) 
    {
		$indent = str_repeat("\t", $depth);
		$output .= "\n$indent<ul class=\"sub-menu\">\n";
    }
}
```

Output:
```php
class Extensible_Walker_Nav_Menu extends \Walker_Nav_Menu
{
	public function start_lvl(&$output, $depth = 0, $args = [])
	{
		$indent = str_repeat("\t", $depth);
		$output .= "\n$indent<ul class="sub-menu">\n";
	}
}
```

The escaped quotes in `class=\"sub-menu\"` are un-escaped in the output, which makes it invalid PHP. 

(On the bright side, the `\n` are retained, so that's nice. 😄)

**Comment by evilebottnawi** [comment]
@czosel yes, duplicate.
@hawkrives Thanks for issue. Already tracked :+1:

**Comment by hawkrives** [comment]
@czosel Yeah, I think it is. Sorry about that!

Duplicate of #298

**Comment by czosel** [comment]
No worries :smile:
