### ISSUE TITLE
"abstract static public function" in interface becomes "abstract public static function"

### ISSUE THREAD

**Issue by hawkrives** [prettier/plugin-php#327]
I did some cursory searches, but I didn't see this decision explicitly stated anywhere.

I think that these two are functionally identical, but I just wanted to make sure that this was intended.

(The difference is that `static public` becomes `public static`.)

---

PHP: 7.0
Node: 9
prettier-php: 26c6262
prettier: <code>[d676188](https://github.com/prettier/prettier/commit/d676188dbb0c99de57bdffda96ab0cccb1abfa1d)</code>

### Input
```php
interface Site
{
	abstract static public function get_site_id(): int;
}
```

### Output
```php
interface Site
{
	abstract public static function get_site_id(): int;
}
```

(edited to add prettier / prettier-php version info)

**Comment by evilebottnawi** [comment]
@hawkrives expected, PSR-4 and PSR-12 https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#46-abstract-final-and-static

**Comment by hawkrives** [comment]
@evilebottnawi thanks 👍
