### ISSUE TITLE
Extra space before `static` keyword in class variable declaration

### ISSUE THREAD

**Issue by hawkrives** [prettier/plugin-php#328]
PHP: 7.0
Node: 9
prettier-php: 26c6262 (`master`, after #315 [fix: extra space for `static` property] was merged)
prettier: <code>[d676188](https://github.com/prettier/prettier/commit/d676188dbb0c99de57bdffda96ab0cccb1abfa1d)</code>

### Input
```php
<?php
class Sidebar extends Base {
	static $cache;
}
```

### Output
```php
<?php
class Sidebar extends Base
{
	 static $cache;
}
```

### Expected Output
```php
<?php
class Sidebar extends Base
{
	static $cache;
}
```

---

The `static` keyword gets re-printed with an extra space before it, so it becomes `\t static $cache;` instead of `\tstatic $cache;`.

**Comment by evilebottnawi** [comment]
@hawkrives regression, thanks!
