### ISSUE TITLE
Formatting: Heredoc/Nowdoc inside arrays and function calls

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#333]
Example output:
```php
$content = array(<<<'EOF'
foo
EOF
, "bar");
```
Not sure what would be cleaner - maybe something like
```php
$content = array(
<<<'EOF'
foo
EOF
    , "bar"
);
```

**Comment by nicoder** [comment]
or

```php
$content = array(
    <<<'EOF'
foo
EOF
    ,
    "bar"
);
```

(the first element can be indented normally, the comma is at the end of a line, and the second element starts on its own line)
