### ISSUE TITLE
Potential nodes print without comments.

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#347]
Need add tests for each
- [x] interface
- [x] exit
- [x] goto
- [x] silent
- [x] halt
- [x] break
- [x] continue
- [x] traituse
- [x] traitprecedence
- [x] traitalias
- [x] label

For many nodes i already send PR. I think list above is last. When we should improve ugly output :+1:

**Comment by evilebottnawi** [comment]
Cross issue https://github.com/prettier/prettier/issues/4276

**Comment by evilebottnawi** [comment]
Information: strange with
```php
exit(/* Comment */);
```

**Comment by mgrip** [comment]
🎉 nice work @evilebottnawi

**Comment by evilebottnawi** [comment]
Looks like all nodes print comments, but i will add more tests, example around empty arguments in function  and double check every node.
@mgrip Thanks!
