### ISSUE TITLE
Question, Tokens vs Ast

### ISSUE THREAD

**Issue by ichiriac** [prettier/plugin-php#358]
Hi,

I'm wondering why do you need AST in order to print PHP files. You could maybe use instead tokens. They have some benefits :

 - 2x to 5x faster than the AST parser (https://github.com/glayzzle/php-parser/issues/57)
 - You could format a file with a parsing error without breaking it (as the tokenizer don't mind about PHP grammar)
 - More easy to handle comments at any position
 - You can be sure you can't miss any node or statement as 100% of code source is translated to tokens

**Comment by evilebottnawi** [comment]
@ichiriac sometimes we need context where keyword used, example get parent and determinate it is ternary. AST very help us to detect context and change output based on this (example functiuon in ternany or closure inside `if`)

**Comment by evilebottnawi** [comment]
Also tokens from php sometimes invalid (newline in inline is best example), you already fix ast to improve usage for us and other people who use your parser.

**Comment by ichiriac** [comment]
Oh, got it about ternary. Indeed context would be hard to retrieve from tokens, would result in a pseudo ast representation.

I just feel that joining tokens, and just handle T_WHITESPACE would be easier and maybe more accurate.
