### ISSUE TITLE
Comment shuffling on arrays and declarations

### ISSUE THREAD

**Issue by aboyton** [prettier/plugin-php#366]
Not sure if this is related to #323 or not.

```php
<?php
$array = [
    123 => true, // A comment
    456 => true, // Another comment
];

$foo = 123; // A comment
$bar = 456; // Another comment

```
is converted to
```php
<?php
$array = [
    123 => true,
    // A comment
    456 => true, // Another comment
];

$foo = 123;
// A comment
$bar = 456; // Another comment
```

I'd much prefer if the comments could be left on the same line.

**Comment by mgrip** [comment]
pretty sure this is the same as https://github.com/prettier/plugin-php/issues/323 - I'll close for now, if its still broken after fixing 323 we can reopen
