### ISSUE TITLE
Newline required after opening php tag

### ISSUE THREAD

**Issue by aboyton** [prettier/plugin-php#367]
Prettier removes any newlines There's not a newline after `<?php`.

```php
<?php

$a = 1;
```
is converted to
```php
<?php
$a = 1;
```

I think the spec is reasonably clear that you must have a newline between the `<?php` block and the next block (whatever it is). https://github.com/php-fig/fig-standards/blob/6d44cdf2f06ab2440212facbaa3f3e787b24875d/proposed/extended-coding-style-guide.md#3-declare-statements-namespace-and-import-statements

> ## 3. Declare Statements, Namespace, and Import Statements
> The header of a PHP file may consist of a number of different blocks. If present, each of the blocks below MUST be separated by a single blank line, and MUST NOT contain a blank line. Each block MUST be in the order listed below, although blocks that are not relevant may be omitted.
>
> * Opening `<?php` tag.
> * File-level docblock.
> * One or more declare statements.
> * The namespace declaration of the file.
> * One or more class-based `use` import statements.
> * One or more function-based `use` import statements.
> * One or more constant-based `use` import statements.
> * The remainder of the code in the file.

This was all discussed in https://github.com/prettier/plugin-php/pull/198 which seems to fix this issue but it hasn't been pushed for reasons I haven't understood so I thought I'd open an issue to track it.

**Comment by evilebottnawi** [comment]
Now we respect newline between each block above. Should we **always** add their or not?

**Comment by gouch** [comment]
For PSR-12, yes/no to a blank line after `<?php` was [undecided](https://groups.google.com/d/msg/php-fig/kIqR-7WI690/OgXPCW6KBQAJ) for a long time. IMO that section of the spec as currently written is ambiguous, but if you look at that section's history, the *intent* seems to be to require a blank line after the opening `<?php` tag: See that [`<?php` was added](https://github.com/php-fig/fig-standards/pull/984/files#diff-6117460e83bc73740412811e8a0477cbR125) to an already existing list of items that need a blank line between them.

That said, it specifies *opening* `<?php` tags need a blank line. I'm not sure if that means specifically the first-line PHP tag in a PHP-only file, or if it includes every PHP block in a multi-language file with multiple PHP blocks.

To me, `<?php` blank line is still ambiguous in different contexts, so I would say don't force a certain behavior until PSR-12 gets clearer

**Comment by evilebottnawi** [comment]
By default we respect user input, so if you add newline we keep newline if you don't add we don;t add newline, prettier do same
