### ISSUE TITLE
Newlines before opening braces in class definition

### ISSUE THREAD

**Issue by winged** [prettier/plugin-php#370]
Just testing the plugin, and found one issue with too many newlines between class declaration and the following open brace. I have the following code fragment:

    class Custom_Plugin_NotificationPlaceholderSource extends Notification_Manager_DefaultPlaceholderSource {
        # ...
    }

Which gets transformed to the following, which contains one newline too many:

    class Custom_Plugin_NotificationPlaceholderSource
        extends Notification_Manager_DefaultPlaceholderSource
    
    {
        # ...
    }

**Comment by evilebottnawi** [comment]
@winged Thanks for issue
