### ISSUE TITLE
Comments on extends/implements statement with function

### ISSUE THREAD

**Issue by sseypt** [prettier/plugin-php#388]
Hello again.

This issue is probably related to #357.
Yet formating this will only add an unnecessary line break.

Input:
```php
<?php
class ClassA extends ClassB // comment
{
    public function someFunction()
    {

    }
}

```

Output:
```php
<?php
class ClassA
    extends ClassB // comment

{
    public function someFunction()
    {

    }
}

```

Best regards,
Steve

**Comment by evilebottnawi** [comment]
@sseypt thanks for issue, already fixed in master https://github.com/prettier/plugin-php/pull/371/files

**Comment by czosel** [comment]
I'll close this since it should be fixed already - feel free to reopen in case you still see the issue on the current master.
