### ISSUE TITLE
First object method call on the same line

### ISSUE THREAD

**Issue by bertuz** [prettier/plugin-php#415]
Hi everyone, my team is using mehtod chaining with the first method call on the same line:
```
            $timelineClientBuilder->setUserId($userId)
                ->setPagination(static::PER_PAGE_QUERY, $page)
                ->setEventType($eventType)
                ->setDateRange($startDate, $endDate);
```

but prettier outputs this like the following:

```
            $timelineClientBuilder
                ->setUserId($userId)
                ->setPagination(static::PER_PAGE_QUERY, $page)
                ->setEventType($eventType)
                ->setDateRange($startDate, $endDate);
```

is there already a way to tells prettier to adopt the first formatting? Or is there a workaround for this? Thanks in advance

**Comment by evilebottnawi** [comment]
Bug, Thanks!
Example from js: [Expected](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAJDAlgWzgGyyjgGFCEYAhAVy3wBM4AnAOgGc4YBVDpgSXoAKdNV4CAlAB0oqWXPkLU7TgAUAhgHMia7NEFsYOrGCRIVAUQBKAfRUBBAOLnrARS5WAmgBoMAB01wUjKKIbLKMOYAbhQAKgCevnDCcNGw8YlBoaHhACI6cJZqUBpJ6AZqTDB58D7oCPTVgQDcIF4gEL66UGzIoBVMEADu6kwIPShqkRBY9K0gAEZMamAA1pwAyv5gRBrIMEzUcG1EvDAqSxo4asgAZmr4HG0AVmwAHpRLqxtqeAAyRHBbvdHiB-ExeMgFmp5nF8NA5r4mEQYAB1GYwAAWyAAHAAGNqIiAcFFLXyQxFwXjROajACOtFG500VyBDyOIA4OCwewO7LYO3wcBc1Ag8FZIMM8zR9ExyAATG19mo6DsSBAcCyUFBoIC2qI4DFoeM7myAL6moA)

Feel free PR with fix it.

**Comment by mgrip** [comment]
@evilebottnawi the JS example you listed prints the same as our plugin?

**Comment by evilebottnawi** [comment]
@mgrip oh yes, it is not bug, sorry, tired
@bertuz it is expected behaviour

**Comment by evilebottnawi** [comment]
@bertuz you can use `phpcs` or other codemodes utils for this this for your team. Each `->` on new line looks better and easy to read

**Comment by virgofx** [comment]
I agree prettier is formatting it correctly. Method chaining should drop every action to new line including first. This is how DOM attributes are handled as well.
