### ISSUE TITLE
Formatting of `::` 

### ISSUE THREAD

**Issue by mathiasrw** [prettier/plugin-php#419]
I'm super excited for this plugin. Letting hybrid web-apps use one formatter for everything is awesome. 

> Please note that this plugin is currently in alpha stage and still under active development. We encourage everyone to try it and give feedback

On the note of "We encourage everyone to try it and give feedback" I have the following feedback:

Recently the plugin formatted like this

```
DB::table('identity')->insert([
	'ref' => $ref,
	'handle' => $handle
]);
```

however, something changed the last week so it now formats like this

```
DB
	::table('identity')
		->insert([
			'ref' => $ref,
			'handle' => $handle
		]);
```

Is anyone aware if this reflects a change I prettier itself, or the plugin-php?

Asked a few programmers and they all really prefer the previous formatting. I have a feeling the cognitive connection of having "table", "Identity" and "Insert" is helpful. 

Is there a thread discussing the effects of, for example, placing the `::` part on a new line?

**Comment by evilebottnawi** [comment]
@mathiasrw thanks for PR, it is bug

**Comment by evilebottnawi** [comment]
Should be easy fix :+1:

**Comment by mgrip** [comment]
Interesting though that it changed recently... I don't think there have been any changes deployed to this repo in at least a couple weeks

**Comment by mathiasrw** [comment]
Sounds good. Ill close it...

**Comment by evilebottnawi** [comment]
Need add tests

**Comment by mgrip** [comment]
For reference: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEARAQgdwJYwBYA20A5lAIYC2cSSMZARgXABQDk2AJgjLgJ6sBKAHTYoAZzgAnGACU4ZAgV5yFSlYt4AZEgDlKLYWIhUA8vinq18jdqjFmAgNwgANCAgAHHtDHJQZSUkITAAFAIRfFDIANwhOVxB6STIwAGs4GABlDxTRYmQYSQBXODdRCWkQ5OIKMmQAMwUJNwArMQAPdGS0jMz9TVE4BqbSkBzJCuREhl4iKASPSVEYAHVOfGQADgAGN0WICRXkjynFuAroobdJOABHIuwbqrIauqRGgmaQCQpsAuLRmI8kwAIpFCDwYafUZ0ehrDgbJAAJjchTI2AIeQAwsZalMoNAriAihIACoMSIfCQAX2pQA

**Comment by mathiasrw** [comment]
🎉
