### ISSUE TITLE
Shouldn't break immediately for method chains

### ISSUE THREAD

**Issue by mgrip** [prettier/plugin-php#420]
We always break method chains after the 1st member, but looks like prettier JS does it after the second

output:
```php
Logger
    ::use_logger('albus')
    ->info('Albus: failed to find active version for albus object', [
         'uuid' => $uuid,
         'requested_date' => $date
     ]);
```

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCBzDcBOA6AVwGc4B9AG02xwAoByAQ3ICNi6BKAHSgAI-+BeAJZQAZhHoBBFsSQ9RDIeTgATHjAjyRahmBhCAbnB5GcRIdHkQcPJqyI8IzAFZw9dADQ9g3AX-50BARCKnRyACRBIR6+-n50OHAAjgRwRPAqpCoM8GE84dnw3AC+7ADc3NzoWLgA6kIwABboUBgAcgwAtnCEJADKEN0A8k24ACqNIhj1TS3tXXA07HiNcOSUS3jQcACy1ovL23uJAKIAHl0ADsozzdDzDI9P3UtlIB4gEJf60ETIoAwcDgIAB3AAKgIQfxQDAMEBC7xAzBwugA1nAYH1LropsgYDhUh8RCQcDAwSiMJ0GMgFOQSB9nEQzgAhFFgdGYhaoERwGlMekgbFmXDIJEMZgAT0oUERlxwIhg9RUTWQAA4AAwfOUQEi1FGXUVytK4IyIxIpISJckMSnUpC0gUkTpCPEEuAfcytZQARQIEHgfLp7pAMHFSpVSAATB98YpyFMAMKDKmiqDbRHEOBjcXQh1wYrFIA

**Comment by evilebottnawi** [comment]
@mgrip i think better https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCBzDcBOSkCuAznAPoA2m2OAFAOQCG5ARsXQJQA6UABH-wIB0ASygAzCPQCCLYkh5iGw8nAAmPGBAWj1DMDGEA3OD2M4iw6Aog4eTVkR4RmAKzj66AGh7BuA--x0BATCqnTyACTBoZ5+Af50OHAAjgRwRPCqpKoM8OE8ETnw3AC+7ADc3NzoWLgA6sIwABboUBgAcgwAtnCCxHAAyhA9APLNuAAqTaIYDc2tHd1wNOyCTXDklCuC0HAAsjbLq7sHSQCiAB7dAA4qcy3QiwzPLz0r5SCeIBDXBtBEyFADBwOAgAHcAArAhAAlAMQwQUKfEDMHB6ADWcBgA2uehmyBgODSX1EJBwMAhaIwXQYyEU5BIXxcRAuACE0WBMdilqhRHA6UxGSBceZcMgUQxmABPShQZHXHCiGANVTNZAADgADF8FRASHU0ddxQr0rhjMikqlhElKQxqbSkPShSQusICUS4F8LG0VABFAgQeAChmekAwSUqtVIABMX0JSnIMwAwsMaeKoLtkf0JpLYU64CUSkA

**Comment by mgrip** [comment]
Didn't know `::` was valid JS haha
