### ISSUE TITLE
Remove github dependencies

### ISSUE THREAD

**Issue by mgrip** [prettier/plugin-php#422]
We're trying to start using this at our work, but dependencies that aren't on npm are a hard blocker. Asked for the parser to be updated to latest here https://github.com/glayzzle/php-parser/issues/160 - after that's done I can update our `package.json` and publish a `0.2.0`.

**Comment by czosel** [comment]
Awesome! If I wouldn't be that swamped with work I probably would have pushed for this in my team already, too. Did you find any working editor integration already, or are running prettier just in a pre-commit hook?

**Comment by mgrip** [comment]
I've actually been using this for atom https://atom.io/packages/save-autorun, and for phpstorm you can set up an external tool pretty easily!

for both i just point them to `npm run prettier <filename>`

**Comment by czosel** [comment]
Nice! I hope "first-class" support for plugins in prettier-atom, prettier-vscode and vim-prettier will also land soon :slightly_smiling_face:
