### ISSUE TITLE
Nested arrays should keep opening bracket on same line as key 

### ISSUE THREAD

**Issue by adamroyle** [prettier/plugin-php#434]
Version: 0.2.2

Input/Output:

```php
$helpers = [
  'Lazy',
  'Form' =>
    [
      'templates' => 'app_form',
      'widgets' =>
        [
          'select' => ['App\View\Widget\SelectBoxWidget'],
          'nestingLabel' => ['App\View\Widget\NestingLabelWidget']
        ]
    ],
  'MagicMenu.MagicMenu'
];
```

Expected:

```php
$helpers = [
  'Lazy',
  'Form' => [
    'templates' => 'app_form',
    'widgets' => [
      'select' => ['App\View\Widget\SelectBoxWidget'],
      'nestingLabel' => ['App\View\Widget\NestingLabelWidget']
    ]
  ],
  'MagicMenu.MagicMenu'
];
```

**Comment by mgrip** [comment]
JS output to confirm:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAFnANgBzgJwGcACAXmOAB0pjj5CYliByAGQEMAvAT2YBpqtZgDEI+ALbNiTKjVot44nFnb0pTZuxw4A+gDMxkgXKEB3AJYATAOZwYhdRUHyhhbHDAxHAbWYBBbUpKADVzOFMggHUrWxgggGV3TwAhCAAPaJs7ZgBdYxchKDgGcyhrDgAjbB9-QJCwiMpM2KCAOWKYUvL2Kqxm7JznFwBfamH8ug6NAFl2a3MwaYQAVwA6WfnFleYxgG4QPhAIHE7oQmRQdnx8CFMABSuEc5R2ADcIKwOQCvx2MABrOzxHB-LrIGD4ZZwQ6lNz4GB3X7WcTsZB6dhYNyHABWhDSyV+AKB7HEcFYpTgaIxWJAIKIBGQ3x63Cw0C+OHwpRgmRg6GQAA4AAyHDkQNyRX44Rkc4oEV6Uw74OAAR2W5iViLmKKpmOhIDc4nM4MhesIXSwcAAissIPAdTSYD0eXykAAmQ4Q9jmLBdADCEHE2pQUGgCpAyzcABUes90brhsMgA
