### ISSUE TITLE
Comments being moved above opening tag for inline php

### ISSUE THREAD

**Issue by adamroyle** [prettier/plugin-php#435]
This might be a duplicate of the other comment bugs, but listing here just in case.

Version: 0.2.2

Input/Expected:

```php
some text
<?php
/**
 * A comment
 */
$thing = 1;
```

Output:

```php
some text
/**
 * A comment
 */
<?php
$thing = 1;
```

**Comment by mgrip** [comment]
thanks for reporting @adamroyle!

**Comment by evilebottnawi** [comment]
@mgrip looks already fixed

**Comment by mgrip** [comment]
Oh awesome 🎉
