### ISSUE TITLE
Inline comments don't count towards line length

### ISSUE THREAD

**Issue by sseypt** [prettier/plugin-php#438]
Hello.

It seems like inline comments do not count towards line length limitation.
I'd recommend to follow [Sonar PHP:S139](https://sonarcloud.io/coding_rules?open=php%3AS139&rule_key=php%3AS139) in that regard.

Version:
```
+ @prettier/plugin-php@0.2.2
+ prettier@1.13.5
```

Input:

```php
<?php
$var = $condition
    ? 'Text'
    : 'AnotherText'; // loooooooooooooooooooooooooooooooooooooooooong comment
```

or

```php
<?php
$var = ' Text' .
    'another Text'; // loooooooooooooooooooooooooooooooooooooooooong comment
```

Output:

```php
<?php
$var = $condition ? 'Text' : 'AnotherText'; // loooooooooooooooooooooooooooooooooooooooooong comment
```

or 

```php
<?php
$var = ' Text' . 'another Text'; // loooooooooooooooooooooooooooooooooooooooooong comment
```

Expected:

```php
// loooooooooooooooooooooooooooooooooooooooooong comment
$var = $condition ? 'Text' : 'AnotherText';
```

Best regards,
Steve

**Comment by evilebottnawi** [comment]
@sseypt move comment is very danger in this situation (some comments can have `phpcs` rules, also comments can be more than 80 characters in line), we use prettier logic:
1. https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAbgQwE4AIC8uqkUAJgJYznQA6UuDuA-LgOQAqcAHjK3Y7iRsAglAgwAFnGycerANy4A9EtwAbCJq3aduvft1QA5rkgBbMwhggANCAgAHKtADOyUDmwQA7gAUcCG4omOgQ5KS2IABG2JhgANZwMADKDnHkxsgw2ACucHYZLtIwvrFGZpjIAGaYakV2AFYuXABCsQlJyZiWADIZcNW19SBp2EXYyNGYUQCeGlCRDtgZMADq4ZLIABwADHZLEEWrsQ6TS3Dj6AN22HAAjjnkt6WY5ZVINXX5IEVm5Fm5b4uDJGNRwACKOXEAw+Q2+MGm61ImyQACY7NlMOQ1CCAMIQCzvEBiKDXEA5IrsaZBT5FAC+dKAA
2. https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAbgQwE4AIC8uA5LgCpwAeMJA1ADpS5PGZQQwAWce5VRA3LgD0Q3ABsIkqdJmy582VADmuSAFs1CGCAA0ICAAcYAS2gBnZKBzYIAdwAKOBBZSZ0EYwBNdIAEbZMMABrOBgAZQNA42VkGGwAVzg9aLNuGHsApTVMZAAzTDFUvQArMwoAIQDg0LDMTQAZaLg8gqKQSOxU7GQ-TF8ATwkoHwNsaJgAdS9OZAAOAAY9UYhUiYCDHtG4LvRmvWw4AEd44wOMzCycpHzCpJBUtWNYhLuzaKUxOABFePZm69adxgfSmnhmSAATHo4phjGJ3gBhCAaK4gNhQPYgeKpUh9Fw3VIAX0JQA
3. https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAbgQwE4AIC8uA5LgCpwAeMJA1MZlBDABZx7lVEDcuA9L7gA2EEaLHiJkqRKgBzXJAC2ihDBAAaEBAAOMAJbQAzslA5sEAO4AFHAmMpM6CHoAmGkACNsmMAGs4MADK2j56csgw2ACucJphhmwwVt6yipjIAGaYggmaAFaGFABC3n4BgZgqADJhcJnZuSAh2AnYyJ6YHgCewlDu2thhMADqrizIABwADJoDEAnD3trtA3Ct6HWa2HAAjlF628mYqelIWTmxIAmKehHRl4ZhsoJwAIpRTHVnDZcwnaMucZIABMmkimD0gieAGEIMpTiBGFBNiAoglSJ17OcEgBfHFAA

Better create issue about this in prettier first

**Comment by sseypt** [comment]
https://github.com/prettier/prettier/issues/4754

**Comment by czosel** [comment]
I'll go ahead and close this, we can reopen the issue if there are any updates from prettier js.
