### ISSUE TITLE
Readme: Add setup instructions for PhpStorm

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#452]
See also #450 
/cc @mgrip

**Comment by K-Leon** [comment]
Did anyone managed to get it working in PHPStorm?

**Comment by evilebottnawi** [comment]
Yep, just install prettier and plugin-php and enable prettier in settings and all works fine

**Comment by czosel** [comment]
Documentation PRs welcome :wink:

**Comment by strider72** [comment]
Where do I put the settings?  I know *what* settings I want, but not where (or how) to put them
