### ISSUE TITLE
SyntaxError for multiline string

### ISSUE THREAD

**Issue by shreyas-a** [prettier/plugin-php#456]
Following is a valid `PHP` code snippet, still prettier throws a syntax error:

`SyntaxError: Parse Error : syntax error, unexpected '{'`

```
<?php

$chart = '
{
  "chart": {
    "caption": "Worlds Top 10 largest companies in 2017"
  }
}';

?>
```

**Comment by evilebottnawi** [comment]
@czosel feel free to send PR with test example, maybe old plugin version

**Comment by evilebottnawi** [comment]
Fixed https://github.com/prettier/plugin-php/pull/457 and https://github.com/prettier/plugin-php/pull/462
