### ISSUE TITLE
invalid comments place in traituse

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#459]
Input:
```php
class ImplementingClass {
    use TraitUseWithComments { /* Comments */ }
}
```

Output:
```php
class ImplementingClass
{
    use TraitUseWithComments /* Comments */ {  }
}
```

**Comment by ichiriac** [comment]
It's related to this missing feature : https://github.com/glayzzle/php-parser/issues/194 - the `use` node should have a `trailingComments` property including the comment
