### ISSUE TITLE
Linebreak in multiline strings

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#461]
Some multiline strings seem to have a linebreak before the opening quote. It seems to have something to do both with line length and number of lines :confused: 

Input:
```php
$multiline = '
  looooooooooooooooooooooooooooooooooooooooooooooooooooooong
  more
';
```
Output:
```php
$multiline =
     '
  looooooooooooooooooooooooooooooooooooooooooooooooooooooong
  more
';
```

Excpected output: Same as input.

**Comment by evilebottnawi** [comment]
@czosel let's fix it :+1: WIP
