### ISSUE TITLE
strange output with merge array

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#466]
Input:
```php
 $response->headers->replace($headers + [
    'Content-Type' => $this->mimeType($path),
    'Content-Length' => $this->size($path),
    'Content-Disposition' => $disposition,
]);
```

Output:
```php
$response->headers->replace(
    $headers + [
        'Content-Type' => $this->mimeType($path),
        'Content-Length' => $this->size($path),
        'Content-Disposition' => $disposition
    ]
);
```

Expected: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASATnAzgB2luAOgAs4BDAEznS0MxwBsyw4AKAHSgAIfe+fUpStSxcA1F2Cd+M-gEcA7tRgBPFUi4BGADTTZ+xcrUade-TMPpV6rbu7meAXzP8AlAG4Q2kBBwwAlvjIoGTo6BAKAAqhCFjIIGQAbhD+FF4gAEbozADWcDAAyjjM-lAA5sgw6ACucN6lBFaR2WUAtmTIAGZkDATeAFZYAB4AQtlgeYVkrXAAMqVwXT19IMU01PEZZBkqDNDpOOilMADqqTDEyAAcAAzehxAEJ9k48YfY1ImL3phy1f6YZpkNodJDdXp1EAEVr+So1SFYUplBhwACK1Qg8CWEO8MG2ZwoF2QACZcdl-AwkQBhCCtdrxKDQb4gaoEAAq2ziYOWcEcjiAA

But need discussion

**Comment by czosel** [comment]
To me, the way it's formatted right now also looks pretty good.

**Comment by evilebottnawi** [comment]
Close, because expected
