### ISSUE TITLE
Short echo syntax

### ISSUE THREAD

**Issue by gouch** [prettier/plugin-php#467]
Seeking some clarification on this behavior:

- Input: `There are <?= $variable; ?> examples.`
- Want: `There are <?= $variable; ?> examples.`
- Actual output: `There are <?php echo $variable; ?> examples.`

Is the [“short syntax”](https://php.net/echo) for `echo` being translated intentionally or is this a bug?

(Also, I'm not vouching for my exact use of optional spaces and semicolon — the PHP docs actually use the very compact `<?=$variable?>` — just wanted to clarify if short syntax is being rewritten on purpose.)

**Comment by evilebottnawi** [comment]
@gouch bug :+1:

**Comment by nikolasmatt** [comment]
what about multiline? 
input:
```php
<?= $someOtherVar()->element('collection/item-title', [
    'class' => $itemTitleClass,
    'small_title' => $item->small_title,
    'title' => $item->title,
    'url' => $url,
    'color' => $item->title_color ?: 'primary',
]); ?>
```
current output:
```php
<?php
echo $this->element('collection/item-title', [
    'class' => $itemTitleClass,
    'small_title' => $item->small_title,
    'title' => $item->title,
    'url' => $url,
    'color' => $item->title_color ?: 'primary'
]);
?>
```
output keeping the shorthand:
```php
<?=
$this->element('collection/item-title', [
    'class' => $itemTitleClass,
    'small_title' => $item->small_title,
    'title' => $item->title,
    'url' => $url,
    'color' => $item->title_color ?: 'primary'
]);
?>
```
