### ISSUE TITLE
Whitespace lines removed inside arrays

### ISSUE THREAD

**Issue by adamroyle** [prettier/plugin-php#468]
Possibly related to #368 

Single lines of whitespace between elements should be preserved. Multiple lines should collapse into a single line.

Input:
```php
$data = [


  'value',
  'value',
  

  // a comment
  'value',
  'value'


];
```

Output:
```php
$data = [
  'value',
  'value',
  // a comment
  'value',
  'value'
];
```

Expected:

```php
$data = [
  'value',
  'value',

  // a comment
  'value',
  'value'
];
```

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAJgQxpgBAXlwG0AdKMs3XAcgDdMAbAVzmoBpKb7nWOoqK-XAHphuPJAC2khDE51GLdvO5LBZALoBuEGxAQADjACW0AM7JQmAE7WIAdwAKNhBZSZaEY+l0gARtaYYADWcDAAygZBxlAA5sgw1ix6MWZw1jCOgbGSmMgAZoxpegBWZgAeAEKBIWHhmDIAMjFwBUVwelHWadbI-ph+AJ4M0L4G1jEwAOreMAAWyAAcAAyddmlTgQZ943A9tK161nAAjkzGx1mYOXlIhQzFIGmSxglJHU8xsQxwAIpMEHgbQeHxwfhm6HmyAATHpEphjAwvgBhCDSW4gKDQQ4gJhpAAqAzc9zSAF9SUA

**Comment by evilebottnawi** [comment]
@adamroyle thanks for issue
