### ISSUE TITLE
Invalid formatting with switch statement and comment

### ISSUE THREAD

**Issue by ntotten** [prettier/plugin-php#526]
The latest version of the php plugin produces an error that seems to be related to switch statements and comments. See the diff. Happy to provide more details if needed.

When removing the comment from the code, the formatting works as expected.

Using versions:
```
"@prettier/plugin-php": "^0.5.0",
"prettier": "^1.14.2"
```
![image](https://user-images.githubusercontent.com/282782/43959383-9f8221aa-9c7c-11e8-8768-ad7d68b6ca1a.png)

**Comment by ntotten** [comment]
Actually, looks like this might be a dup of #517.

**Comment by evilebottnawi** [comment]
@ntotten yep dup, can you put example of broken code in https://github.com/prettier/plugin-php/issues/517?

**Comment by evilebottnawi** [comment]
Close here
