### ISSUE TITLE
Bad comment handling

### ISSUE THREAD

**Issue by antonioribeiro** [prettier/plugin-php#527]
Before and after commenting a block of code inside a Closure:

![image](https://user-images.githubusercontent.com/3182864/43962028-f126b380-9c8c-11e8-9008-61ea990c4213.png)

This is what I get:

![image](https://user-images.githubusercontent.com/3182864/43962117-3bb7139a-9c8d-11e8-93ca-0fcae68cfb0e.png)

It does that one line by one, so it takes 11 CTRL-Zs to revert it all.

And in PHPStorm this is kind of a nightmare because you need to answer this question on every undo:

![image](https://user-images.githubusercontent.com/3182864/43962249-991c1346-9c8d-11e8-9f96-fcbdb0487eeb.png)

And this one

![image](https://user-images.githubusercontent.com/3182864/43962411-07525c58-9c8e-11e8-8259-55d65d507f30.png)

Becomes

![image](https://user-images.githubusercontent.com/3182864/43962437-168e5aaa-9c8e-11e8-9862-0f2203685262.png)

**Comment by evilebottnawi** [comment]
@antonioribeiro please use text inestead screenshot in future, it is better testing and fix

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/prettier/plugin-php/issues/701 and https://github.com/prettier/plugin-php/issues/700
