### ISSUE TITLE
broken inline

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#531]
Input:
```
<?php if (!is_ajax()) { ?>
    <?php do_action('woocommerce_review_order_after_payment'); ?>
<?php } ?>
```
Output:
```
<?php if (!is_ajax()) { ?>
    <?php do_action('woocommerce_review_order_after_payment');} ?>
```

It is break output. 

//cc @czosel I will try to search solution, if doesn't find, we should revert this. Because it is regression. Previous solution looks like hack but works great and doesn't break anything.

**Comment by czosel** [comment]
Fixed in #532
