### ISSUE TITLE
Ugly break of chain with call

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#537]
Input:
```php
        $this->view->members = (new Custom_Model_UserGroup())->getUsersByService($serviceId);
```

Output:
```php
        $this->view
            ->members = (new Custom_Model_UserGroup())->getUsersByService(
            $serviceId
        );
```
Expected:
Not sure, fixing the indentation would certainly help:
```php
        $this->view
            ->members = (new Custom_Model_UserGroup())->getUsersByService(
                $serviceId
            );
```

**Comment by evilebottnawi** [comment]
@czosel What about this https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+w+AOlPvhlrgcWZdXQw09nvWwpVa9bj0x9WcEkM5QAJDAAWOIgDoAbjjgB3NQFs4+gEZwATkXwBefKSi78AYXQkI+gPoBZCABM4AG3cAVSJzAHEzCHQABwpyNQBzOBgQ8yIAIQBPAGVzLTA4UnlQs3y4AEkfcgBuOgBfesaoOpAAGhAIaJYoImRQAEMzSJ0ABUGEXpR+jQgcHzaQYzN+sABrZOzolZwoBOQYM3Q4dp2SmBHlhP1+5FR+-1D2gCsiAA905bWN-sMAGR24Ld7o8QFsLOZkIt+sZMv5oAtomYdjAAOpzZTIAAcAAZ2oiIKEUctopDEdI8oD2mY4ABHdA4akXfpXG5IO4PY4gUL6HD7Q6cog7BL+OAARXQEHgQI57Rg0LRPgxSAALLLljh-ELHG5rpCoNBKSAXHAACrQybs0J1OpAA

**Comment by evilebottnawi** [comment]
Look prettier doesn't break line in this case on `=`

**Comment by czosel** [comment]
@evilebottnawi That looks even better :wink:
