### ISSUE TITLE
cast nodes break pretty output

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#539]
Input:
```
$var = 'veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString';
$var = (bool) 'veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString';
```

It is hard check in each place on `cast` node, maybe better solution move `cast` node out of ast and save this as `cast` argument on node. Need discussion.

**Comment by czosel** [comment]
What's the problem exactly? Did we forget to handle the `cast` node somewhere?

**Comment by evilebottnawi** [comment]
@czosel yep, many places where we don't handle `cast` statement, i will refactor this in future, maybe we can solve this on our side, just note issue
