### ISSUE TITLE
move brace to new line for functions

### ISSUE THREAD

**Issue by mgrip** [prettier/plugin-php#54]
From https://github.com/prettier/plugin-php/issues/45#issuecomment-366111694
> This came to mind when seeing the output:
> 
> The opening brace of a function should be on its own line according to PSR-12 (same as class methods).
> 
> (but the opening brace of a closure goes on the same line as the closing parens of the parameter list)

**Comment by aboyton** [comment]
I know we want to go with PSR-12 and we don't want to add options for everything, but man is that an ugly style.

**Comment by mgrip** [comment]
This got fixed a while ago - please reopen if you see anything else!
