### ISSUE TITLE
SyntaxError: Unexpected token after install

### ISSUE THREAD

**Issue by pjhartin** [prettier/plugin-php#55]
Having installed prettier and @prettier/plugin-php globally, I cannot seem to get prettier to work on any php files, it always results in a syntax error.

Am I doing something wrong?
![image](https://user-images.githubusercontent.com/1385026/36360625-e14836c2-1579-11e8-9488-479007c848a2.png)

**Comment by camflan** [comment]
I'm having the same issue - not using globally installed prettier though.

**Comment by mgrip** [comment]
I _believe_ you still need to specify the plugin manually, although that does seem to contradict the [prettier docs](https://prettier.io/docs/en/plugins.html#using-plugins). @azz or @vjeux do you guys have any more info on how plugins are intended to be run from a cli?

**Comment by camflan** [comment]
@mgrip I tried that as well, without luck.

The command I attempted,
`yarn prettier --plugin=./node_modules/@prettier/plugin-php app/Http/Controllers/ReserveController.php`

**Comment by mgrip** [comment]
what's the error you get when manually specifying the plugin? I'm guessing the package might have to be updated on npm - there have been a lot of changes since @azz originally published it

**Comment by camflan** [comment]
```
❯: yarn prettier --plugin=./node_modules/@prettier/plugin-php app/Http/Controllers/ReserveController.php
yarn run v1.3.2
$ /Users/camron/src/lodgetools/inntender/node_modules/.bin/prettier --plugin=./node_modules/@prettier/plugin-php app/Http/Controllers/ReserveController.php

[error] app/Http/Controllers/ReserveController.php: SyntaxError: Unexpected token (1:2)
[error] > 1 | <?php
[error]     |  ^
[error]   2 | 
[error]   3 | namespace InnTender\Http\Controllers;
[error]   4 | 
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by mgrip** [comment]
@vjeux @azz do you guys know how the plugins are intended to be run from the cli? the [docs](https://prettier.io/docs/en/plugins.html#using-plugins) make its seem like plugins are intended to be found automatically, but it doesn't seem like thats happening

**Comment by vjeux** [comment]
I don’t know, @azz built all the support for it.

**Comment by evilebottnawi** [comment]
Confirm don't work as expected

**Comment by mgrip** [comment]
Ok think I got something that will at least work for now. 2 main things
1) you still need to specify the parser
2) while we're developing you should probably use the repos as dependencies rather than whats published on npm as things are getting updated very quickly

so this should work
```yarn add --dev prettier/prettier prettier/plugin-php```
```prettier --parser=php /some/php/file.php```

I can update the readme accordingly

**Comment by mgrip** [comment]
@camflan @pjhartin can you guys see if that worked when you have a chance? if so I'll close this out for now

**Comment by mgrip** [comment]
Pretty sure this is working - gonna close for now

**Comment by camflan** [comment]
@mgrip yep, those steps worked. Not sure why reinstalling prettier as `prettier/prettier` works but my existing install would fail. 

Thanks 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mgrip** [comment]
i believe its because `prettier` would just add whatever the latest version published to npm is, `prettier/prettier` references the git repo (and there are recent changes that the plugins rely on)

**Comment by camflan** [comment]
Oh, ok!

- Camron

**Comment by pjhartin** [comment]
@mgrip Thanks, I followed your instructions and all seemed to work well.i did notice however that a number of phpDoc comments within my phone code were being stripped away by prettier though. So I'm not 100% on using it right now.

**Comment by azz** [comment]
@pjhartin Please raise bugs for those items!


@mgrip Sorry for the delay in responding. Fixing it in https://github.com/prettier/prettier/pull/4038.
