### ISSUE TITLE
Array in function line break

### ISSUE THREAD

**Issue by mathieutu** [prettier/plugin-php#608]
```diff
-            return response()->json([
-                'type'     => 'validation',
-                'fields'   => $errors->keys(),
-                'messages' => $errors->values()->collapse(),
-            ], $exception->status);
+            return response()->json(
+                [
+                    'type' => 'validation',
+                    'fields' => $errors->keys(),
+                    'messages' => $errors->values()->collapse(),
+                ],
+                $exception->status
+            );
```

The previous one is valid, and is the way we should format it imo.

**Comment by evilebottnawi** [comment]
@mathieutu see https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAJ0DOADtAXABQCUAdAFYHTkA6eub7HnwLnvfbAchgBPInAFJcAgG4BDADYBLACayYi6AIA0PfnsEAzRXHnKCE3ABI4qVBFQFqAazjCCVHa338BAWzgEBLIA5gEW1rb2jnLymAFU1JDy8rJEZB663uwAvp5ZHNYAHmBwROrQ1AQwapgEmXqUANwgWiAQZRpQBMigspEA7gAKfQjdKLLSECotIABGqLJgLjAAykSLilDByDCoca2bZKgwgwvBvrLIBgpkrfSFAEILSxgrsv4AMptwVzdwresHDZkHNZLNhPJoDMiKhNjAAOoqGAAC2QAA4AAwAuxkeELIggmEBGzSH6tdAAR0winQpxCF1+8luIDIvkUOz2-xZm2C8jgAEVMBB4IzmdVZojlCjkAAmVq7WSKJRbADCEF8DJQUGgZJAtTgABUwWNrky4NlskA

**Comment by mathieutu** [comment]
And so?
same here, old one is valid and should be the standard:
```diff
-        return array_map(function ($rule) {
-            return 'sometimes|' . $rule;
-        }, [
-            'last_name'    => 'required|string|max:255',
-            'first_name'   => 'required|string|max:255',
-            'room'         => 'max:255',
-            'gender'       => 'required|integer|' . Rule::in(User::GENDERS),
-            'device_token' => 'required|string',
-            'available'    => 'required|boolean',
-        ]);
+        return array_map(
+            function ($rule) {
+                return ('sometimes|' . $rule);
+            },
+            [
+                'last_name' => 'required|string|max:255',
+                'first_name' => 'required|string|max:255',
+                'room' => 'max:255',
+                'gender' => 'required|integer|' . Rule::in(User::GENDERS),
+                'device_token' => 'required|string',
+                'available' => 'required|boolean',
+            ]
+        );
```

In js this would be https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAICGqq+AngPoC2+ADgBQAkqmANnLrgLwB8uA5AM4QKGAJbD+AH164A1LkYs4AGlzAAOnnZbt7Xs3z8YZKPmHStSPugCOmEegAmEw6hFQA5hKoAPJACYAVgDeJQ0dcL4AM3tDY1M4c1xLXhs7R2cYVw8vfF9A4NDNCK0UiCFE8OSffyCQsOKS9wQHOFQKiys4W3s4Jzd4JtQpQoaSloA3ETA4MhgIAGsEaWTUnqcXN3c6oobefHH8EX0AI1YKla603oljstZ8KG3igF8ASgBuECUQCGoYEWg-GQoEIqAgAHcAAqEBBAlD7CAiBxfEDHYhgRYwADK1HwYE2yEymGUIDc-FaMEhxHcVGQkXwzHJ3wAVvxvAAhdGYrHxAAybjgdIZTJAuNQ5NQyFR+GOJGY0BR1CyMAA6kiYAALZAADgADN8lRBySriNQpUq4BLxoLvqt0FT8DT8ELGSTyRQRISmG7NqwAIqYCDwF0imAytUOTXIPzfTKHZibADCQlpKCg0BtIEw5IAKjK4fTXc9nkA

**Comment by evilebottnawi** [comment]
@mathieutu yep, ugly, PR welcome

**Comment by evilebottnawi** [comment]
@mathieutu i am wrong, you example use `arrow` function but in you example using `closure` [example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAICGqq+AngPoC2+ADgBQBmmUYMAltLrQCSqYA2cAJS5gAHSiiYudFhy4A5AGcIFDK1WKAPvNwA6XD35wA3OIC+AGhHjcthX3yKYZKPlU67SBegCOmVugAJppOqKxQAOaaVAAeSABMAKyJ8hY2dvL0AU4ubnAeuF7yvv5BITBhkdH4cUkpaXgZqBAqBXaeCrEJyanptvIRCIFwqG0dxXB+AXDB4fCDqNoN7fLDAG6sYHBkMBAA1gg6RSXTwaHhEb2N-fhr+KwOAEYCbceTpTOajy0C+FBXZkExhAFhAEGobGgimQoEIzQA7gAFQgIaEoW4QViBEEgR7EMAHGAAZWo+DAF2QFUwcFB4UUIxgiOIESoyHo+D49NBACtFDEAEL4wlEvIAGXCcDZHK5IFJqHpqGQuPwjxIfGgOOolRgAHUsTAABbIAAcAAZQVqIPSdcRqEqtXAFWtJaCTugmfgWfgpZyaSB6RRWJTeH7FBcBABFTAQeA+mUwFV6wKG5DxUEVe58C4AYRUrJQUGgLpAmHpABUVWj2b6zGYgA). 

Output is expected

**Comment by mathieutu** [comment]
yeah because in this example the arrow function is the equivalent in js.

**Comment by evilebottnawi** [comment]
@mathieutu no, arrow function is not equivalent `closure` in `php`

**Comment by evilebottnawi** [comment]
And please don't say `imo/standard/should be` and etc, each developer use own code style, prettier should solve this situation, your style of communication to these problems is not constructive, please stop doing this, this is open source software and each of us spends our free time on it, thanks

**Comment by evilebottnawi** [comment]
Also duplicate https://github.com/prettier/plugin-php/issues/399

**Comment by mathieutu** [comment]
@evilebottnawi ok. 
I'm sorry if I annoyed you by reporting issues, and let you know my opinion on them.
I never said "we have to", or worst "you have to", I just let you know, that "in my point of view, we should do that because...".

If you don't want any comments of the way of php developers are doing, it's ok but it will be more difficult to make it adopted. For me it's all the "we're doing like prettier" answers which are not constructive. I'm using prettier for js, ts, vue, jsx and graphql, and I have no issue with the way the code is transformed. It's just that the languages are different. 

Here, for you're arrow function example: JS dev can chose between several sort of function. Php's almost can't. The way of using callback function in php is exactly the same than arrow's in js. And the behaviour is the same. The js `function` could be considerate as equivalent as php's `Closure`, and not just callback. This is why I tried to make you understand that we cannot just apply the same transformation because it looks like the same.

I'm ok that each framework and dev has their way to do, but if we don't event consider all the things they already have in common, it will just not work at all. 😥

**Comment by evilebottnawi** [comment]
@mathieutu feel free to feedback here https://github.com/prettier/plugin-php/issues/399, right now we have a lot of problems with a more important priority (`break code`, `inline` nodes, `comments`, `parens`, `string` with double quotes and other). You example is just some ugly. I'm not against to improve output as you write above, just don't have time on this right now. It will be much more convenient if you shorten the examples to the minimum and describe what you have that we output and what you expect and why it should look like this. 

Issue was closed because it is duplicate https://github.com/prettier/plugin-php/issues/399. Thanks for using prettier :+1:

**Comment by czosel** [comment]
I think this concrete case is formatted the way it is because function arguments are formatted as 
```
func(
  a,
  b,
  c
)
```
if more than one argument contains linebreaks (which makes sense in my opinion). If we were treating the `closure` like an arrow function, it would have to be formatted on one line (`function (...) { ... }` to allow  formatting the function arguments like this
```
function (inlineArgs, [
  array,
  ...
])
```
And squeezing a closure on one line is not what we want, i guess (probably not PSR compatible either).
