### ISSUE TITLE
Prettier added useless parenthese

### ISSUE THREAD

**Issue by mathieutu** [prettier/plugin-php#610]
```diff
-        return static::class . '@' . $method;
+        return (static::class . '@' . $method);
```

**Comment by mathieutu** [comment]
Idem : 

```diff
-        return [
-                'email'    => 'required|string|email|max:255|unique:users',
+        return (
+            [
+                'email' => 'required|string|email|max:255|unique:users',
                 'password' => 'required|string|min:6|confirmed',
-            ] + self::profilesRules();
+            ] + self::profilesRules()
+        );
```

**Comment by evilebottnawi** [comment]
@mathieutu `return` always avoid parens in all cases

**Comment by mathieutu** [comment]
I'm sorry @evilebottnawi I didn't understand.
You said that return **avoid** parentheses, but prettier added them (in both cases).

**Comment by evilebottnawi** [comment]
@mathieutu 
```
return (static::class . '@' . $method);
```

look as bug.

Second example expected.

**Comment by mathieutu** [comment]
Idem here:
```diff
-        return $this->customer->paymentService ?? null;
+        return ($this->customer->paymentService ?? null);
```

Imo in php, we should not add parentheses in any return cases. (Never seen that in any php code)

**Comment by evilebottnawi** [comment]
@mathieutu already fixed in master, here you examples https://github.com/prettier/plugin-php/pull/612

**Comment by Meroje** [comment]
> Why we should avoid parens?  
Because there is not a single person anywhere doing it ?

**Comment by vjeux** [comment]
In JavaScript, there’s a “feature” called automatic semi-colon insertion that makes the following 

```js
return
  123
```

be parsed as

```js
return;
123;
```

So you have to have parenthesis if you want to make it multiline otherwise you return undefined.

```js
return (
  123
);
```

Because of this, people in js tend to put parenthesis in a lot more places than php and put { on the same line.

**Comment by mathieutu** [comment]
Thanks for the explanation @vjeux! 🙂

**Comment by evilebottnawi** [comment]
@mathieutu feel free to send a PR

**Comment by czosel** [comment]
:+1: Let's remove the braces in the PHP plugin then!

**Comment by mathieutu** [comment]
ok thanks!
As I haven't contributed yet to prettier, I don't really know how it works under the hood, and how to make that done. 

I'll try to check that when it'll be quieter at work.
