### ISSUE TITLE
parens around include

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#611]
```php
$var = include './foo.php';
// VS
$var = (include './foo.php');
```

:+1: for first
:heart: for second

**Comment by QWp6t** [comment]
Only when it's used as assignment like that. Otherwise no parentheses.

**Comment by austinpray** [comment]
Why tho

**Comment by evilebottnawi** [comment]
@austinpray ?

**Comment by evilebottnawi** [comment]
Right now we use `first` example, let's close issue. Feel free to feedback.
