### ISSUE TITLE
Nested ternary

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#614]
Input and output:
```php
$var ? $var1 ? 1 : 2 : $var2 ? 3 : 4;
```
JS is printing this example like that, which seems much more readable:
```php
$var ? ($var1 ? 1 : 2) : $var2 ? 3 : 4;
```
(from #586)

**Comment by evilebottnawi** [comment]
@czosel `ternary` in `php` works another than in other language, we already add parens in you example. Here example:
```php
$var = ($var ? $var1 ? 1 : 2 : $var2) ? 3 : 4;
```

**Comment by evilebottnawi** [comment]
Look here https://github.com/prettier/plugin-php/pull/615

**Comment by evilebottnawi** [comment]
Should be solve https://github.com/prettier/plugin-php/pull/627
