### ISSUE TITLE
ugly anonymous classes 

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#653]
**Prettier 1.14.2**

**PHP Plugin 0.6.0**

**Input:**

```php
$var = new class(
    $arg,
    'string',
    2100,
    $var ? true : false,
    $other_arg,
    function () {
        return 1;
    }
) extends SomeClass implements SomeInterface {
    public function log($msg)
    {
        echo $msg;
    }
};
```

**Output:**

```php
$var = new class(
    $arg,
    'string',
    2100,
    $var ? true : false,
    $other_arg,
    function () {
        return 1;
    }
) extends SomeClass implements SomeInterface 
{
    public function log($msg)
    {
        echo $msg;
    }
};
```

**Expected behavior:**

Expected as is, because `{` on same line is ok for anonymous classes

**Comment by evilebottnawi** [comment]
I think i wrong here.

From PSR-12:
> The opening brace MAY be on the same line as the class keyword so long as the list of implements interfaces does not wrap. If the list of interfaces wraps, the brace MUST be placed on the line immediately following the last interface.

I think this rule applies to arguments too. 

I.e. if between `class` keyword and class body something on next line `{` should be start with new line.

**Comment by czosel** [comment]
I agree. I'd interpret the rule like this: If the class definition spans multiple lines, the brace MUST be placed on a new line. That's also fitting to the two examples mentioned in [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#8-anonymous-classes).

**Comment by evilebottnawi** [comment]
@czosel yep, let'c close issue, if someone has a different opinion feel free to create new issue
