### ISSUE TITLE
If plain html code is provided, empty lines are added

### ISSUE THREAD

**Issue by vielhuber** [prettier/plugin-php#665]
I have alot of php files that contain pure html code.

Prettier PHP takes those files and adds plain empty html lines between every line.

Before:
```php
<section class="[ c-social-foot ]  [ has-text-centered ]">
  <div class="[ container  is-fluid ]">
    <div class="[ columns  is-centered ]">
      <div class="[ column ]">
```

After
```php
<section class="[ c-social-foot ]  [ has-text-centered ]">

  <div class="[ container  is-fluid ]">

    <div class="[ columns  is-centered ]">

      <div class="[ column ]">
```

This is very odd, it should remain as it was.

**Comment by evilebottnawi** [comment]
@vielhuber can you provide fill example of file

**Comment by vielhuber** [comment]
1.php: Original file
2.php: File after first save
3.php: File after second save

I'm using Windows 10 Pro and Visual Studio Code 1.27.2.

[1-2-3.zip](https://github.com/prettier/plugin-php/files/2412759/1-2-3.zip)

**Comment by evilebottnawi** [comment]
@vielhuber interesting, how you run `prettier`?

**Comment by evilebottnawi** [comment]
OR maybe you can create minimum reproducible test repo?

**Comment by vielhuber** [comment]
```
npm install --global prettier @prettier/plugin-php
```

vscode config
```
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.php$",
                "cmd": "prettier ${file} --write --print-width 200 --tab-width 4 --single-quote"
            }
        ]
    }
```

**Comment by vielhuber** [comment]
I have NO problems with normal php files.

Have you tested this on windows? I think it is a line break issue.

**Comment by Myhlamaeus** [comment]
@evilebottnawi It seems that (outside of PHP code) every CR is replaced with two CRs. I’ve tried adding tests for this, but it seems that snapshots are normalized to LF-only.

**Comment by evilebottnawi** [comment]
@Myhlamaeus can't reproduce on windows, maybe you have something wrong in editor? Maybe you can record video with all steps?

**Comment by vielhuber** [comment]
here is a video of the behaviour:

![prettier-bug](https://user-images.githubusercontent.com/3183737/46312645-fa196e80-c5c5-11e8-9088-1fcaaabfc0c9.gif)

**Comment by evilebottnawi** [comment]
@vielhuber can you send me original file to `sheo13666q@gmail.com`?

**Comment by vielhuber** [comment]
This is the simple file:

[index.zip](https://github.com/prettier/plugin-php/files/2435447/index.zip)

**Comment by evilebottnawi** [comment]
@vielhuber can't reproduce on linux/macos/windows, can you reproducilbe this using `node_modules/.bin/prettier --write index.php`?

**Comment by evilebottnawi** [comment]
@vielhuber hm try again

**Comment by evilebottnawi** [comment]
@vielhuber can't reproducible using `--write` or vs code, i will try CRLF, CR and LF, all works fine, looks you have something wrong in your env

**Comment by evilebottnawi** [comment]
@vielhuber what version of `prettier` you use?

**Comment by vielhuber** [comment]
mkdir test
cd test
npm install --save-dev prettier @prettier/plugin-php
sh node_modules/.bin/prettier --version // 1.14.3
sh node_modules/.bin/prettier --write index.php // results in the problem

**Comment by evilebottnawi** [comment]
@vielhuber i can't reproduce this on 3 machines and with virtual box with difference os and line endings. Maybe you can debug plugin?

**Comment by vielhuber** [comment]
OK, i just tested it and could reproduce it on a fresh vmware windows 10 image.

- first installed node js 10.11.0 and git 2.19
- then add node_modules\.bin\ to PATH (to run local packages on the command line)
- mkdir test
- cd test
- npm install --save-dev prettier @prettier/plugin-php
- prettier --version
- prettier --write index.php

Same result!

**Comment by vielhuber** [comment]
It is important that you put html code inside your php file. Every other file is working without any problems.

**Comment by Myhlamaeus** [comment]
@vielhuber I have added tests for this in #708; they’re also failing on [Travis CI](https://travis-ci.org/prettier/plugin-php/jobs/436280848):

```diff
- <!DOCTYPE html>\r
- <html lang="de">\r
- <head>\r
-     <meta charset="utf-8" />\r
-     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />\r
-     <title>.</title>\r
- </head>\r
- <body>\r
- \r
-     <?php echo 'foo!'; ?>\r
- \r
- </body>\r
- </html>\r
+ <!DOCTYPE html>\r\r
+ <html lang="de">\r\r
+ <head>\r\r
+     <meta charset="utf-8" />\r\r
+     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />\r\r
+     <title>.</title>\r\r
+ </head>\r\r
+ <body>\r\r
+ \r\r
+     <?php echo 'foo!'; ?>\r\r
+ \r\r
+ </body>\r\r
+ </html>\r\r
```

**Comment by vielhuber** [comment]
Awesome, it works now!
