### ISSUE TITLE
extra parens in control structures with assign

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#731]
**Prettier 1.14.3**

**PHP Plugin 0.7.0**

**Input:**

```php
if ($secondDate = $this->getDateTimeWithOptionalFormat($format, $second)) {
}
```

**Output:**

```php
if (($secondDate = $this->getDateTimeWithOptionalFormat($format, $second))) {
}
```

**Expected behavior:**

Prettier JS add parens, but i don't think it is good for PHP, maybe i am wrong.

Vote :+1: for adding parens
Vote :heart: for removing parens

Issue in prettier https://github.com/prettier/prettier/issues/5070.

**Comment by aboyton** [comment]
It’s not just JS that adds extra parens, C and C++ do it so that it’s clearer that it’s assignment not comparison.
