### ISSUE TITLE
include form

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#74]
```php
require ('somefile.php');
```
vs
```php
require 'somefile.php';
```

All popular framework use this form:
https://github.com/laravel/framework/search?l=PHP&q=require&type=&utf8=%E2%9C%93
https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=require&type=
https://github.com/yiisoft/yii2/search?l=PHP&q=require&type=&utf8=%E2%9C%93

Vote welcome.
1. :heart: - First example
2. :+1: - Second example
3. :100: Output as is

**Comment by evilebottnawi** [comment]
WordPress also use second output. Let's do it :+1:

**Comment by ichiriac** [comment]
Just for your information, the second choice is better, and there is a reason :

This code :
```php
<?php
echo include('foo.php') . ' MORE OUTPUT';
```

Does not behaves as expected, and is interpreted as :
```php
<?php
echo include 'foo.php' . ' MORE OUTPUT';
```

Resulting in a warning with a file not found. So removing parenthesis removes ambiguity on how it will be interpreted.

**Comment by evilebottnawi** [comment]
@ichiriac thanks for feedback, now we use first option, but anyone can post own opinion and vote and we can change this in future
