### ISSUE TITLE
return with comments

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#764]
**Prettier 1.14.3**

**PHP Plugin 0.8.0**

**Input:**

```php
return // Comment
    $a;
```

**Output:**

```php
return 
    // Comment
    $a;
```

**Expected behavior:**
/cc @vjeux 
Both looks good, but need advice. In PHP we don't print `(` and `)` for `return` because no one do it. Should we add `newline` if comment exists or not?

**Comment by vjeux** [comment]
My gut feeling is “why the hell would you put a comment directly after return if you have some content afterwards”. For those cases my stance with prettier is to not care that much about how the output looks like as long as it is stable.

**Comment by evilebottnawi** [comment]
@vjeux Thanks, for other keywords we don't add `hardline`, looks better don't add for consistently
