### ISSUE TITLE
[feature] support difference value for trailing commas

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#798]
Values:
- `none` doesn't print any trailing commas.
- `php5.0` print trailing commas for `array`
- `php7.2` include all for `php7.2` + `list` and `use` (grouped namepaces only).
- `php7.3` include all for `php7.2` + `function calls` (https://wiki.php.net/rfc/trailing-comma-function-calls).
- `all` is latest stable `PHP` release (right now it is `php7.2`, in near future `php7.3`).

Somebody know when `PHP` starts support trailing commas for `array` ? :smile: But `php5.0` looks good for me because minimum supported version is `5`.

Feel free to feedback

**Comment by czosel** [comment]
Right now we're supporting `none` and `all`. The `all` setting will add trailing commas in multiline arrays.
