### ISSUE TITLE
[bug] lose `&` in static lookup

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#806]
**Prettier 1.14.3**

**PHP Plugin 0.8.0**

**Input:**

```php
$var = &self::$darwinCache[$k];
```

**Output:**

```php
$var = self::$darwinCache[$k];
```

**Expected behavior:**

```php
$var = &self::$darwinCache[$k];
```

Ref: https://github.com/glayzzle/php-parser/issues/205

**Comment by BobbieGoede** [comment]
It seems this bug has returned, ampersand gets removed when formatting.

**@prettier/plugin-php v0.11.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648MCIKgtsxAOYAbKAEVB6GFHwAzNspEtpbeMqUBhdAFtrbAAoAJe-hCYsOlhwhsAxlABlGABPVVcARhgOXBZoAEdBeGh7H0U7PQMjEGIRCBgUtjS2DMMoAF8WKAp4GHQUNHgsSVA2bBgSkQrszDBBdrwQAB4AfjBqMAAdTAASXz9qKoB9ADc2CAACAF51gDIKGTADRba2BF8ACkXFgDEAVQA5C1EASWR7q4BKAG4QMqA)

**Input:**
```php
<?php
$cached_var = &drupal_static(__FUNCTION__);
```

**Output:**
```php
<?php
$cached_var = drupal_static(__FUNCTION__);

```

**Comment by evilebottnawi** [comment]
@BobbieGoede it is php5? Because in php7 it is not work

**Comment by evilebottnawi** [comment]
@BobbieGoede works good in master, we need do release, will be in near future
