### ISSUE TITLE
Unquoted array keys in interpolated strings

### ISSUE THREAD

**Issue by claytonrcarter** [prettier/plugin-php#831]
**Prettier 1.14.3**

**PHP Plugin 0.9.0**

**Input:**

```php
echo "This is my array value: $anArray[key]";
```

**Output:**

```php
echo "This is my array value: {$anArray[key]}";
```

This continues to work as before, but PHP starts generating warnings: `PHP Warning:  Use of undefined constant key - assumed 'key' (this will throw an Error in a future version of PHP)`

**Expected behavior:**

Not sure. Perhaps:

```php
echo "This is my array value: {$anArray['key']}";
```

**Comment by evilebottnawi** [comment]
@claytonrcarter hm, should output `Warning` on `echo "This is my array value: $anArray[key]";`. Here good question should we `{` and `}` remove or not. Can you have example when removing `{` and `}` break code?

**Comment by claytonrcarter** [comment]
Sorry, I don't understand your question. If adding `{` and `}` will cause PHP to issue warnings or errors, then it seems that the problem is adding them , not removing them.

Honestly, in my case, I don't mind fixing my code by adding the `'`, but I'm not sure that it is good for prettier to change code in a way that then causes PHP to begin generating warnings or errors.

You know much more about this than I do, but it seems like there would be to options when encountering an unquoted array key in a string: either leave that variable alone (eg `$anArray[key]`) or "fix" it by adding braces *and* quotes (eg `{$anArray['key']}`)

Here is a terminal session:
```
$ php --version
PHP 7.2.6 (cli) (built: May 25 2018 06:18:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.6, Copyright (c) 1999-2018, by Zend Technologies
$ prettier --version
1.14.3
$ cat test.php
<?php

$anArray = ['key' => 'value'];

echo "This is an array value: $anArray[key]\n";
$ php test.php
This is an array value: value
$ prettier --write test.php
test.php 32ms
$ cat test.php
<?php

$anArray = ['key' => 'value'];

echo "This is an array value: {$anArray[key]}\n";
$ php test.php
PHP Warning:  Use of undefined constant key - assumed 'key' (this will throw an Error in a future version of PHP) in /Users/crcarter/Software/Fedco/shared-order-logic/test.php on line 5

Warning: Use of undefined constant key - assumed 'key' (this will throw an Error in a future version of PHP) in /Users/crcarter/Software/Fedco/shared-order-logic/test.php on line 5
This is an array value: value
$
```

Thank you!

**Comment by evilebottnawi** [comment]
Yes it is bug, need fix

**Comment by evilebottnawi** [comment]
Problem in parser :disappointed: https://github.com/glayzzle/php-parser/issues/175, we need fix it.

Example of tests.
Input:
```php
$var = "This is my array value: $anArray[key]";
$var = "This is my array value: {$anArray[key]}";
$var = "This is my array value: { $anArray[key]}";
$var = "This is my array value: { 
$anArray[key]
}";
$var = "This is my array value: {$anArray[key] }";
$var = "This is my array value: {$anArray[key] /* Comment */ }";
$var = "This is my array value: {$anArray[key] 
}";
$var = "This is my array value: { $anArray[key] }";
$var = "This is my array value: { 
$anArray[key]
}";
```

Output:
```
$var = "This is my array value: $anArray[key]";
$var = "This is my array value: {$anArray[key]}";
$var = "This is my array value: { {$anArray[key]}}";
$var = "This is my array value: { 
{$anArray[key]}
}";
$var = "This is my array value: $anArray[key]";
$var = "This is my array value: $anArray[key] /* Comment */";
$var = "This is my array value: {$anArray[key]}";
$var = "This is my array value: { $anArray[key] }";
$var = "This is my array value: { 
{$anArray[key]}
}";
```

Some expressions specifically have space before `{` to ensure we print all as is.

**Comment by evilebottnawi** [comment]
Try to find this on our side

**Comment by karptonite** [comment]
I’d suggest that almost always, this should be fixed by adding braces and quotes. As the error says, it is working because PHP assumes that `key` Is a `key` because it is currently undefined. But there is nothing preventing some other code from `define`ing `key` at some point, creating a very hard to find bug.

I imagine the only time you wouldn’t want to add both braces and quotes is when `key` really is defined. Unfortunately, I don’t think we have any way of knowing when that might be the case.
