### ISSUE TITLE
Including plugin-php in with standalone in Browser

### ISSUE THREAD

**Issue by EdibleClover** [prettier/plugin-php#842]
I can't find any documentation on including the prettier parser with the standalone.js file for us in a browser project. 

Would be great if some docs would be added showing a clear way to do this if at all possible.

**Comment by evilebottnawi** [comment]
@EdibleClover hm, i think it is require work on `prettier` side, `prettier` create bundle for `browsers` and need investigate how it is compatibility with plugin api, feel free investigate, right now it is not priority issue

**Comment by EdibleClover** [comment]
Thanks for the reply, Ill poke around, perhaps there's a way to just bundle it all into a standalone parser file for ease of use

**Comment by evilebottnawi** [comment]
@EdibleClover maybe, i am glad to any help, feel free to send a PR with docs how it is can be done

**Comment by Loilo** [comment]
@evilebottnawi FWIW, I got this plugin to work in the browser (through webpack) by just replacing all `require("prettier")` calls with `require("prettier/standalone")`, so these Prettier builds seem to be compatible regarding the Plugin API.

@EdibleClover If you're using webpack to generate your browser code, you could just configure an alias that points all `prettier` requests to `prettier/standalone`:

```js
// Your webpack.config.js

module.exports = {
  // ...
  resolve: {
    alias: {
      prettier: 'prettier/standalone'
    }
  }
}
```

This should make the plugin work in the browser.

**Comment by czosel** [comment]
@Loilo This is great news, thank you for sharing! Would you have the chance to create a pull request with your webpack setup?

@evilebottnawi I think we have to publish a built that works in browsers as part of our regular releases. Once we have that, it should be relatively straight forward to include it as a plugin in the playgrounds' web worker.

**Comment by evilebottnawi** [comment]
@czosel can you take care about this?

**Comment by czosel** [comment]
@evilebottnawi I've been looking into this last weekend, and I can definitely try to push this forward a bit. Just not sure how much long it'll take, I'm a bit swamped with work these days ...

**Comment by evilebottnawi** [comment]
@czosel no need to rush :+1:

**Comment by Loilo** [comment]
@czosel Like, a pull request for the documentation? Or would you like me to implement a build chain for a prettier-like standalone build?

**Comment by czosel** [comment]
@Loilo The build chain for a prettier-like standalone build, or actually rather something like the standalone parser/printer bundle for each language, is what we ultimately need. If you could send a PR for that, that would of course be amazing! Otherwise, feel free to share anything that might help us to get there faster :wink:

**Comment by suchipi** [comment]
Everything should be complete on the prettier side; I did this with the lua plugin back when we first shipped standalone. You need to use rollup or etc to make a bundle of your plugin, and then you can pass it as a plugin in prettier's options iirc

**Comment by evilebottnawi** [comment]
@suchipi can you provide some examples?

**Comment by Loilo** [comment]
That's what I thought. The `prettier/standalone` already does what it should.

What we would do is create one build for Node.js and one `standalone` build for the browser (in analogy to Prettier accessed as `@prettier/plugin-php` and `@prettier/plugin-php/standalone`).

The only thing we'd need to vary in the plugin is which version of Prettier we `require` — `prettier` or `prettier/standalone`. We should be able to relatively easily control this with Rollup and e.g. an environment variable.

**Comment by suchipi** [comment]
Here's an example:

https://jsbin.com/zojalinosu/edit?html,output

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Prettier browser plugin example</title>
  
  <!-- this script define the global `prettier` -->
  <script src="https://cdn.jsdelivr.net/npm/prettier@1.16.4/standalone.js"></script>
  
  <!--
    packd.now.sh makes a rollup bundle; though ideally
    you should ship one with your package. in this case
    it defines the global `_prettier_pluginLua`
  -->
  <script src="https://packd.now.sh/@prettier/plugin-lua@0.0.1"></script>
</head>
<body>
<pre>
<code>
      function foo ( )
        local a    =
           4
          return a
         end
</code>
</pre>
  <button>Format</button>
  <script>
    var code = document.querySelector("code");
    var button = document.querySelector("button");
    button.onclick = function() {
      code.textContent = prettier.format(
        code.textContent,
        {
          plugins: [_prettier_pluginLua],
          parser: "lua"
        }
      )
    }
  </script>
</body>
</html>
```

![2019-02-05 11 33 38](https://user-images.githubusercontent.com/1341513/52299321-f44be500-2939-11e9-875d-205dffeac9da.gif)

**Comment by Loilo** [comment]
There we go, pull request has landed. 🙂

The implementation is feature-complete, tests and docs are still missing though. I'd like to add those when all points listet in the PR are clarified.
