### ISSUE TITLE
Support php7.3 and php7.4

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#854]
No issue template. We need improve parser (https://github.com/glayzzle/php-parser):

# php7.3

- [x] Support trailing commas in `call`/`isset`/`unset` (spec https://wiki.php.net/rfc/trailing-comma-function-calls)
- [ ] Support new syntax for NowDoc and HereDoc (spec https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes)
- [x] Array Destructuring supports Reference Assignments
- [x] Instanceof Operator accepts Literals (i think we already support, need add tests)

# php7.4

- [x] https://wiki.php.net/rfc/null_coalesce_equal_operator
- [x] https://wiki.php.net/rfc/typed_properties_v2
- [x] https://wiki.php.net/rfc/arrow_functions_v2
- [x] https://wiki.php.net/rfc/spread_operator_for_array
- [x] https://wiki.php.net/rfc/numeric_literal_separator

Something missing? Any help welcome :+1:

**Comment by cseufert** [comment]
From the looks it closing #1346 should close this too, so does this mean that prettier should work find for all php 7.4 features?

**Comment by czosel** [comment]
@cseufert Yes! I updated the checkboxes above accordingly. Once #1291 and #1295 landed, we have full support for PHP 7.3 and 7.4! :tada: I hope we can release this real soon :wink:
