### ISSUE TITLE
Prettier adding extra unnecessary parenthesis in method with assignment call

### ISSUE THREAD

**Issue by cseufert** [prettier/plugin-php#857]
**Prettier 1.15.3**

**PHP Plugin 0.9.0-prerelease.5**

```sh
# Options (if any):
{
  "singleQuote": true,
  "tabWidth": 2,
  "bracketSpacing": false,
  "trailingComma": "all"
}
```

**Input:**
```php
    $fieldWrap->addChild($span= new Tag\Html('span'));
```

**Output:**

```php
    $fieldWrap->addChild(($span= new Tag\Html('span')));
```

**Expected behaviour:**
Prettier does not need to double up the braces around the assignment inside the method call.

**Comment by hawkrives** [comment]
I don't know about this case in particular, but I know that in, e.g., a `while` loop, prettier will add an extra set of parens to indicate that assignment is happening instead of an equality check – like `while (($var = $other)) {`.

I'd imagine that assignment within a method call is doing this for the same reasons.

**Comment by hawkrives** [comment]
@evilebottnawi just something like this https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVB3AFgSwDZyoAURAHgLyoCeAlDasADpTrqmqUBOAhlACY5YRGs1bUOqHv0Exho1AF8QAGhAQADjBzQAzslDdOnCBgAKhhHpTcAbhBx8VIAEY8wAazgwAyuu5hBAHNkGE4AVzhVLBgAWzwAdVx4HT8wOG9LHC0bLKpkcB09VUEdOE4YUx5AmO5kADNuPFLVACsdUgAhN08fbhi4ABlBOHrG5pA20m8gggBFMIh4UabIkD9OUs58525nKjxoJ3VOGXiHGCxkAA4ABlVjiFL4nnV847hNmxHVTjgARzCOF+lW41VqSAaK1UpRiOBC4VWOhmcHmixGELGqxguzOfAuyAATKpQtx8EEAMIQGI1fJQaDfEBhUoAFV2VkhpQUCiAA

I personally like the extra parentheses around assignment in odd locations, in both JS and PHP, but maybe I'm in the minority opinion here.

**Comment by evilebottnawi** [comment]
@hawkrives we remove don't add parens in this case because php and js have difference how built-in function works, many php function return `null` when something wrong or something can be executed so in php it is normal practice use `if ($content = file_get_content('file.text'))`.

**Comment by evilebottnawi** [comment]
Maybe for while we also don't add parens

**Comment by hawkrives** [comment]
@evilebottnawi ah, ok. Thanks for the explanation.

**Comment by evilebottnawi** [comment]
/cc @czosel 
1. what do you think about extra parens in control structure

Now:
```
if (($file = file_get_content())) {
}
```

I think we should avoid this, exclude `while`

2. what do you think about extra parens in arguments for function/new/etc

```
call($file = new Foo(), $foo, $bar);
```

I think we should avoid parens here too in PHP

**Comment by czosel** [comment]
Generally I like the extra parens if we spot an assignment in an unusual place. `if ($file = file_get_content()) {` indeed seems common in PHP, so we might not want to add parens there. Assignment in function arguments or in `while` looks odd to me, so I'd leave the extra parens there. Or can you point to some typical use cases for that @evilebottnawi?

**Comment by evilebottnawi** [comment]
@czosel After investigate in `laravel`/`symfony`/`drupal` code based it is frequent practice to do `call($var = new Foo())`.

**Comment by czosel** [comment]
Alright, I'm good with dropping the parens then.

**Comment by evilebottnawi** [comment]
Just not for `while`, popular code:
```
while ($info = mysql_fetch_array($data_jurisdiction)) {}
```
