### ISSUE TITLE
Die and Exit ERROR

### ISSUE THREAD

**Issue by rafael-figueiredogluz** [prettier/plugin-php#871]
In wordpress we need to use exit and die with wp_redirect function. But prettier convert "exit;" to "exit();" and the same occurs with "die;".

How can I configure to skip this?

**Comment by czosel** [comment]
Hi @rafael-figueiredogluz!
`exit;` and `exit();` should behave exactly the same way, so prettier formats `exit` as `exit()` for consistency. So if your code still works as before, I'd recommend to just stick to `exit()` - if not, can you paste some code and more details about the issue?

**Comment by evilebottnawi** [comment]
@rafael-figueiredogluz About new options https://prettier.io/docs/en/option-philosophy.html, anyway you can use `phpcs` or other tool after prettier to change some places in you code base (for `js` it is good practice use `prettier` + `eslint`)

**Comment by rafael-figueiredogluz** [comment]
Hi @czosel,

The function I'm using is this:
https://codex.wordpress.org/Function_Reference/wp_safe_redirect

When was convert to exit() the function wasn't work properly.

**Comment by evilebottnawi** [comment]
@rafael-figueiredogluz what? `exit;` and `exit();` is same

**Comment by evilebottnawi** [comment]
```
exit;
exit();
exit(0);
```
Is same

**Comment by czosel** [comment]
@rafael-figueiredogluz can you paste the code before and after formatting and the error wordpress threw?

**Comment by evilebottnawi** [comment]
@rafael-figueiredogluz close, feel free to feedback

**Comment by rafael-figueiredogluz** [comment]
@czosel @evilebottnawi sorry to take this long to answer you. I don't have the exactly code more but today I tried to replicate and nothing happens.

Thanks for your answers.
