### ISSUE TITLE
[bug] prettier-php formats some methods in my class with brace and closing paren  both on separate lines

### ISSUE THREAD

**Issue by gauthierm** [prettier/plugin-php#929]
**Prettier 1.15.3**

**PHP Plugin 0.9.0**

```sh
# Options (if any):
--single-quote
```

**Input:**

Original file is https://github.com/silverorange/swat/blob/master/Swat/SwatString.php

```php
public static function ellipsizeMiddle(
		$string,
		$max_length,
		// @codingStandardsIgnoreLine
		$ellipses = ' … ', // the spaces are non-breaking spaces
		&$flag = null
	) {
		$string = trim($string);

...
```

**Output:**

```php
public static function ellipsizeMiddle(
		$string,
		$max_length,
		// @codingStandardsIgnoreLine
		$ellipses = ' … ', // the spaces are non-breaking spaces
		&$flag = null
	)
	{
		$string = trim($string);

...
```

**Expected behavior:**

I expected the opening brace to go on the same line as the paren. Other multiline method signatures in the same file are formatted with the paren and brace on the same line.

The file is quite large, but if I delete everything except the problem method the problem remains. I suspect the problem is related to the inline comment in the method signature. I can adjust my code to remove the inline comments but thought I should file a bug regardless.

**Comment by evilebottnawi** [comment]
@gauthierm thanks for issue
