### ISSUE TITLE
Thanks PHP Prettier Team

### ISSUE THREAD

**Issue by virgofx** [prettier/plugin-php#933]
I just wanted to say that there is a huge community following this project and we are all excited with the level of involvement getting this plugin to production ready stability. It is going to change/revolution the entire PSR-2 debacle for teams and I'm personally eager for the 1.0 release. Keep up the great work guys. Any updates on the 1.0 milestone ETA (again not trying to rush ... been following this project for over a year now ... just curious)

**Comment by evilebottnawi** [comment]
@virgofx Thanks, we are already very close to stable release. In near time we release `0.10.0` with a lot of fixes and improvements. 

Main problem for stable release is `inline` node, i.e.
```php
<div><?php echo $other_var; echo $var; ?></div>
```

In some cases it is very hard to print, but i think we solve this for `0.11.0`.

Milestones:
1. `0.10.0` (release tomorrow) - fixed bugs with `strings` in double quotes.
2. `0.11.0` (next mouth release) - fixed problem with `inline` nodes.
3. `0.12.0` (next mouth release + 2 week) - `PHP 7.3` support.
4. Stable release.

Maybe we can do more release if find bugs whats break code.
