### ISSUE TITLE
Force array/list shorthand notation

### ISSUE THREAD

**Issue by bfanger** [prettier/plugin-php#939]
Force the use of shorthand array's, (available since php 5.4)

## Reasoning:
The old syntax looks like a method call, not like an array. 
The new syntax is shorter and improves readability as it looks like an array.

Other issues regarding array's use the shorthand notation in their example code, indicating a preference towards shorthand.

**Input:**

```php
$my_array = array(1, 2, 3);
```

**Desired output:**

```php
$my_array = [1, 2, 3];
```

**Comment by evilebottnawi** [comment]
hm, we need `--engine` option for this improvement, because some people can use prettier for `php5.3`/`php5.2` and lower. Not sure it is part of prettier, maybe better use `linter` for this.

/cc @czosel

**Comment by hawkrives** [comment]
Is there any reason not to use the shorthand on newer PHP versions, though? (I, for one, would really like this transformation.)

**Comment by evilebottnawi** [comment]
@hawkrives no, we officially support `php5.0`, `php5.1` and etc so we can broke their code, it can be solved only added `engine` field, but it is discussed

**Comment by czosel** [comment]
These kind of transformations are not Prettier's job, but instead done by a linter. PHP-CS-Fixer seems to support this use-case as well (`array_syntax`). If PHP-CS-Fixer also support automatically fixing rule violations, a setup like eslint-prettier for JS would be possible for us as well.

**Comment by Billz95** [comment]
> These kind of transformations are not Prettier's job, but instead done by a linter. PHP-CS-Fixer seems to support this use-case as well (`array_syntax`). If PHP-CS-Fixer also supports automatically fixing rule violations, a setup like eslint-prettier for JS would be possible for us as well.

For anyone who's interested in integrating `prettier` into the workflow of `php-cs-fixer` as a fixer, I've wrote a customised fixer to execute `prettier` before all other fixers.
https://gist.github.com/Billz95/9d5fad3af728b88540fa831b73261733

**Comment by evilebottnawi** [comment]
@Billz95 i think we can add this to docs/recipes

**Comment by Billz95** [comment]
> @Billz95 i think we can add this to docs/recipes

Hmmm sorry would you mind elaborating a bit on `docs/recipes`? Couldn't find much info about it, thx

**Comment by evilebottnawi** [comment]
@Billz95 we can create recipes directory and put your example, also add link on this in README, it is allow faster integrate prettier for other developers

**Comment by evilebottnawi** [comment]
Other idea - use `composer.json` to determinate php version, it is increase 0CJS configuration. Example:
```json
{
  "require": {
    "php": "^7.1",
  }
}
```

**Comment by xdega** [comment]
> @hawkrives no, we officially support `php5.0`, `php5.1` and etc so we can breake their code, it can be solved only added `engine` field, but it is discussed

Why would you be supporting wildly out-of-date, hardly-used, deprecated versions of PHP? 
I would suggest PHP 5.6 as the earliest, as it still has a significant user-base (albeit still deprecated).

**Comment by xdega** [comment]
I second this suggestion. PSR-2 isn't explicit on array syntax, but their examples are shorthand: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#43-methods

**Comment by evilebottnawi** [comment]
@xbuzz because we should not break code, it is prettier

**Comment by xdega** [comment]
@evilebottnawi You may have accidentally tagged the wrong person there. 

I understand the concern however, this is catering for ~20% of PHP 5 users (https://w3techs.com/technologies/details/pl-php/5/all), whom are using legacy systems, and likely have no intention of desire to use a tool like Prettier.

The tradeoff is that this propagates a syntax that is not recommended, barely used by the consensus (PSR-2), and unusual in the grand scheme of things. All for the sake of the minority.

That being said, a reasonable compromise here would be to simply allow the config to determine `long` vs `short` array syntax. 

Forcing long-form array syntax would be an unfortunate deal-breaker here, and I am sure I am not alone in that.

**Comment by karptonite** [comment]
@xdega I don’t think there is any talk of forcing long-form array syntax—just leaving array syntax unchanged.

I’m in favor of forcing short form array syntax If the composer.json file requires a version of PHP new enough to allow it.  This seems like something that should be in prettier’s purview to me—array syntax is esssentially a formatting choice, since the two forms are functionally identical. I see it in the same class of changes as changing double quoted to single quotes in js, as prettier already does.

**Comment by bfanger** [comment]
The presence of a composer.json is enough, as even [Composer 1.0.0 requires PHP 5.3.2+](https://github.com/composer/composer/blob/32df3aa8cdbdaa16df9491b5e672e81c87f94c78/doc/00-intro.md) to run.

**Comment by QWp6t** [comment]
@xdega 20% seems like an aggressively high estimate. That could be outdated.

According to packagist, it looks to me like it's [about 2%](https://blog.packagist.com/php-versions-stats-2018-2-edition/), and according to WordPress, it's [around 7%](https://wordpress.org/about/stats/).

**Comment by czosel** [comment]
@karptonite Good point about the analogy to single/double quotes! From a user perspective I liked the idea of rewriting arrays from the beginning, but I wanted to make sure that we’re not slowly adopting too much linting functionality. Anyway, I’m all in for rewriting arrays now!

@evilebottnawi Sounds good!

**Comment by angry-dan** [comment]
> These kind of transformations are not Prettier's job

I think this is prettiers job. `[]` and `array()` are syntactically equivalent in PHP, for engines that support it, the choice is purely stylistic. Prettier should take an opinion on it and enforce that opinion. I doubt anyone writing a style guide for PHP in 2019 would recommend mixing the two styles nor would they be likely to allow the old style.

**Comment by bfanger** [comment]
While we wait for prettier to implement rewriting the array notation,
I'll share my workaround with [phpcbf (PHP Code Beautifier and Fixer)](https://github.com/squizlabs/PHP_CodeSniffer):
```sh
phpcbf --standard=Generic --sniffs=Generic.Arrays.DisallowLongArraySyntax file.php
```

**Comment by czosel** [comment]
We just posted a little RFC-style issue that proposes a way to move forward with this over at #1280. Your feedback would be appreciated!

**Comment by czosel** [comment]
During implementation a related question about list formatting came up: Since PHP 7.1, lists also have a [short form](https://wiki.php.net/rfc/short_list_syntax), i.e.

```php
list($a, $b) = $arr;
# becomes
[$a, $b] = $arr;
```
Currently, we're printing the form just the way we find it - but since we introduced `phpVersion` it would be possible to always print the short form when phpVersion >= 7.1, and otherwise always the long form.

What do you think? Feel free to post a :+1: reaction for automatic conversion to short forms (just like we decided to do for `array`) or :-1: to leave things the way the are now.

**Comment by czosel** [comment]
Array shorthand syntax has landed in `v0.14.0`, but let's keep this issue open until shorthand `list` syntax has landed as well (#1351).

**Comment by sparcbr** [comment]
I think this issue can be closed

**Comment by xdega** [comment]
@czosel Thanks for your work here. Much appreciated.

**Comment by pshechko** [comment]
Is there any way to forse the old syntax?
