### ISSUE TITLE
Indent multiple variables value on the same level

### ISSUE THREAD

**Issue by muuvmuuv** [prettier/plugin-php#970]
I'm sorry if this is out of scope of prettier, but I find it really handy and more beautiful if in variable blocks the values are intended on the same level. I would like to discuss this. Any if all are against this then the formatter should remove those spaces between the end of the variable and the `=`.

**Prettier 1.16.4**
**PHP Plugin 0.10.0**

```sh
# Suggested:
--indent-blocks
```

**Input:**

```php
$params = $template->params;
$referer = AdditiveHelper::getReferer();
$templateDetails = AdditiveHelper::getTemplateDetails();
```

**Output:**

```php
$params          = $template->params;
$referer         = AdditiveHelper::getReferer();
$templateDetails = AdditiveHelper::getTemplateDetails();
```

**Comment by evilebottnawi** [comment]
Thanks for issue, i don't think we need this. But we can keep open issue for other developers and voting

**Comment by captn3m0** [comment]
+1 for this.

We have lots of constant definitions that are getting re-aligned by prettier.

**Comment by muuvmuuv** [comment]
@evilebottnawi so then if we don't need this, prettier-php should remove those spaces. ATM it does nothing and I have mixed intended and not intended variable blocks.

@captn3m0 it is more helpful to 👍 on the issue instead of saying +1 or do both to explain your use case as a comment and give a 👍 👎

**Comment by evilebottnawi** [comment]
@muuvmuuv we already remove spaces

**Comment by muuvmuuv** [comment]
@evilebottnawi really? I hadn't seen any change to my files. Maybe it's broken on my end. Hmm. I'll keep that in mind and will open another issue if this happens again after this is out of WIP status

**Comment by evilebottnawi** [comment]
Feel free to open issue
