### ISSUE TITLE
Make custom formats

### ISSUE THREAD

**Issue by pistou** [prettier/plugin-php#988]
Is there a way to make custom formats for instructions `if`, `switch`, `for`, etc. ?

For instance:

**Input:**

```php
if ($condition == true) {
    // do whatever
}

$array1 = array("foo" => "bar");
$array2 = array("foo" => "bar", "lorem" => "ipsum");

```

**Output:**

```php
// Same structure for Switch and For loops
if ( $condition == true )
{
    // do whatever
}

$array1 = array("foo" => "bar"); // Remains one line as there is only one value
$array2 = array(
    "foo" => "bar",
    "lorem" => "ipsum"
);
```

Can I make a kind of template or something so I can format things the way I need?

**Comment by evilebottnawi** [comment]
@pistou no, is is prettier and we don't have option(s) to change your format, it is main advantage of `prettier`

**Comment by Loilo** [comment]
@pistou For more information, see [this article](https://prettier.io/docs/en/option-philosophy.html).

**Comment by czosel** [comment]
@pistou While we're quite conservative about adding options, you can always suggest changes that you would like to see in how we're formatting code!

**Comment by czosel** [comment]
No, usually adopting prettier means convincing your team to not worry about stylistic coding conventions anymore and _just use prettier_ :tm: :wink:
