### ISSUE TITLE
The PHP CS Fixer recipe is broken on windows

### ISSUE THREAD

**Issue by lllopo** [prettier/plugin-php#993]
The recipe about integrating Prettier with PHP CS Fixer is great, but has a bug on windows. The temporary file name function replaces the directory separator with underscore, but the author forgot the fact that on windows the path starts with drive name and ':'. So, this ':' remains in the generated file name and effectively makes it invalid. The fix would be to replace the ':' with underscore too.

**Comment by evilebottnawi** [comment]
PR welcome
